#!/usr/bin/env python3
# coding=utf-8

#粗排 2 阶段相关队列

final_channel_sort_queues = [
  {
    "name" : "cascade_score",
    "weight" : 1.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_pctr",
    "weight" : 0.1,
    "power_weight_attr" : "explore_mc_ensemble_s2_pctr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pctr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pctr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pctr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pctr_dynamic_weight",
    "user_xtr" : "realtime_ctr",
    "rank_cliff_attr": "explore_mc_ensemble_pctr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pctr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pctr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pctr_raw_power_weight",
    "fractile_name": "mc_ensemble_pctr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pctr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pctr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_pltr",
    "weight" : 0.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_pltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pltr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pltr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pltr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pltr_dynamic_weight",
    "user_xtr" : "realtime_ltr",
    "rank_cliff_attr": "explore_mc_ensemble_pltr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pltr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pltr_rank_cliff_min",
    "score_threshold": "user_emp_ltr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pltr_raw_power_weight",
    "fractile_name": "mc_ensemble_pltr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pltr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pltr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_pwtr",
    "weight" : 0.45,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pwtr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pwtr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pwtr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pwtr_dynamic_weight",
    "user_xtr" : "realtime_wtr",
    "rank_cliff_attr": "explore_mc_ensemble_pwtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pwtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pwtr_rank_cliff_min",
    "score_threshold": "user_emp_wtr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pwtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pwtr_raw_power_weight",
    "fractile_name": "mc_ensemble_pwtr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pwtr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pwtr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_pftr",
    "weight" : 0.05,
    "power_weight_attr" : "explore_mc_ensemble_s2_pftr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pftr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pftr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pftr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pftr_dynamic_weight",
    "user_xtr" : "realtime_ftr",
    "rank_cliff_attr": "explore_mc_ensemble_pftr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pftr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pftr_rank_cliff_min",
    "score_threshold": "user_emp_ftr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pftr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pftr_raw_power_weight",
    "fractile_name": "mc_ensemble_pftr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pftr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pftr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_plvtr",
    "weight" : 0.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_plvtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_plvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_plvtr_raw_power_weight",
    "fractile_name": "mc_ensemble_plvtr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_plvtr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_plvtr_fractile_power_weight"
  },
  {
    "name" : "mc_ensemble_plvtr2",
    "weight" : 0.12,
    "power_weight_attr" : "explore_mc_ensemble_s2_plvtr2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_plvtr2_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_plvtr2_raw_power_weight",
    "fractile_name": "mc_ensemble_plvtr2_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_plvtr2_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_plvtr2_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_psvtr",
    "weight" : -0.1,
    "power_weight_attr" : "explore_mc_ensemble_s2_psvtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ensemble_ptr",
    "weight": 0.05,
    "power_weight_attr": "explore_mc_ensemble_s2_ptr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_ensemble_pptr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pptr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pptr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pptr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pptr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pepstr",
    "weight" : 0.3,
    "power_weight_attr" : "explore_mc_ensemble_s2_pepstr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pepstr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pepstr_raw_power_weight",
    "fractile_name": "mc_ensemble_pepstr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pepstr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pepstr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_pcestr",
    "weight" : 0.18,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcestr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pcestr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcestr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pcmtr",
    "weight" : 0.18,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcmtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_ensemble_pcmtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pcmtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pcmtr_rank_cliff_min",
    "score_threshold": "user_emp_cmtr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pcmtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcmtr_raw_power_weight",
    "fractile_name" : "mc_ensemble_pcmtr_fractile",  # 12
    "fractile_weight_attr": "explore_mc_ensemble_s2_pcmtr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pcmtr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_pptime",
    "weight" : 0.4,
    "power_weight_attr" : "explore_mc_ensemble_s2_pptime_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_pwatch_time",
    "weight" : 0.45,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwatch_time_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_ppwatch_time_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_ppwatch_time_raw_power_weight",
    "fractile_name": "mc_ensemble_pwatch_time_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pwatch_time_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pwatch_time_fractile_power_weight",
  },
  {
    "name": "mc_ensemble_peftr",
    "weight": 0.5,
    "power_weight_attr": "explore_mc_ensemble_s2_eftr_score_power_weight",
    "weight_attr": "mc_eftr_ensemble_sort_weight_s2",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_peftr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_peftr_raw_power_weight",
    "fractile_name": "mc_ensemble_peftr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_peftr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_peftr_fractile_power_weight",
  },
  {
    "name": "mc_ensemble_pefctr",
    "weight": 0.5,
    "power_weight_attr": "explore_mc_ensemble_s2_efctr_score_power_weight",
    "weight_attr": "mc_efctr_ensemble_sort_weight_s2",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pefctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pefctr_raw_power_weight",
    "fractile_name": "mc_ensemble_pefctr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pefctr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pefctr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_pcltr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "variant_weight" : "explore_mc_ensemble_s2_pcltr_variant_weight",
    "avg_xtr" : "avg_cltr",
    "min_ratio" : "explore_mc_ensemble_pcltr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pcltr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pcltr_dynamic_weight",
    "user_xtr": "realtime_cltr",
    "rank_cliff_attr": "explore_mc_ensemble_pcltr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pcltr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pcltr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pcltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcltr_raw_power_weight",
    "fractile_name": "mc_ensemble_pcltr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pcltr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pcltr_fractile_power_weight",
  },
  {
    "name": "mc_ensemble_opportunity_cost_score",  #粗排机会成本队列
    "weight": 0.8,
    "power_weight_attr": "explore_mc_ensemble_s2_opportunity_cost_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_opportunity_cost_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_pwtd",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwtd_power_weight",
    "weight_attr" : "mc_wtd_ensemble_sort_weight_s2",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_ensemble_pwtd_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pwtd_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pwtd_rank_cliff_min"
  },
  {
    "name": "mc_ensemble_pwtd_inverse", 
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_pwtd_inverse_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_pwtd_inverse_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_pwtd_inverse_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_pwtd_inverse_raw_power_weight",
    "fractile_name": "cascade_pwtd_inverse_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_wtd_inverse_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_wtd_inverse_fractile_power_weight",
  },
  {
    "name": "mc_ensemble_pfptr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_pfptr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_pfptr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_pfptr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_pfptr_raw_power_weight",
  },
  {
    "name": "mc_ensemble_ordinal_wtd",  
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_ordinal_wtd_weight",
    "weight_attr": "explore_mc_ensemble_s2_ordinal_wtd_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ensemble_ordinal_prob",  
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_ordinal_prob_weight",
    "weight_attr": "explore_mc_ensemble_s2_ordinal_prob_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ada_xtr_score",  #粗排播放完成度队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_mc_ada_xtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_mc_ada_xtr_score_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "diversity_fr",  #粗排播放完成度队列
    "weight": 0.0,
    "power_weight_attr": "xlife_mc_ensemble_s2_diversity_fr_power_weight",
    "weight_attr": "xlife_mc_ensemble_s2_diversity_fr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "use_new_pow_func": "xlife_diversity_fr_use_new_pow_func",
    "new_pow_func_coeff": "xlife_diversity_fr_new_pow_func_coeff",
    "new_pos_func_bias": "xlife_diversity_fr_new_pos_func_bias"
  },
  {
    "name": "hate_fr",  #粗排topkmgs hate 队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_hate_fr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_hate_fr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "use_new_pow_func": "explore_hate_fr_use_new_pow_func",
    "new_pow_func_coeff": "explore_hate_fr_new_pow_func_coeff",
    "new_pos_func_bias": "explore_hate_fr_new_pos_func_bias"
  },
  {
    "name": "mc_ensemble_prerank_er",  #粗排 LTR
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_prerank_er_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_prerank_er_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "cascade_phtr",  #粗排 htr
    "weight": 0.0,
    "reverse_order": True,
    "power_weight_attr": "explore_mc_ensemble_s2_phtr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_phtr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_s2_ensemble_phtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_s2_ensemble_phtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_s2_ensemble_phtr_rank_cliff_min",
    "rank_height_attr": "explore_mc_s2_ensemble_phtr_rank_height",
  },
  {
    "name": "cascade_phtr",  #粗排 htr 正序
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_phtr_in_order_power_weight",
    "weight_attr": "explore_mc_s2_phtr_in_order_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_phtr_in_order_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_phtr_in_order_raw_power_weight",
    "score_threshold": "explore_mc_s2_phtr_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_phtr_in_order_rank_height",
  },
  {
    "name": "global_emphtr_score",  #粗排 emp htr 正序
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_emp_phtr_in_order_power_weight",
    "weight_attr": "explore_mc_s2_emp_phtr_in_order_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_emp_phtr_in_order_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_emp_phtr_in_order_raw_power_weight",
    "score_threshold": "explore_mc_s2_emp_phtr_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_emp_phtr_in_order_rank_height",
  },
  {
    "name": "global_empwtr_score",  
    "weight": 0.0,
    "power_weight_attr": "life_mc_s2_emp_pwtr_power_weight", 
    "weight_attr": "life_mc_s2_emp_pwtr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "life_mc_s2_emp_pwtr_raw_weight",
    "raw_power_weight_attr": "life_mc_s2_emp_pwtr_raw_power_weight",
  },
  {
    "name": "cascade_fc_s2_pctr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_fc_pctr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_fc_pctr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fc_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fc_pctr_raw_power_weight",
  },
  {
    "name": "cascade_fc_s2_plvtr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_fc_plvtr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_fc_plvtr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fc_plvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fc_plvtr_raw_power_weight",
  },
  {
    "name": "cascade_fc_s2_psvtr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_fc_psvtr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_fc_psvtr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fc_psvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fc_psvtr_raw_power_weight",
  },
  {
    "name": "cascade_fc_s2_pvtr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_fc_pvtr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_fc_pvtr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fc_pvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fc_pvtr_raw_power_weight",
  },
  {
    "name": "pdn_rank_score",  #pdn召回rank score队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_pdn_rank_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_pdn_rank_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "comirec_rank_score",  #comirec召回rank score队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_comirec_rank_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_comirec_rank_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "colossus_ann_rank_score",  #colossus ann召回rank score队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_colossus_ann_rank_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_colossus_ann_rank_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_smooth_age_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_smooth_age_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_emp_pop_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_emp_pop_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_htr_cost_score",  #粗排 htr 机会成本
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_phtr_cost_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_phtr_cost_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_interact_fusion_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_interact_fusion_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_interact_fusion_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_watch_time_fusion_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_watch_time_fusion_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_watch_time_fusion_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_psvtr2",
    "reverse_order": True,
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_psvtr2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ctcvr_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_ctcvr_score_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_ctcvr_score_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ctcvr_gmv_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_ctcvr_gmv_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_ctcvr_gmv_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_elive_ctcvr_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_elive_ctcvr_score_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_elive_ctcvr_score_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_elive_ctcvr_gmv_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_elive_ctcvr_gmv_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_elive_ctcvr_gmv_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "produce_cascade_mtctr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_mtctr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_twhtr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_twhtr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_mtcotr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_mtjtr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_mtjtr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtjtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtjtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtjtr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_kym",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_kym_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_kym_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_kym_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_kym_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_csti",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_csti_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_sjctr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_sjctr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_prerank_wtd",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_prerank_wtd_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_prerank_wtd_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_prerank_wtd_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_wtd_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_prerank_wtd_in_s1",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_prerank_wtd_in_s1_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_prerank_wtd_in_s1_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_prerank_wtd_in_s1_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_wtd_in_s1_raw_power_weight",
  },
  {
    "name" : "prerank_wltr_in_s1",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_prerank_wltr_in_s1_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_prerank_wltr_in_s1_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_prerank_wltr_in_s1_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_wltr_in_s1_raw_power_weight",
  },
  {
    "name" : "cascade_pctr_corr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_pctr_corr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_pctr_corr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_pctr_corr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_cascade_pctr_corr_raw_power_weight",
  },
  {
    "name" : "cascade_pctr_fc",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_pctr_fc_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_pctr_fc_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_pctr_fc_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_cascade_pctr_fc_raw_power_weight",
  },
  {
    "name": "cascade_prerank_pctr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_prerank_pctr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pctr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pctr_raw_power_weight",
  },
  {
    "name": "cascade_prerank_pltr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_prerank_pltr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pltr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pltr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_psvtr",
    "reverse_order": True,
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_psvtr_v2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "cascade_pwtd",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_pwtd_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "cascase_life_ctr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_lifetab_pctr_power_weight",
    "weight_attr" : "explore_mc_ensemble_s2_lifetab_pctr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_lifetab_pctr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_lifetab_pctr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_lifetab_pctr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_lifetab_pctr_dynamic_weight",
    "user_xtr" : "realtime_ctr",
    "rank_cliff_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_lifetab_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_lifetab_pctr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_lifetab_pctr_normalize_alpha"
  },
  {
    "name" : "cascade_pxtr_fractile_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pxtr_fractile_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_pxtr_fractile_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_pxtr_fractile_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_pxtr_fractile_raw_power_weight",
  },
  {
    "name" : "cascade_prerank_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_prerank_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_prerank_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_prerank_score_raw_power_weight",
  },
  {
    "name" : "cascade_dstill_pctr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_dstill_pctr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_dstill_pctr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_dstill_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_dstill_pctr_raw_power_weight",
  },
  {
    "name" : "cascade_dstill_pltr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_dstill_pltr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_dstill_pltr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_dstill_pltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_dstill_pltr_raw_power_weight",
  },
  {
    "name" : "cascade_dstill_plvtr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_dstill_plvtr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_dstill_plvtr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_dstill_plvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_dstill_plvtr_raw_power_weight",
  },
  {
    "name" : "cascade_dstill_pwatch_time",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_dstill_pwatch_time_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_dstill_pwatch_time_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_dstill_pwatch_time_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_dstill_pwatch_time_raw_power_weight",
  },
  {
    "name" : "is_same_location",
    "value_type": "int",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_same_location_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_same_location_weight",
    "raw_weight_attr": "explore_mc_ensemble_s2_same_location_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_same_location_raw_power_weight",
  },
  {
    "name" : "fountain_efficiency_vv",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_fountain_efficiency_vv_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_fountain_efficiency_vv_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fountain_efficiency_vv_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fountain_efficiency_vv_raw_power_weight",
  },
  {
    "name": "nonneg_intere_score",
    "weight": 0.5,
    "power_weight_attr": "explore_mc_ensemble_s2_intere_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_intere_score_weight",
    "raw_weight_attr": "explore_mc_ensemble_s2_intere_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_intere_score_raw_power_weight",
  },
  {
    "name": "danlie_depress_score",
    "weight": 0.5,
    "power_weight_attr": "xlife_mc_ensemble_s2_danlie_depress_score_power_weight",
    "weight_attr": "xlife_mc_ensemble_s2_danlie_depress_score_weight",
    "raw_weight_attr": "xlife_mc_ensemble_s2_danlie_depress_score_raw_weight",
    "raw_power_weight_attr": "xlife_mc_ensemble_s2_danlie_depress_score_raw_power_weight",
  },
  {
    "name" : "empirical_svtr",
    "weight" : 0.5,
    "weight_attr" : "explore_prerank_ensemble_empirical_svtr_weight",
    "power_weight_attr" : "explore_prerank_ensemble_empirical_svtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_empirical_svtr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_empirical_svtr_raw_power_weight",
  },
]



final_channel_sort_queues_new = [
  {
    "name" : "cascade_s2_score",
    "weight" : 1.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_s2_ensemble_pctr",
    "weight" : 0.1,
    "power_weight_attr" : "explore_mc_ensemble_s2_pctr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pctr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pctr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pctr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pctr_dynamic_weight",
    "user_xtr" : "realtime_ctr",
    "rank_cliff_attr": "explore_mc_ensemble_pctr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pctr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pctr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pctr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_pctr_normalize_alpha"
  },
  {
    "name" : "mc_s2_ensemble_pltr",
    "weight" : 0.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_pltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pltr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pltr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pltr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pltr_dynamic_weight",
    "user_xtr" : "realtime_ltr",
    "rank_cliff_attr": "explore_mc_ensemble_pltr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pltr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pltr_rank_cliff_min",
    "score_threshold": "user_emp_ltr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pltr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_pltr_normalize_alpha"
  },
  {
    "name" : "mc_s2_ensemble_pwtr",
    "weight" : 0.45,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pwtr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pwtr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pwtr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pwtr_dynamic_weight",
    "user_xtr" : "realtime_wtr",
    "rank_cliff_attr": "explore_mc_ensemble_pwtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pwtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pwtr_rank_cliff_min",
    "score_threshold": "user_emp_wtr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pwtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pwtr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_pwtr_normalize_alpha"
  },
  {
    "name" : "mc_s2_ensemble_pftr",
    "weight" : 0.05,
    "power_weight_attr" : "explore_mc_ensemble_s2_pftr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pftr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pftr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pftr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pftr_dynamic_weight",
    "user_xtr" : "realtime_ftr",
    "rank_cliff_attr": "explore_mc_ensemble_pftr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pftr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pftr_rank_cliff_min",
    "score_threshold": "user_emp_ftr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pftr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pftr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_pftr_normalize_alpha"
  },
  {
    "name" : "mc_s2_ensemble_plvtr",
    "weight" : 0.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_plvtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_plvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_plvtr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_plvtr_normalize_alpha"
  },
  {
    "name" : "mc_s2_ensemble_plvtr2",
    "weight" : 0.12,
    "power_weight_attr" : "explore_mc_ensemble_s2_plvtr2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_plvtr2_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_plvtr2_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_plvtr2_normalize_alpha"
  },
  {
    "name" : "mc_s2_ensemble_psvtr",
    "weight" : -0.1,
    "power_weight_attr" : "explore_mc_ensemble_s2_psvtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_s2_ensemble_ptr",
    "weight": 0.05,
    "power_weight_attr": "explore_mc_ensemble_s2_ptr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_ensemble_pptr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pptr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pptr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pptr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pptr_raw_power_weight",
  },
  {
    "name" : "mc_s2_ensemble_pepstr",
    "weight" : 0.3,
    "power_weight_attr" : "explore_mc_ensemble_s2_pepstr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pepstr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pepstr_raw_power_weight",
  },
  {
    "name" : "mc_s2_ensemble_pcestr",
    "weight" : 0.18,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcestr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pcestr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcestr_raw_power_weight",
  },
  {
    "name" : "mc_s2_ensemble_pcmtr",
    "weight" : 0.18,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcmtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_ensemble_pcmtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pcmtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pcmtr_rank_cliff_min",
    "score_threshold": "user_emp_cmtr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pcmtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcmtr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_pcmtr_normalize_alpha"
  },
  {
    "name" : "mc_s2_ensemble_pptime",
    "weight" : 0.4,
    "power_weight_attr" : "explore_mc_ensemble_s2_pptime_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_s2_ensemble_pwatch_time",
    "weight" : 0.45,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwatch_time_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_ppwatch_time_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_ppwatch_time_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_pwatch_time_normalize_alpha"
  },
  {
    "name": "mc_s2_ensemble_peftr",
    "weight": 0.5,
    "power_weight_attr": "explore_mc_ensemble_s2_eftr_score_power_weight",
    "weight_attr": "mc_eftr_ensemble_sort_weight_s2",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_peftr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_peftr_raw_power_weight",
  },
  {
    "name": "mc_s2_ensemble_pefctr",
    "weight": 0.5,
    "power_weight_attr": "explore_mc_ensemble_s2_efctr_score_power_weight",
    "weight_attr": "mc_efctr_ensemble_sort_weight_s2",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pefctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pefctr_raw_power_weight",
  },
  {
    "name" : "mc_s2_ensemble_pcltr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "variant_weight" : "explore_mc_ensemble_s2_pcltr_variant_weight",
    "avg_xtr" : "avg_cltr",
    "min_ratio" : "explore_mc_ensemble_pcltr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pcltr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pcltr_dynamic_weight",
    "user_xtr": "realtime_cltr",
    "rank_cliff_attr": "explore_mc_ensemble_pcltr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pcltr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pcltr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pcltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcltr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_pcltr_normalize_alpha"
  },
  {
    "name": "mc_ensemble_opportunity_cost_score",  #粗排机会成本队列
    "weight": 0.8,
    "power_weight_attr": "explore_mc_ensemble_s2_opportunity_cost_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_opportunity_cost_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_s2_ensemble_pwtd",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwtd_power_weight",
    "weight_attr" : "mc_wtd_ensemble_sort_weight_s2",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_pwtd_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_pwtd_raw_power_weight",
    "rank_cliff_attr": "explore_mc_ensemble_pwtd_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pwtd_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pwtd_rank_cliff_min"
  },
  {
    "name" : "mc_s2_ensemble_pcptr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcptr_power_weight",
    "weight_attr" : "mc_pcptr_ensemble_sort_weight_s2",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_pcptr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_pcptr_raw_power_weight",
  },
  {
    "name": "mc_s2_ensemble_pfptr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_pfptr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_pfptr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_pfptr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_pfptr_raw_power_weight",
  },
  {
    "name": "mc_s2_ensemble_ordinal_wtd",
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_ordinal_wtd_weight",
    "weight_attr": "explore_mc_ensemble_s2_ordinal_wtd_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ada_xtr_score",  #粗排播放完成度队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_mc_ada_xtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_mc_ada_xtr_score_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "diversity_fr",  #粗排播放完成度队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_diversity_fr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_diversity_fr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "use_new_pow_func": "explore_diversity_fr_use_new_pow_func",
    "new_pow_func_coeff": "explore_diversity_fr_new_pow_func_coeff",
    "new_pos_func_bias": "explore_diversity_fr_new_pos_func_bias"
  },
  {
    "name": "hate_fr",  #粗排topkmgs hate 队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_hate_fr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_hate_fr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "use_new_pow_func": "explore_hate_fr_use_new_pow_func",
    "new_pow_func_coeff": "explore_hate_fr_new_pow_func_coeff",
    "new_pos_func_bias": "explore_hate_fr_new_pos_func_bias"
  },
  {
    "name": "mc_s2_ensemble_prerank_er",  #粗排 LTR
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_prerank_er_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_prerank_er_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "cascade_phtr",  #粗排 htr
    "weight": 0.0,
    "reverse_order": True,
    "power_weight_attr": "explore_mc_ensemble_s2_phtr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_phtr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_s2_ensemble_phtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_s2_ensemble_phtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_s2_ensemble_phtr_rank_cliff_min",
    "rank_height_attr": "explore_mc_s2_ensemble_phtr_rank_height",
  },
  {
    "name": "mc_htr_cost_score",  #粗排 htr 机会成本
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_phtr_cost_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_phtr_cost_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_interact_fusion_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_interact_fusion_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_interact_fusion_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_watch_time_fusion_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_watch_time_fusion_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_watch_time_fusion_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ctcvr_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_ctcvr_score_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_ctcvr_score_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ctcvr_gmv_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_ctcvr_gmv_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_ctcvr_gmv_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_elive_ctcvr_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_elive_ctcvr_score_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_elive_ctcvr_score_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_elive_ctcvr_gmv_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_elive_ctcvr_gmv_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_elive_ctcvr_gmv_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "produce_cascade_mtctr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_mtctr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_twhtr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_twhtr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_mtcotr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_mtjtr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_mtjtr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtjtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtjtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtjtr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_kym",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_kym_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_kym_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_kym_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_kym_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_csti",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_csti_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_sjctr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_sjctr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_raw_power_weight",
  },
  {
    "name" : "cascase_life_ctr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_lifetab_pctr_power_weight",
    "weight_attr" : "explore_mc_ensemble_s2_lifetab_pctr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_lifetab_pctr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_lifetab_pctr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_lifetab_pctr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_lifetab_pctr_dynamic_weight",
    "user_xtr" : "realtime_ctr",
    "rank_cliff_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_lifetab_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_lifetab_pctr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_lifetab_pctr_normalize_alpha"
  },
  {
    "name" : "is_same_location",
    "value_type": "int",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_same_location_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_same_location_weight",
    "raw_weight_attr": "explore_mc_ensemble_s2_same_location_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_same_location_raw_power_weight",
  },
  {
    "name": "nonneg_intere_score",
    "weight": 0.5,
    "power_weight_attr": "explore_mc_ensemble_s2_intere_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_intere_score_weight",
    "raw_weight_attr": "explore_mc_ensemble_s2_intere_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_intere_score_raw_power_weight",
  },
  {
    "name": "danlie_depress_score",
    "weight": 0.5,
    "power_weight_attr": "xlife_mc_ensemble_s2_danlie_depress_score_power_weight",
    "weight_attr": "xlife_mc_ensemble_s2_danlie_depress_score_weight",
    "raw_weight_attr": "xlife_mc_ensemble_s2_danlie_depress_score_raw_weight",
    "raw_power_weight_attr": "xlife_mc_ensemble_s2_danlie_depress_score_raw_power_weight",
  },
]


