ada_decay_rate: 0.99999
ada_epsilon: 1e-8
avg_decay_rate: 0.999993
back_propagate_input: true
embedding:
  create_threshold: 0
  initial_g2sum: 3
  initial_range: 1e-4
  learning_rate: 0.05
  slots_config:
  - compress_group: USER
    dim: 32
    dtype: float32
    expand: 1
    input_name: user_id
    is_common: true
    slots: '16'
  - compress_group: USER
    dim: 32
    dtype: float32
    expand: 1
    input_name: user_device_id
    is_common: true
    slots: '21'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_age_segment
    is_common: true
    slots: '18'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_gender
    is_common: true
    slots: '22'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_city_id
    is_common: true
    slots: '19'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_client_id
    is_common: true
    slots: '20'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_visit_mod
    is_common: true
    slots: '26'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_level
    is_common: true
    slots: '27'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_emp_ctr
    is_common: true
    slots: '28'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_emp_ltr
    is_common: true
    slots: '30'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_emp_wtr
    is_common: true
    slots: '29'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_emp_lvtr
    is_common: true
    slots: '31'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_request_province_id
    is_common: true
    slots: '24'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_request_city_id
    is_common: true
    slots: '25'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_request_poi_type
    is_common: true
    slots: '23'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: user_region_type
    is_common: true
    slots: '32'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_realtime_click_list
    is_common: true
    slots: '61'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_realtime_like_list
    is_common: true
    slots: '64'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_realtime_follow_list
    is_common: true
    slots: '62'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_realtime_forward_list
    is_common: true
    slots: '63'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_fountain_profile_like_pid_list
    is_common: true
    slots: '40'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_fountain_profile_like_aid_list
    is_common: true
    slots: '39'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_fountain_profile_effective_view_pid_list
    is_common: true
    slots: '59'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_fountain_profile_effective_view_aid_list
    is_common: true
    slots: '60'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_fountain_profile_long_view_pid_list
    is_common: true
    slots: '55'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 50
    input_name: user_fountain_profile_long_view_aid_list
    is_common: true
    slots: '56'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_id
    slots: '1016'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_id_v2
    slots: '4000'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_id
    slots: '1026'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_gender
    slots: '1024'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_upload_type
    slots: '1017'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_hetu_tag_level1_list
    slots: '1027'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_hetu_tag_level2_list
    slots: '1028'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_hetu_tag_level5_list
    slots: '1031'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: photo_duration_ms
    slots: '1023'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pctr
    slots: '3017'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pltr
    slots: '3019'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pwtr
    slots: '3025'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pftr
    slots: '3018'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_plvtr
    slots: '3020'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pvtr
    slots: '3023'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pptr
    slots: '3021'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pcmtr
    slots: '3016'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pepstr
    slots: '3124'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pcpr
    slots: '3122'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pcltr
    slots: '3123'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_psvr
    slots: '3129'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_pwtd
    slots: '3024'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_fullrank_ltr_score
    slots: '3125'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_fullrank_act_wtd
    slots: '3126'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_fullrank_ltr_v4_fountain_next
    slots: '3127'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_fountain_related_score_v2
    slots: '3128'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_cascade_pctr
    slots: '3029'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_cascade_pltr
    slots: '3030'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_cascade_pwtr
    slots: '3033'
  - dim: 16
    dtype: float32
    expand: 1
    input_name: context_cascade_plvtr
    slots: '3031'
  - compress_group: USER
    dim: 32
    dtype: float32
    expand: 1
    input_name: context_source_pid
    is_common: true
    slots: '3026'
  - compress_group: USER
    dim: 32
    dtype: float32
    expand: 1
    input_name: context_source_aid
    is_common: true
    slots: '3040'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: context_source_hetu_tag_level1_top1
    is_common: true
    slots: '3042'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: context_source_hetu_tag_level2_top1
    is_common: true
    slots: '3043'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: context_source_tag
    is_common: true
    slots: '3044'
  - compress_group: USER
    dim: 16
    dtype: float32
    expand: 1
    input_name: context_source_duration_ms
    is_common: true
    slots: '3041'
  version_aware: true
  weight_bounds:
  - -10
  - 10
extra_params: []
extra_preds: rerank_gen_score_0
global_init_range: 0.2
graph: ../infer/graph.pb
graph_output_labels:
- Identity_9:0
- Identity_29:0
- Identity_4:0
- Identity_24:0
- Identity_5:0
- Identity_6:0
- Identity_17:0
- Select_4:0
- Identity_11:0
- Identity_14:0
- Identity_2:0
- Select_11:0
- Identity_18:0
- Identity_25:0
- Identity_8:0
- Identity:0
- Identity_21:0
- Identity_7:0
- Identity_26:0
- Identity_13:0
- Identity_10:0
- Identity_12:0
- Identity_20:0
- Identity_15:0
- Identity_23:0
- Identity_27:0
- Identity_3:0
- Identity_22:0
- Identity_1:0
- Identity_16:0
graph_q_valid:
  all_evtr: Select_5:0
  all_lvtr: Select_5:0
  all_svr: Select_5:0
  cmef: Maximum_1:0
  cmtr: Select_15:0
  coltr: Select_17:0
  dtr: Select_16:0
  epst: Maximum_1:0
  ftr: Select_13:0
  ftr_os: Select_14:0
  hot_lvtr: Minimum:0
  htr: Select_18:0
  live: Identity_19:0
  ltr: Maximum_1:0
  mcp_match: Select_1:0
  ptr: Maximum_1:0
  scale_vtr: Maximum:0
  setr: Maximum:0
  setr2: Identity_28:0
  thanos_cmef: Select_1:0
  thanos_dfvtr: mul_2:0
  thanos_etcm: Select_1:0
  thanos_evtr: mul:0
  thanos_ftr: Select_1:0
  thanos_ltr: Select_1:0
  thanos_lvtr: mul_1:0
  thanos_svr: Select_1:0
  thanos_wtr: Select_1:0
  vtr: Identity_30:0
  wtr: Select_12:0
graph_targets:
- opt
graph_tensor_mapping:
  rerank_gen_score_0: Reshape_11:0
hyperparameter_kconf: null
input_type: 3
learning_rate: 5.0e-06
mom_decay_rate: 0.999
output_hidden_units: update_input continue_normlized_input slide_embedding slide_wide
  watch_time_wide position_weight_input
param:
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/share_bottom/dense/kernel
  rown: 752
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/share_bottom/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 512
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/share_bottom/dense_1/kernel
  rown: 1056
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/share_bottom/dense_1/bias
  rank: 1
  rown: 512
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/share_bottom/dense_2/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/share_bottom/dense_2/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/share_bottom/dense_3/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/share_bottom/dense_3/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 512
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/share_bottom/mmoe_expert_unit/dense/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/share_bottom/mmoe_expert_unit/dense/bias
  rank: 1
  rown: 512
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_0/encoder_mha/dense/kernel
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_0/encoder_mha/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_0/encoder_mha/dense_2/kernel
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_0/encoder_mha/dense_3/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_0/encoder_mha/dense_3/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: act_ltr_model/prm_enc_layer_0/encoder_ln1_layer_norm/gamma
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_0/encoder_ln1_layer_norm/beta
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_0/encoder_ffn/dense/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_0/encoder_ffn/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_0/encoder_ffn/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_0/encoder_ffn/dense_1/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: act_ltr_model/prm_enc_layer_0/encoder_ln2_layer_norm/gamma
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_0/encoder_ln2_layer_norm/beta
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_1/encoder_mha/dense/kernel
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_1/encoder_mha/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_1/encoder_mha/dense_2/kernel
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_1/encoder_mha/dense_3/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_1/encoder_mha/dense_3/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: act_ltr_model/prm_enc_layer_1/encoder_ln1_layer_norm/gamma
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_1/encoder_ln1_layer_norm/beta
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_1/encoder_ffn/dense/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_1/encoder_ffn/dense/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/prm_enc_layer_1/encoder_ffn/dense_1/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_1/encoder_ffn/dense_1/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: act_ltr_model/prm_enc_layer_1/encoder_ln2_layer_norm/gamma
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/prm_enc_layer_1/encoder_ln2_layer_norm/beta
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/ctr_head/dense/kernel
  rown: 512
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/ctr_head/dense/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 128
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/ctr_head/dense_1/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/ctr_head/dense_1/bias
  rank: 1
  rown: 128
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/ctr_head/dense_2/kernel
  rown: 128
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/ctr_head/dense_2/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: act_ltr_model/ctr_head/dense_3/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: act_ltr_model/ctr_head/dense_3/bias
  rank: 1
  rown: 1
  scale_by_rown: true
q_names: rerank_gen_score_0
step_placeholder: step:0
summary:
- len: 1912
  name: base_summary
- len: 2072
  name: stub_summary
summary_decay_rate: 0.999999
summary_init_n: 1e4
summary_init_squared_sum: 1e4
summary_squared_sum_epsilon: 1e-4
test_layers_at_joining: join join_forward update update_forward
test_layers_at_updating: update update_forward
test_mode: false
train_layers_at_joining: join
train_layers_at_updating: update
vec_input:
- common: false
  dim: 1
  name: duration_ms
