from cascading import CommonModule

class CascadingFcLtrPredictModule(CommonModule):
  def __init__(self, name: str) -> None:
    super().__init__(name)

  def user_feature(self):
    features = [
      "uId",
      "dId",
      "uHourOfDay",
      "uDayOfWeek",
      "uExpCtr",
      "uExpLtr",
      "uExpWtr",
      "uExpFtr",
      "uExpLvtr",
      "uExpSvtr",
      "uExpHtr",
      "uExpClickCount",
      "uExpLikeCount",
      "uExpFollowCount",
      "uExpForwardCount",
      "uExpHateCount",
      "uFansCount",
      "uClickPidsHot",
      "uClickAidsHot",
      "uLikePidsHot",
      "uLikeAidsHot",
      "uFollowPidsHot",
      "uFollowAidsHot",
      "uCommentPidsHot",
      "uCommentAidsHot",
      "uCollectPidsHot",
      "uCollectAidsHot",
      "uForwardPidsHot",
      "uForwardAidsHot",
      "uPlayViewPidsGlobal",
      "uPlayViewAidsGlobal",
      "uPlayViewDurationGlobal",
      "uPlayViewPlaytimeGlobal",
      "uPlayViewHetu2Global",
      "uPlayViewChannelGlobal",
      "uUploadCount",
      "uCityLevelNew",
      "uCityId",
      "uProvinceId",
      "uGender",
      "uTrueYear",
      "uBasicAge",
      "uNetwork",
      "uIsLowActiveUser",
    ]

    return features

  def photo_features(self):
    features = [
      {"name": "photo_id", "as": "pId"},
      {"name": "author__id", "as": "aId"},
      "upload_time",
      {"name": "duration_ms", "as": "pDurationMs"},
      {"name": "upload_type", "as": "pUploadType"},
      {"name": "location__poi", "as": "pPhotoPoi"},
      {"name": "location__city_id", "as": "pCityId"},
      {"name": "location__province_id", "as": "pProvinceId"},
      {"name": "empirical_ctr", "as": "pEmpCtrHot"},
      {"name": "empirical_ltr", "as": "pEmpLtrHot"},
      {"name": "empirical_wtr", "as": "pEmpWtrHot"},
      {"name": "empirical_ftr", "as": "pEmpFtrHot"},
      {"name": "empirical_cmtr", "as": "pEmpCmtrHot"},
      {"name": "empirical_htr", "as": "pEmpHtrHot"},
      {"name": "explore_stat__real_show_count", "as": "pEmpRealShowCountHot"},
      {"name": "explore_stat__click_count", "as": "pEmpClickCountHot"},
      {"name": "empirical_watch_time", "as": "pEmpWatchTimeHot"},

      {"name": "hetu_tag_level_info__hetu_cluster_id", "as": "pHetuClusterId"},
      {"name": "user_hash_tag_id", "as": "pHashTagIdList"},
      {"name": "ocr_cover_text_word_count", "as": "pOcrCoverTWCount"},
      {"name": "content_safety_level_with_namespace__level_hot_online", "as": "pLevelHotOnline"},
      {"name": "audit_hot_high_tag_level", "as": "pAuditHotHighTagLevel"},
      {"name": "hetu_tag_level_info__hetu_face_id", "as": "pHetuTagFaceId"},
      {"name": "hetu_tag_level_info__hetu_level_one", "as": "pHetuTagLevel1"},
      {"name": "hetu_tag_level_info__hetu_level_two", "as": "pHetuTagLevel2"},
      {"name": "hetu_tag_level_info__hetu_level_three", "as": "pHetuTagLevel3"},
      {"name": "hetu_tag_level_info__hetu_level_five", "as": "pHetuTagLevel5"},
      {"name": "hetu_tag_level_info__hetu_tag", "as": "pHetuTagLevelTag"},
      {"name": "author__hetu_author_tag__hetu_level_one", "as": "aHetuTagLevel1"},
      {"name": "author__hetu_author_tag__hetu_level_two", "as": "aHetuTagLevel2"},
      {"name": "author__hetu_author_tag__hetu_level_three", "as": "aHetuTagLevel3"},

      {"name": "cascade_pctr", "as": "pMcPctr"},
      {"name": "cascade_pltr", "as": "pMcPltr"},
      {"name": "cascade_pwtr", "as": "pMcPwtr"},
      {"name": "cascade_plvtr", "as": "pMcPlvtr"},
      {"name": "cascade_psvtr", "as": "pMcPsvtr"},
      {"name": "cascade_pftr", "as": "pMcPftr"},
      {"name": "cascade_pcmtr", "as": "pMcPcmtr"},
      {"name": "cascade_plvtr2", "as": "pMcPlvtr2"},
      {"name": "cascade_pepstr", "as": "pMcPepstr"},
      {"name": "cascade_pcltr", "as": "pMcPcltr"},
      {"name": "cascade_phtr", "as": "pMcPhtr"},
      {"name": "cascade_pwatch_time", "as": "pMcPwatchTime"},
    ]
    return features
          
  def process(self) -> None:
    self.flow \
      .if_("enable_explore_mc_fc_ltr_predict == 1") \
        .explore_common_user_feature_enricher(
          user_info_attr = "user_info_ptr",
          user_uid_attr = "uId",
          user_did_attr = "dId",
          context_hour_of_day_attr = "uHourOfDay",
          context_day_of_week_attr = "uDayOfWeek",
          user_exp_ctr_attr = "uExpCtr",
          user_exp_ltr_attr = "uExpLtr",
          user_exp_wtr_attr = "uExpWtr",
          user_exp_ftr_attr = "uExpFtr",
          user_exp_lvtr_attr = "uExpLvtr",
          user_exp_svtr_attr = "uExpSvtr",
          user_exp_htr_attr = "uExpHtr",
          user_exp_click_count_attr = "uExpClickCount",
          user_exp_like_count_attr = "uExpLikeCount",
          user_exp_follow_count_attr = "uExpFollowCount",
          user_exp_forward_count_attr = "uExpForwardCount",
          user_exp_hate_count_attr = "uExpHateCount",
          user_fans_cnt_attr = "uFansCount",
          hot_click_pids_attr = "uClickPidsHot",
          hot_click_aids_attr = "uClickAidsHot",
          hot_like_pids_attr = "uLikePidsHot",
          hot_like_aids_attr = "uLikeAidsHot",
          hot_follow_pids_attr = "uFollowPidsHot",
          hot_follow_aids_attr = "uFollowAidsHot",
          hot_comment_pids_attr = "uCommentPidsHot",
          hot_comment_aids_attr = "uCommentAidsHot",
          hot_forward_pids_attr = "uForwardPidsHot",
          hot_forward_aids_attr = "uForwardAidsHot",
          hot_collect_pids_attr = "uCollectPidsHot",
          hot_collect_aids_attr = "uCollectAidsHot",
          global_pv_pids_attr = "uPlayViewPidsGlobal",
          global_pv_aids_attr = "uPlayViewAidsGlobal",
          global_pv_duration_attr = "uPlayViewDurationGlobal",
          global_pv_time_attr = "uPlayViewPlaytimeGlobal",
          global_pv_hetu2_attr = "uPlayViewHetu2Global",
          global_pv_channel_attr = "uPlayViewChannelGlobal",
          user_upload_cnt_attr = "uUploadCount",
          user_city_level_attr = "uCityLevelNew",
          user_city_attr = "uCityId",
          user_province_attr = "uProvinceId",
          user_gender_attr = "uGender",
          user_true_year_attr = "uTrueYear",
          user_basic_age_attr = "uBasicAge",
          user_visit_net_attr = "uNetwork",
          user_low_active_attr = "uIsLowActiveUser",
        ) \
        .delegate_enrich(
          kess_service = "{{mc_fc_ltr_service}}",
          recv_item_attrs = [
            {"name": "ctr_fc", "as": "cascade_pctr_fc"}
          ],
          timeout_ms = 100,
          send_item_attrs = self.photo_features(),
          send_common_attrs = self.user_feature(),
          request_type = "{{mc_fc_ltr_request_type}}",
          partition_size = "{{mc_fc_ltr_partition_size}}"
        ) \
      .end_() \
