#!/usr/bin/env python3
# coding=utf-8

distill_user_features = [
  "featureUId",
  "featureDeviceId",
  "featureDeviceModel",
  "featureGender",
  "featureAge",
  "featureAgeSegment",
  "featureProvinceId",
  "featureCityId",
  "featureClientId",
  "featureVisitMod",
  "featureVisitNet",
  "featureUserLevel",
  "featureRiskLevel",
  "featureRegTime",
  "featureFollowCount",
  "featureFansCount",
  "featureUploadCount",
  "featureUserCtr",
  "featureUserLtr",
  "featureUserWtr",
  "featureUserFtr",
  "featureUserLvtr",
  "featureUserSvtr",
  "featureUserAvgWatchTime",
  "featureUserRequestProvinceId",
  "featureUserRequestCityId",
  "featureUserRequestPoiType",
  "featureUserRegion",
  "featureUserPhonePriceLevel",
  "featureUserAppNewCat1",
  "featureUserAppNewCat2",
  "featureUserAppNewCat3",
  "featureUserAppNormNames",
  "featureUserAppNameList",
  "featureRealtimeClickList",
  "featureRealtimeLikeList",
  "featureRealtimeFollowList",
  "featureRealtimeForwardList",
  "featureAppSignList",
  "featureLongTermInterestPhotoDnnClusterId",
  "featureTopDislikeTopic",
  "featureTopRateTopic",
  "featureUserProfileV1ClickPidList",
  "featureUserProfileV1ClickAidList",
  "featureUserProfileV1LikePidList",
  "featureUserProfileV1LikeAidList",
  "featureUserProfileV1CommentPidList",
  "featureUserProfileV1CommentAidList",
  "featureUserProfileV1DownloadPidList",
  "featureUserProfileV1DownloadAidList",
  "featureUserProfileV1FollowPidList",
  "featureUserProfileV1FollowAidList",
  "featureUserProfileV1ForwardPidList",
  "featureUserProfileV1ForwardAidList",
  "featureUserProfileV1SearchClickPidList",
  "featureUserProfileV1SearchClickAidList",
  "featureUserProfileV1ProfileEnterPidList",
  "featureUserProfileV1ProfileEnterAidList",
  "featureSourcePId",
  "sourcePidAuthorId",
  "sourcePidFirstLevelCategory",
  "sourcePidSecondLevelCategory",
  "sourcePidThirdLevelCategory",
  "sourcePidFourthLevelCategory",
  "sourcePidHetuLevelOneList",
  "sourcePidHetuLevelTwoList",
  "sourcePidHetuLevelThreeList",
  "sourcePidHetuLevelFourList",
  "sourcePidHetuLevelFiveList",
  "sourcePidHetuTagList",
  "sourcePidHetuFaceIdList",
  "sourcePidMmuImgClusterV3",
  "sourcePidDnnCluster",
  "sourcePidTagId",
  "sourcePidDuration",
  "featureActiveDays",
  "featureUserRequestPoi",
  "featureLongtermTagList",
  "featureUserRequestTown",
  "featureUserRequestCityLevel",
  "featureUserRequestCommunityType",
  "featureUserProfileV1Play11SPidList",
  "featureUserProfileV1Play11SAidList",
  "featureUserProfileV1Play18SPidList",
  "featureUserProfileV1Play18SAidList",
  'featureFountainProfileShortViewPidList',
  'featureFountainProfileCommentAidList',
  'featureFountainProfileClickAidList',
  'featureFountainProfileClickPidList',
  'featureFountainProfileCommentPidList',
  'featureFountainProfileEffViewAidList',
  'featureFountainProfileFollowPidList',
  'featureFountainProfileLongViewPidList',
  'featureFountainProfileEffViewPidList',
  'featureFountainProfileShortViewAidList',
  'featureFountainProfileLikeAidList',
  'featureFountainProfileFollowAidList',
  'featureFountainProfileLongViewAidList',
  'featureFountainProfileLikePidList'
]

cascade_ltr_common_feature = [
  "featureUId",
  "featureDeviceId",
  "featureDeviceModel",
  "featureGender",
  "featureAge",
  "featureAgeSegment",
  "featureProvinceId",
  "featureCityId",
  "featureClientId",
  "featureVisitMod",
  "featureVisitNet",
  "featureUserLevel",
  "featureRiskLevel",
  "featureRegTime",
  "featureFollowCount",
  "featureFansCount",
  "featureUploadCount",
  "featureUserCtr",
  "featureUserLtr",
  "featureUserWtr",
  "featureUserFtr",
  "featureUserLvtr",
  "featureUserSvtr",
  "featureUserAvgWatchTime",
  {"name": "user_emp_ltr", "as": "featureColossusEmpLtr"},
  {"name": "user_emp_wtr", "as": "featureColossusEmpWtr"},
  {"name": "user_emp_ftr", "as": "featureColossusEmpFtr"},
  {"name": "user_emp_htr", "as": "featureColossusEmpHtr"},
  {"name": "user_emp_cmtr", "as": "featureColossusEmpCmtr"},
  {"name": "user_emp_eptr", "as": "featureColossusEmpPtr"},
  {"name": "user_emp_svtr", "as": "featureColossusEmpSvtr"},
  {"name": "user_emp_evtr", "as": "featureColossusEmpEvtr"},
  {"name": "user_emp_lvtr", "as": "featureColossusEmpLvtr"},
  {"name": "user_emp_watch_time", "as": "featureColossusAvgWatchTime"},
  {"name": "user_emp_fintr", "as": "featureColossusEmpFintr"},
  {"name": "user_emp_finish_rate", "as": "featureColossusAvgFinishRate"},

  "featureFountainIsFirstPage",
  {"name": "page", "as": "featureFountainPageNew"},
  "featureUserRequestCommunityType",

  "featureUserRequestProvinceId",
  "featureUserRequestCityId",
  "featureUserRequestCityLevel",
  "featureUserRequestPoiType",
  "featureUserRegion",
  "featureUserPhonePriceLevel",
  "featureUserAppNewCat1",
  "featureUserAppNewCat2",
  "featureUserAppNewCat3",
  "featureUserAppNormNames",
  "featureUserAppNameList",
  "featureRealtimeClickList",
  "featureRealtimeLikeList",
  "featureRealtimeFollowList",
  "featureRealtimeForwardList",
  "featureAppSignList",
  "featureLongTermInterestPhotoDnnClusterId",
  "featureTopDislikeTopic",
  "featureTopRateTopic",
  "featureActiveDays",
  "featureUserClickCount",
  "featureUserLikeCount",
  "featureUserFollowCount",
  "featureUserLongViewCount",
  "featureUserProfileV1ClickPidList",
  "featureUserProfileV1ClickAidList",
  "featureUserProfileV1LikePidList",
  "featureUserProfileV1LikeAidList",
  "featureUserProfileV1CommentPidList",
  "featureUserProfileV1CommentAidList",
  "featureUserProfileV1DownloadPidList",
  "featureUserProfileV1DownloadAidList",
  "featureUserProfileV1FollowPidList",
  "featureUserProfileV1FollowAidList",
  "featureUserProfileV1ForwardPidList",
  "featureUserProfileV1ForwardAidList",
  "featureUserProfileV1SearchClickPidList",
  "featureUserProfileV1SearchClickAidList",
  "featureUserProfileV1ProfileEnterPidList",
  "featureUserProfileV1ProfileEnterAidList",
  "featureUserProfileV1Play7SPidList",
  "featureUserProfileV1Play18SPidList",
  "featureUserProfileV1Play7SAidList",
  "featureUserProfileV1Play18SAidList",
  "featureSourcePId",
  "sourcePidAuthorId",
  "sourcePidFirstLevelCategory",
  "sourcePidSecondLevelCategory",
  "sourcePidThirdLevelCategory",
  "sourcePidFourthLevelCategory",
  "sourcePidHetuLevelOneList",
  "sourcePidHetuLevelTwoList",
  "sourcePidHetuLevelThreeList",
  "sourcePidHetuLevelFourList",
  "sourcePidHetuLevelFiveList",
  "sourcePidHetu0",
  "sourcePidHetuLevelTwo0",
  "sourcePidHetuTagList",
  "sourcePidHetuFaceIdList",
  "sourcePidMmuImgClusterV3",
  "sourcePidDnnCluster",
  "sourcePidTagId",
  "sourcePidDuration",
  "featureUserProfileV1DupClickPidList",
  "featureUserProfileV1DupClickAidList",
  "featureUserProfileV1Play3SPidList",
  "featureUserProfileV1Play11SPidList",
  "featureUserProfileV1Play3SAidList",
  "featureUserProfileV1Play11SAidList",
  "featureFountainProfileClickPidList",
  "featureFountainProfileClickAidList",
  "featureFountainProfileLikeAidLis",
  "featureFountainProfileLikePidLis",
  "featureFountainProfileCommentPidList",
  "featureFountainProfileCommentAidList",
  "featureFountainProfileFollowAidList",
  "featureFountainProfileFollowPidList",
  "featureFountainProfileShortViewAidList",
  "featureFountainProfileShortViewPidList",
  "featureFountainProfileEffViewAidList",
  "featureFountainProfileEffViewPidList",
  "featureFountainProfileLongViewPidList",
  "featureFountainProfileLongViewAidList",
  "featureFountainProfileLikeAidList",
  "featureFountainProfileLikePidList",
  "featureFountainPage",
  "featureRecentRealshowPids",
  "featureRecentRealshowAids",
  "featureRecentRealshowTags",
  "featureRecentRealshowPlays",
  "featureRecentRealshowTimestamps",
  "featureFountainRecentRealshowPids",
  "featureFountainRecentRealshowAids",
  "featureFountainRecentRealshowTags",
  "featureFountainRecentRealshowPlays",
  "featureFountainRecentRealshowTimestamps",
  "featureFountainRecentViewPids",
  "featureFountainRecentViewAids",
  "featureFountainRecentViewTags",
  "featureFountainRecentViewPlays",
  "featureFountainRecentViewDurations",
  "featureFountainRecentViewTimestamps",
  "hetuLevelOneLongTermId",
  "hetuLevelTwoLongTermId",
  "hetuLevelThreeLongTermId",
  "featureUserProfileV1LikeHetuOneList",
  "featureUserProfileV1CommentHetuOneList",
  "featureUserProfileV1FollowHetuOneList",
  "featureUserProfileV1ForwardHetuOneList",
  "featureUserProfileV1ProfileEnterHetuOneList",
  "featureUserProfileV1DupClickHetuOneList",
  "featureUserProfileV1Play7SHetuOneList",
  "featureUserProfileV1Play18SHetuOneList",
  "featureFountainProfileClickDnnClusterIds",
  "featureFountainProfileClickImgV3List",
]

cascade_fc_feature = [
    "ExtractSignUserId",
    "ExtractEmbeddingAfterClickUid",
    "ExtractSignUserLike",
    "ExtractSignUserLike2",
    "ExtractSignUserClick",
    "ExtractSignUserClick2",
    "ExtractEmbeddingUserForward",
    "ExtractEmbeddingUserForward3",
    "ExtractSignUserContext",
    "ExtractSignUserContext2",
    "ExtractSignUserApplistTotal",
    "ExtractSignUserApplistTotal2",
    "ExtractSignUserIp",
    "ExtractSignUserIp2",
    "ExtractSignUserMod",
    "ExtractSignUserMod2",
    "ExtractSignUserProvCity",
    "ExtractSignUserProvCity2",
    "ExtractSignUserYear",
    "ExtractSignUserYear2",
    "ExtractSignUserAllGender",
    "ExtractSignUserAllGender2",
    "ExtractSignSlideUserId",
    "ExtractSignUserDeviceId",
    "ExtractSignUserDeviceId2",
    "ExtractSignSlideUserIdV2",
    "ExtractSignUserHhEffectiveView",
    "ExtractSignUserHhLongView",
    "ExtractSignUserIdV2",
    "ExtractSignUserIdV3",
    "ExtractSignUserDeviceIdCross1",
    "ExtractSignUserDeviceIdCross2",
    "ExtractSignThanosUserPosNegFeedbackCount",
    "ExtractSignThanosUserPosNegFeedbackCount_720",
    "ExtractSignRecentRealshowPids",
    "ExtractSignRecentRealshowAids",
    "ExtractSignRecentRealshowTags",
    "ExtractSignRecentRealshowTimestamps",
    "ExtractSignRecentRealshowPlay",
    "ExtractSignUserDeviceIdMcMMOE_821",
    "ExtractSignUserDeviceIdMcMMOE_822",
    "ExtractSignUserDeviceIdMcMMOE_823",
    "ExtractSignUserDeviceIdMcMMOE_824",
    "ExtractSignUserDeviceIdMcMMOE_825",
    "ExtractSignUserDeviceIdMcMMOE_826",
    "ExtractSignUserDeviceIdMcMMOE_827",
    "ExtractSignUserDeviceIdMcMMOE_828",
    "ExtractSignUserDeviceIdMcMMOE_829",
    "ExtractSignUserFountainClick",
    "ExtractSignUserFountainEvtr",
    "ExtractSignUserFountainLike",
    "ExtractSignUserFountainLvtr",
    "ExtractSignUserComboId_1130"
]

cascade_fc_sim3_feature = cascade_fc_feature + [
    "ExtractSignUserComboId_1131",
    "ExtractSignUserComboId_1132",
    "ExtractSignUserComboId_1133",
    "ExtractEmbeddingNonclickRealshow3",
    "ExtractSignUserFollowClick"
]

cascade_slide_features = [
    "featureUId",
    "featureDeviceId",
    "featureGender",
    "featureAgeSegment",
    "featureCityId",
    "featureClientId",
    "featureVisitMod",
    "featureVisitNet",
    "featureUserLevel",
    "featureActiveDays",
    "featureRegTime",
    "featureFollowCount",
    "featureFansCount",
    "featureUploadCount",
    "featureUserClickCount",
    "featureUserLikeCount",
    "featureUserLongViewCount",

    "featureUserCtr",
    "featureUserLtr",
    "featureUserWtr",
    "featureUserFtr",
    "featureUserLvtr",
    "featureUserSvtr",
    "featureUserAvgWatchTime",

    {"name": "user_emp_ltr", "as": "featureColossusEmpLtr"},
    {"name": "user_emp_wtr", "as": "featureColossusEmpWtr"},
    {"name": "user_emp_ftr", "as": "featureColossusEmpFtr"},
    {"name": "user_emp_htr", "as": "featureColossusEmpHtr"},
    {"name": "user_emp_cmtr", "as": "featureColossusEmpCmtr"},
    {"name": "user_emp_eptr", "as": "featureColossusEmpPtr"},
    {"name": "user_emp_svtr", "as": "featureColossusEmpSvtr"},
    {"name": "user_emp_evtr", "as": "featureColossusEmpEvtr"},
    {"name": "user_emp_lvtr", "as": "featureColossusEmpLvtr"},
    {"name": "user_emp_fintr", "as": "featureColossusEmpFintr"},
    {"name": "user_emp_watch_time", "as": "featureColossusAvgWatchTime"},
    {"name": "user_emp_finish_rate", "as": "featureColossusAvgFinishRate"},

    "featureUserRequestProvinceId",
    "featureUserRequestCityId",
    "featureUserRequestPoiType",
    "featureUserRequestCityLevel",
    "featureUserRequestCommunityType",
    "featureUserRegion",
    "featureUserPhonePriceLevel",
    "featureUserAppNewCat1",
    "featureUserAppNewCat2",
    "featureUserAppNormNames",

    "featureRealtimeClickList",
    "featureRealtimeLikeList",
    "featureRealtimeFollowList",
    "featureRealtimeForwardList",
    "featureAppSignList",
    "featureLongtermTagList",
    "featureLongTermInterestPhotoDnnClusterId",
    "featureTopDislikeTopic",
    "featureTopRateTopic",
    "hetuLevelOneLongTermId",
    "hetuLevelTwoLongTermId",
    "hetuLevelThreeLongTermId",

    "featureUserProfileV1ClickPidList",
    "featureUserProfileV1ClickAidList",
    {"name": "featureUserProfileV1ClickHetuOneList", "as": "featureUserInteractionHetuOneList"},
    "featureUserProfileV1LikePidList",
    "featureUserProfileV1LikeAidList",
    "featureUserProfileV1LikeHetuOneList",
    "featureUserProfileV1CommentPidList",
    "featureUserProfileV1CommentAidList",
    "featureUserProfileV1CommentHetuOneList",
    "featureUserProfileV1FollowPidList",
    "featureUserProfileV1FollowAidList",
    "featureUserProfileV1FollowHetuOneList",
    "featureUserProfileV1ForwardPidList",
    "featureUserProfileV1ForwardAidList",
    "featureUserProfileV1ForwardHetuOneList",
    "featureUserProfileV1ProfileEnterPidList",
    "featureUserProfileV1ProfileEnterAidList",
    "featureUserProfileV1ProfileEnterHetuOneList",
    "featureUserProfileV1DupClickPidList",
    "featureUserProfileV1DupClickAidList",
    "featureUserProfileV1DupClickHetuOneList",
    "featureUserProfileV1Play7SPidList",
    "featureUserProfileV1Play7SAidList",
    "featureUserProfileV1Play7SHetuOneList",
    "featureUserProfileV1Play18SPidList",
    "featureUserProfileV1Play18SAidList",
    "featureUserProfileV1Play18SHetuOneList",

    "featureFountainProfileClickPidList",
    "featureFountainProfileClickAidList",
    "featureFountainProfileClickDnnClusterIds",
    "featureFountainProfileClickImgV3List",
    "featureFountainProfileLikePidList",
    "featureFountainProfileLikeAidList",
    "featureFountainProfileCommentPidList",
    "featureFountainProfileCommentAidList",
    "featureFountainProfileFollowPidList",
    "featureFountainProfileFollowAidList",
    "featureFountainProfileShortViewPidList",
    "featureFountainProfileShortViewAidList",
    "featureFountainProfileEffViewPidList",
    "featureFountainProfileEffViewAidList",
    "featureFountainProfileLongViewPidList",
    "featureFountainProfileLongViewAidList",
    "featureFountainRecentRealshowPids",
    "featureFountainRecentRealshowAids",
    "featureFountainRecentRealshowTags",
    "featureFountainRecentRealshowPlays",
    "featureFountainRecentRealshowTimestamps",
    "featureFountainRecentViewPids",
    "featureFountainRecentViewAids",
    "featureFountainRecentViewTags",
    "featureFountainRecentViewPlays",
    "featureFountainRecentViewDurations",
    "featureFountainRecentViewTimestamps",

    "featureFountainPage",
    "featureFountainIsFirstPage",
    {"name": "page", "as": "featureFountainPageNew"},
    {"name": "featureTabId", "as": "featureTab"},

    "featureSourcePId",
    "sourcePidAuthorId",
    "sourcePidHetu0",
    "sourcePidHetuLevelTwo0",
    "sourcePidDnnCluster",
    "sourcePidMmuImgClusterV3",
    "sourcePidFirstLevelCategory",
    "sourcePidSecondLevelCategory",
    "sourcePidThirdLevelCategory",
    "sourcePidTagId",
    "sourcePidDuration",

    "userRequestHour",
    "userRequestDayOfWeek",
    "uFindUserActiveDegree",
    "uIsLowActiveUser",
    "uFountainRealtimeLikeCountAttr",
    "uFountainRealtimeFollowCountAttr",
    "uFountainRealtimeForwardCountAttr",
    "uFountainRealtimeCommentCountAttr",
    "uFountainRealtimeShortViewCountAttr",
    "uFountainRealtimeLongViewCountAttr",
    "uFountainRealtimeEffectiveViewCountAttr",
    "uFountainRealtimeFinishViewCountAttr",
]

ltr_item_features = [
  {"name" : "photo_id", "as" : "featurePId"},
  {"name" : "author__id", "as" : "featurePAId"},
  {"name" : "author__gender", "as" : "featurePGender"},
  {"name" : "author_age_info__age_segment", "as" : "featurePAgeSegment"},
  {"name" : "location__province_id", "as" : "featurePProvinceId"},
  {"name" : "location__city_id", "as" : "featurePCityId"},
  {"name" : "upload_type", "as" : "featurePUploadType"},
  "featurePUploadTimeDiff",
  {"name" : "duration_ms", "as" : "featurePDurationMs"},
  {"name" : "author__upload_count", "as" : "featurePAUploadCount"},
  {"name" : "author__fans_count", "as" : "featurePAFansCount"},
  {"name" : "music", "as" : "featurePMusic"},
  {"name" : "music_info__music_combo_id", "as": "featurePMusicComboId"},
  {"name" : "hetu_tag_level_info__hetu_level_one", "as" : "featurePHetuTagLevel1"},
  {"name" : "hetu_tag_level_info__hetu_level_two", "as" : " featurePHetuTagLevel2"},
  {"name" : "hetu_tag_level_info__hetu_level_three", "as" : " featurePHetuTagLevel3"},
  {"name" : "author__category_detail__first_level_id", "as" : "featureACategoryLevelOne"},
  {"name" : "author__category_detail__second_level_id", "as" : "featureACategoryLevelTwo"},
  {"name" : "tag", "as" : "featurePTag"},
  {"name" : "mmu_img_cluster_v3", "as" : "featurePMmuImgClusterV3"},
  {"name" : "content_safety_level_with_namespace__level_hot_online", "as" : "featurePContentSafetyLevel"},
  "featurePHotClickCount",
  "featurePHotLikeCount",
  "featurePHotFollowCount",
  "featurePHotLongViewCount",
  "featurePAClickCount",
  "featurePALikeCount",
  "featurePAFollowCount",
  "featurePALongViewCount",
  "featurePHotCtr",
  "featurePHotLtr",
  "featurePHotWtr",
  "featurePHotFtr",
  "featurePHotLvtr",
  "featurePHotSvtr",
  "featurePACtr",
  "featurePALtr",
  "featurePAWtr",
  "featurePAFtr",
  "featurePALvtr",
  "featurePASvtr",
  "cascade_pctr",
  "cascade_pltr",
  "cascade_pwtr",
  "cascade_pftr",
  "cascade_plvtr",
  "cascade_psvtr",
  "cascade_pcmtr",
  "cascade_pcltr",
  "cascade_pcestr",
  "cascade_pepstr",
  "cascade_pwtd",
  {"name":"cascade_ptr", "as": "cascade_pptr"},
  {"name":"cascade_pwatch_time", "as": "cascade_pwatchtime"},
  "featurePHotAvgWatchTime",
  "featurePAAvgWatchTime",
  "fountainWtdV3DurationId",
  "cascade_pcotr",
  {"name":"cascade_wtd_kai", "as": "cascade_pwtd_kai"},
  {"name":"cascade_ftr_kai", "as": "cascade_pfintr"},
  {"name":"cascade_slide_kai", "as": "cascade_pslide"},
]

ltr_opt_item_features = [
  {"name" : "photo_id", "as" : "featurePId"},
  {"name" : "author__id", "as" : "featurePAId"},
  {"name" : "upload_type", "as" : "featurePUploadType"},
  {"name" : "duration_ms", "as" : "featurePDurationMs"},
  {"name" : "hetu_tag_level_info__hetu_level_one", "as" : "featurePHetuTagLevel1"},
  "cascade_pctr",
  "cascade_pltr",
  "cascade_pwtr",
  "cascade_pftr",
  "cascade_plvtr",
  "cascade_psvtr",
  "cascade_pcmtr",
  "cascade_pcltr",
  "cascade_pcestr",
  "cascade_pepstr",
  "cascade_pwtd",
  {"name":"cascade_ptr", "as": "cascade_pptr"},
  {"name":"cascade_pwatch_time", "as": "cascade_pwatchtime"}
]

cascade_distill_item_features =[
  "photo_id",
  "hetu_tag_level_info__hetu_level_one",
  "hetu_tag_level_info__hetu_level_two",
  "duration_ms",
  "cascade_score",
  "cascade_pctr",
  "cascade_pltr",
  "cascade_pwtr",
  "cascade_pftr",
  "cascade_ptr",
  "cascade_plvtr",
  "cascade_phtr",
  "cascade_psvtr",
  "cascade_pcotr",
  "cascade_pwatch_time",
  "cascade_pwtd",
  "cascade_ipw_opt_ftr",
  "cascade_ftr_kai_duration",
  "cascade_longview_score",
  "cascade_shortview_score2",
  "cascade_ftr_kai",
  "cascade_slide_kai",
  "cascade_pepstr",
  "cascade_pcltr",
  "cascade_pcmtr",
  "cascade_pcestr",
  "cascade_wtd_kai",
  "cascade_action_once_interact_score",
  "cascade_action_once_watchtime_score",
  "cascade_pure_value_score",
  "cascade_wtd_kai_mix",
  "cascade_act_kai",
  "cascade_wtd_duration_mix"
  ]
cascade_distill_user_features =[
  "featureUId"
]

cascade_distill_precict_item_features =[
  {"name" : "photo_id", "as" : "photo_idList"},
  {"name" : "author__id", "as" : "author_idList"},
  {"name" : "hetu_level_one", "as" : "hetu_tag_level_info__hetu_level_oneList"},
  {"name" : "hetu_level_two", "as" : "hetu_tag_level_info__hetu_level_twoList"},
  {"name" : "duration_ms", "as" : "duration_msList"},
  {"name" : "cascade_score", "as" : "cascade_scoreList"},
  {"name" : "cascade_pctr", "as" : "cascade_pctrList"},
  {"name" : "cascade_pltr", "as" : "cascade_pltrList"},
  {"name" : "cascade_pwtr", "as" : "cascade_pwtrList"},
  {"name" : "cascade_pftr", "as" : "cascade_pftrList"},
  {"name" : "cascade_ptr", "as" : "cascade_ptrList"},
  {"name" : "cascade_plvtr", "as" : "cascade_plvtrList"},
  {"name" : "cascade_phtr", "as" : "cascade_phtrList"},
  {"name" : "cascade_psvtr", "as" : "cascade_psvtrList"},
  {"name" : "cascade_pcotr", "as" : "cascade_pcotrList"},
  {"name" : "cascade_pwatch_time", "as" : "cascade_pwatch_timeList"},
  {"name" : "cascade_pwtd", "as" : "cascade_pwtdList"},
  {"name" : "cascade_ipw_opt_ftr", "as" : "cascade_ipw_opt_ftrList"},
  {"name" : "cascade_ftr_kai_duration", "as" : "cascade_ftr_kai_durationList"},
  {"name" : "cascade_longview_score", "as" : "cascade_longview_scoreList"},
  {"name" : "cascade_shortview_score2", "as" : "cascade_shortview_score2List"},
  {"name" : "cascade_ftr_kai", "as" : "cascade_ftr_kaiList"},
  {"name" : "cascade_slide_kai", "as" : "cascade_slide_kaiList"},
  {"name" : "cascade_pepstr", "as" : "cascade_pepstrList"},
  {"name" : "cascade_pcltr", "as" : "cascade_pcltrList"},
  {"name" : "cascade_pcotr", "as" : "cascade_pcotrList"},
  {"name" : "cascade_pcmtr", "as" : "cascade_pcmtrList"},
  {"name" : "cascade_pcestr", "as" : "cascade_pcestrList"},
  {"name" : "cascade_wtd_kai", "as" : "cascade_wtd_kaiList"},
  {"name" : "cascade_action_once_interact_score", "as" : "cascade_action_once_interact_scoreList"},
  {"name" : "cascade_action_once_watchtime_score", "as" : "cascade_action_once_watchtime_scoreList"},
  {"name" : "cascade_pure_value_score", "as" : "cascade_pure_value_scoreList"},
  {"name" : "cascade_long_term_interest_ee_score", "as" : "cascade_long_term_interest_ee_scoreList"},
  {"name" : "cascade_act_kai", "as" : "cascade_act_kaiList"},
  {"name" : "cascade_wtd_kai_mix", "as" : "cascade_wtd_kai_mixList"}
]

# 全链路&曝光样本流级联 用户特征
cascade_full_link_distill_user_features = [
    "uId",
    "dId",
    "uGender",
    "uInferYear",
    "uTrueYear",
    "uBasicAge",
    "uFollowCount",
    "uUploadCount",
    "uCityId",
    "uProvinceId",
    "uVisitMod",
    "uClickPids",
    "uLikePids",
    "uFollowAids",
]
