from cascading import CommonModule


class FountainSplashCascadingScoreModule(CommonModule):
  def __init__(self, name: str) -> None:
    super().__init__(name)

  def process(self) -> None:
    self.flow \
      .fountain_calc_ensemble_score(
        skip="{{fountain_cascade_skip_ensemble}}",
        range_end="{{fountain_cascade_ensemble_range_end}}",
        user_new_proportion="{{fountain_cascade_ensemble_sort_enable_proportion}}",
        user_power_calc="{{fountain_cascade_ensemble_sort_enable_power_calc}}",
        user_power_calc_v2="{{fountain_cascade_ensemble_sort_enable_power_calc_v2}}",
        use_xtr_raw_score="{{fountain_cascade_ensemble_sort_use_xtr_raw_score}}",
        enable_time_cost_opt="{{fountain_cascade_enable_time_cost_opt}}",
        save_score_to_attr="cascade_ensemble_score",
        user_info_ptr_attr="user_info_ptr",
        action_day="{{fountain_mc_variant_weight_action_day_num}}",
        rank_smooth="{{fountain_splash_cascade_ensemble_rank_smooth}}",
        queues=[
          {
            "name": "cascade_score",
            "weight": 0.5,
            "weight_attr": "fountain_ensemble_weight_cascade_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_pctr",
            "weight": 0.2,
            "weight_attr": "xlife_fountain_ensemble_weight_cascade_click_score",
            "power_weight_attr": "xlife_fountain_ensemble_weight_cascade_click_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_click_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_click_raw_pow_weight",
          },
          {
            "name": "cascade_pltr",
            "weight": 0.25,
            "weight_attr": "fountain_ensemble_weight_cascade_like_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_like_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_like_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_like_raw_pow_weight",
          },
          {
            "name": "cascade_pwtr",
            "weight": 0.18,
            "weight_attr": "fountain_ensemble_weight_cascade_follow_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_follow_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_follow_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_follow_raw_pow_weight",
          },
          {
            "name": "cascade_pftr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_forward_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_forward_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_forward_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_forward_raw_pow_weight",
          },
          {
            "name": "cascade_longview_score",
            "weight": 0.1,
            "weight_attr": "xlife_fountain_ensemble_weight_cascade_longview_score",
            "power_weight_attr": "xlife_fountain_ensemble_weight_cascade_longview_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_psvtr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_shortview_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_shortview_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "reverse_order": True,
          },
          {
            "name": "cascade_shortview_score2",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_shortview_score2",
            "power_weight_attr": "fountain_ensemble_weight_cascade_shortview_score2",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_shortview_score2_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_shortview_score2_raw_pow_weight",
          },
          {
            "name": "cascade_ptr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_profile_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_profile_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_profile_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_profile_raw_pow_weight",
          },
          {
            "name": "cascade_pcmtr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_comment_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_comment_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_comment_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_comment_raw_pow_weight",
          },
          {
            "name": "cascade_pcestr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_cestr_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_cestr_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_cestr_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_cestr_raw_pow_weight",
          },
          {
            "name": "cascade_pepstr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_epstr_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_epstr_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_epstr_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_epstr_raw_pow_weight",
          },
          {
            "name": "cascade_pwatch_time",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_pwatch_time",
            "power_weight_attr": "fountain_ensemble_weight_cascade_pwatch_time",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_pwatch_time_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_pwatch_time_raw_pow_weight",
          },
          {
            "name": "cascade_pcltr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_pcltr",
            "power_weight_attr": "fountain_ensemble_weight_cascade_pcltr",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "variant_weight": "fountain_ensemble_variant_weight_cascade_pcltr",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_collect_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_collect_raw_pow_weight",
          },
          {
            "name": "cascade_pwtd",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_pwtd",
            "power_weight_attr": "fountain_ensemble_weight_cascade_pwtd",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_pwtd_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_pwtd_raw_pow_weight",
          },
          {
            "name": "cascade_phtr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_phtr",
            "power_weight_attr": "fountain_ensemble_weight_cascade_phtr",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_hate_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_hate_raw_pow_weight",
          },
          {
            "name": "cascade_ftr_kai",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_ftr_kai",
            "power_weight_attr": "fountain_ensemble_weight_cascade_ftr_kai",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_ftr_kai_duration",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_ftr_kai_duration",
            "power_weight_attr": "fountain_ensemble_weight_cascade_ftr_kai_duration",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_ipw_opt_ftr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_ipw_opt_ftr",
            "power_weight_attr": "fountain_ensemble_weight_cascade_ipw_opt_ftr",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_pcotr",
            "weight": 0.0,
            "weight_attr": "xlife_fountain_ensemble_weight_cascade_pcotr",
            "power_weight_attr": "xlife_fountain_ensemble_weight_cascade_pcotr",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_pswptr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_swptr_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_swptr_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_swptr_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_swptr_raw_pow_weight",
          },
          {
            "name": "cascade_pswptr_after",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_swptr_after_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_swptr_after_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_swptr_after_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_swptr_after_raw_pow_weight",
          },
          {
            "name": "cascade_plstr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_lstr_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_lstr_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_lstr_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_lstr_raw_pow_weight",
          },
          {
            "name": "cascade_plsst",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_lsst_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_lsst_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_lsst_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_lsst_raw_pow_weight",
          },
          {
            "name": "cascade_pair_evtr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_pair_evtr_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_pair_evtr_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_pair_evtr_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_pair_evtr_raw_pow_weight",
          },
          {
            "name": "cascade_pair_lvtr",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_pair_lvtr_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_pair_lvtr_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_pair_lvtr_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_pair_lvtr_raw_pow_weight",
          },
          {
            "name": "cascade_fc_pvtr2",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_fc_pvtr2_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_fc_pvtr2_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
            "raw_weight_attr": "fountain_splash_cascade_ensemble_sort_fc_pvtr2_raw_weight",
            "raw_pow_weight_attr": "fountain_splash_cascade_ensemble_sort_fc_pvtr2_raw_pow_weight",
          },
          {
            "name": "cascade_slide_kai",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_slide_kai",
            "power_weight_attr": "fountain_ensemble_weight_cascade_slide_kai",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_act_kai",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_act_kai",
            "power_weight_attr": "fountain_ensemble_weight_cascade_act_kai",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_wtd_kai",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_wtd_kai",
            "power_weight_attr": "fountain_ensemble_weight_cascade_wtd_kai",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_wtd_kai_mix",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_wtd_kai_mix",
            "power_weight_attr": "fountain_ensemble_weight_cascade_wtd_kai_mix",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_action_once_interact_score",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_action_once_interact_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_action_once_interact_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_action_once_watchtime_score",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_action_once_watchtime_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_action_once_watchtime_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_wtd_percent",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_wtd_percent",
            "power_weight_attr": "fountain_ensemble_weight_cascade_wtd_percent",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "cascade_wtd_duration_mix",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_wtd_duration_mix",
            "power_weight_attr": "fountain_ensemble_weight_cascade_wtd_duration_mix",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
          {
            "name": "hate_similary_score",
            "weight": 0.0,
            "weight_attr": "fountain_ensemble_weight_cascade_hate_similary_score",
            "power_weight_attr": "fountain_ensemble_weight_cascade_hate_similary_score",
            "temperature_attr": "fountain_cascade_ensemble_temperature",
          },
        ],
      ) \
      .sort(
        range_end="{{fountain_cascade_ensemble_range_end}}",
        score_from_attr="cascade_ensemble_score",
      ) \
      .truncate(
        skip="{{skip_fountain_pre_fullrank_model_limit_v2_splash}}",
        size_limit="{{fountain_pre_fullrank_size_limit_v2_splash}}",
      )

    return self
