#!/usr/bin/env python3
# coding=utf-8

#粗排非首屏队列，包含只有comb流量的processor

#第一轮分桶排序
explore_cluster_sort_queues = [
  {
    "name": "cascade_score",
    "weight": 0.5,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_cascade_score_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_cascade_score_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_cascade_score_raw_pow_weight",
  },
  {
    "name": "cascade_pctr",
    "weight": 0.2,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_click_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_click_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_click_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_click_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_click_raw_pow_weight",
    "fractile_value_attr": "cascade_pctr_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_pctr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_pctr_fractile_pow_weight",
    "use_vv_min_rank_attr" : "fountain_cascade_variant_cluster_pctr_vv_min_rank",
  },
  {
    "name": "cascade_pltr",
    "weight": 0.25,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_like_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_like_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "cluster_reweight_attr": "fountain_variant_cluster_sort_reweight_config_pltr",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_like_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_like_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_like_raw_pow_weight",
    "fractile_value_attr": "cascade_pltr_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_pltr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_pltr_fractile_pow_weight",
    "use_act_min_rank_attr" : "fountain_cascade_variant_cluster_pltr_act_min_rank",
  },
  {
    "name": "cascade_pwtr",
    "weight": 0.18,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_follow_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_follow_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "cluster_reweight_attr": "fountain_variant_cluster_sort_reweight_config_pwtr",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_follow_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_follow_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_follow_raw_pow_weight",
    "fractile_value_attr": "cascade_pwtr_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_pwtr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_pwtr_fractile_pow_weight",
    "use_act_min_rank_attr" : "fountain_cascade_variant_cluster_pwtr_act_min_rank",
  },
  {
    "name": "cascade_pftr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_forward_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_forward_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "cluster_reweight_attr": "fountain_variant_cluster_sort_reweight_config_pftr",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_forward_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_forward_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_forward_raw_pow_weight",
    "use_act_min_rank_attr" : "fountain_cascade_variant_cluster_pftr_act_min_rank",
  },
  {
    "name": "cascade_longview_score",
    "weight": 0.1,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_longview_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_longview_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_longview_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_longview_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_longview_raw_pow_weight",
    "use_play_min_rank_attr" : "fountain_cascade_variant_cluster_longview_score_play_min_rank",
  },
  {
    "name": "cascade_psvtr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_shortview_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_shortview_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_shortview_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_shortview_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_shortview_raw_pow_weight",
    "reverse_order": True,
  },
  {
    "name": "cascade_shortview_score2",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_shortview_score2",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_shortview_score2",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_shortview_score2_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_shortview_score2_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_shortview_score2_raw_pow_weight",
    "use_vv_min_rank_attr" : "fountain_cascade_variant_cluster_shortview_score2_vv_min_rank",
  },
  {
    "name": "cascade_ptr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_profile_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_profile_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_profile_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_profile_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_profile_raw_pow_weight",
    "use_act_min_rank_attr" : "fountain_cascade_variant_cluster_ptr_act_min_rank",
  },
  {
    "name": "cascade_pcmtr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_comment_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_comment_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_comment_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_comment_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_comment_raw_pow_weight",
    "fractile_value_attr": "cascade_pcmtr_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_pcmtr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_pcmtr_fractile_pow_weight",
    "use_act_min_rank_attr" : "fountain_cascade_variant_cluster_pcmtr_act_min_rank",
  },
  {
    "name": "cascade_pcestr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_cestr_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_cestr_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_cestr_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_cestr_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_cestr_raw_pow_weight",
  },
  {
    "name": "cascade_pepstr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_epstr_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_epstr_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_epstr_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_epstr_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_epstr_raw_pow_weight",
    "fractile_value_attr": "cascade_pepstr_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_pepstr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_pepstr_fractile_pow_weight",
    "use_act_min_rank_attr" : "fountain_cascade_variant_cluster_pepstr_act_min_rank",
  },
  {
    "name": "cascade_pwatch_time",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_pwatch_time",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_pwatch_time",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "cluster_reweight_attr": "fountain_variant_cluster_sort_reweight_config_pwatch_time",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_pwatch_time_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_pwatch_time_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_pwatch_time_raw_pow_weight",
    "fractile_value_attr": "cascade_pwatch_time_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_pwatch_time_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_pwatch_time_fractile_pow_weight",
    "use_play_min_rank_attr" : "fountain_cascade_variant_cluster_pwatch_time_play_min_rank",
  },
  {
    "name": "cascade_distill_fast_rank",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_distill_fast_rank",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_distill_fast_rank",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_distill_fast_rank_raw_bias",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_distill_fast_rank_raw_weight",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_distill_fast_rank_raw_pow_weight",
  },
  {
    "name": "cascade_pcltr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_pcltr",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_pcltr",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "variant_weight": "fountain_variant_cluster_sort_variant_weight_cascade_pcltr",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_collect_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_collect_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_collect_raw_pow_weight",
    "fractile_value_attr": "cascade_pcltr_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_pcltr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_pcltr_fractile_pow_weight",
    "use_act_min_rank_attr" : "fountain_cascade_variant_cluster_pcltr_act_min_rank",
  },
  {
    "name": "cascade_phtr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_phtr",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_phtr",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_hate_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_hate_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_hate_raw_pow_weight",
  },
  {
    "name": "cascade_pwtd",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_pwtd",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_pwtd",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "cluster_reweight_attr": "fountain_variant_cluster_sort_reweight_config_pwtd",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_pwtd_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_pwtd_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_pwtd_raw_pow_weight",
    "use_play_min_rank_attr" : "fountain_cascade_variant_cluster_pwtd_play_min_rank",
  },
  {
    "name": "cascade_wtd_kai_mix",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_kai_mix",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_kai_mix",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_kai_mix_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_kai_mix_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_kai_mix_raw_pow_weight",
    "fractile_value_attr": "cascade_pwtd_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_pwtd_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_pwtd_fractile_pow_weight",
    "use_play_min_rank_attr" : "fountain_cascade_variant_cluster_wtd_kai_mix_play_min_rank",
  },
  {
    "name": "cascade_act_kai",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_act_kai",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_act_kai",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_act_kai_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_act_kai_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_act_kai_raw_pow_weight",
  },
  {
    "name": "cascade_ftr_kai_duration",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_ftr_kai_duration",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_ftr_kai_duration",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_ftr_kai_duration_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_ftr_kai_duration_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_ftr_kai_duration_raw_pow_weight",
    "use_play_min_rank_attr" : "fountain_cascade_variant_cluster_ftr_kai_duration_play_min_rank",
  },
  {
    "name": "cascade_ipw_opt_ftr",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_ipw_opt_ftr",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_ipw_opt_ftr",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_ipw_opt_ftr_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_ipw_opt_ftr_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_ipw_opt_ftr_raw_pow_weight",
    "use_play_min_rank_attr" : "fountain_cascade_variant_cluster_ipw_opt_ftr_play_min_rank",
  },
  {
    "name": "cascade_slide_kai",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_slide_kai",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_slide_kai",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_slide_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_slide_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_slide_raw_pow_weight",
    "fractile_value_attr": "cascade_slide_kai_fractile_score",
    "fractile_weight_attr": "fountain_cascade_variant_cluster_slide_kai_fractile_weight",
    "fractile_pow_weight_attr": "fountain_cascade_variant_cluster_slide_kai_fractile_pow_weight",
    "use_vv_min_rank_attr" : "fountain_cascade_variant_cluster_slide_kai_vv_min_rank",
  },
  {
    "name": "cascade_action_once_interact_score",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_action_once_interact_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_action_once_interact_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_action_once_interact_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_action_once_interact_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_action_once_interact_raw_pow_weight",
  },
  {
    "name": "cascade_action_once_watchtime_score",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_action_once_watchtime_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_action_once_watchtime_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_action_once_watchtime_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_action_once_watchtime_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_action_once_watchtime_raw_pow_weight",
  },
  {
    "name": "comirec_rank_score",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_comirec_rank_score",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_comirec_rank_score",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
  },
  {
    "name": "cascade_wtd_percent",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_percent",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_percent",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_percent_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_percent_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_percent_raw_pow_weight",
    "use_play_min_rank_attr" : "fountain_cascade_variant_cluster_wtd_percent_play_min_rank",
  },
  {
    "name": "cascade_wtd_duration_mix",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_duration_mix",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_duration_mix",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_duration_mix_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_duration_mix_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_duration_mix_raw_pow_weight",
  },
  {
    "name": "cascade_wtd_90p",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_90p",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_90p",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_90p_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_90p_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_90p_raw_pow_weight",
    "use_vv_min_rank_attr" : "fountain_cascade_variant_cluster_wtd_90p_vv_min_rank",
  },
  {
    "name": "cascade_wtd_80p",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_80p",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_wtd_80p",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_80p_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_80p_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_wtd_80p_raw_pow_weight",
  },
  {
    "name": "cascade_distill_show",
    "weight": 0.0,
    "weight_attr": "fountain_variant_cluster_sort_weight_cascade_distill_show",
    "power_weight_attr": "fountain_variant_cluster_sort_weight_cascade_distill_show",
    "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    "raw_weight_attr": "fountain_fast_cascade_variant_cluster_sort_distill_show_raw_weight",
    "raw_bias_attr": "fountain_fast_cascade_variant_cluster_sort_distill_show_raw_bias",
    "raw_pow_weight_attr": "fountain_fast_cascade_variant_cluster_sort_distill_show_raw_pow_weight",
  },
]

#第二轮混排 #第二轮混排
cascade_ensemble_sort_queues = [
  {
      "name": "cascade_long_term_interest_ee_score",
      "weight": 0.5,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_long_term_interest_ee_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_long_term_interest_ee_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
  },
  {
      "name": "cascade_score",
      "weight": 0.5,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
  },
  {
      "name": "cascade_pctr",
      "weight": 0.2,
      "weight_attr": "xlife_fountain_fast_ensemble_weight_cascade_click_score",
      "power_weight_attr": "xlife_fountain_fast_ensemble_power_weight_cascade_click_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_vv_smooth_attr",
      "raw_weight_attr": "xlife_fountain_fast_cascade_ensemble_click_raw_weight",
      "raw_pow_weight_attr": "xlife_fountain_fast_cascade_ensemble_click_raw_pow_weight",
      "fractile_value_attr": "cascade_pctr_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_pctr_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_pctr_fractile_pow_weight",
  },
  {
      "name": "cascade_pltr",
      "weight": 0.25,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_like_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_like_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_like_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_like_raw_pow_weight",
      "use_min_rank": True,
      "fractile_value_attr": "cascade_pltr_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_pltr_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_pltr_fractile_pow_weight",
  },
  {
      "name": "cascade_pwtr",
      "weight": 0.18,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_follow_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_follow_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_follow_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_follow_raw_pow_weight",
      "use_min_rank": True,
      "fractile_value_attr": "cascade_pwtr_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_pwtr_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_pwtr_fractile_pow_weight",
  },
  {
      "name": "cascade_pftr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_forward_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_forward_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_forward_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_forward_raw_pow_weight",
      "use_min_rank": True
  },
  {
      "name": "cascade_longview_score",
      "weight": 0.1,
      "weight_attr": "xlife_fountain_fast_ensemble_weight_cascade_longview_score",
      "power_weight_attr": "xlife_fountain_fast_ensemble_power_weight_cascade_longview_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_watchtime_smooth_attr",
  },
  {
      "name": "cascade_psvtr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_shortview_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_shortview_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_vv_smooth_attr",
      "reverse_order": True,
  },
  {
      "name": "cascade_shortview_score2",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_shortview_score2",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_shortview_score2",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_vv_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_shortview_score2_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_shortview_score2_raw_pow_weight",
  },
  {
      "name": "cascade_ptr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_profile_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_profile_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_profile_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_profile_raw_pow_weight",
      "use_min_rank": True
  },
  {
      "name": "cascade_pcmtr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_comment_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_comment_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_comment_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_comment_raw_pow_weight",
      "use_min_rank": True,
      "fractile_value_attr": "cascade_pcmtr_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_pcmtr_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_pcmtr_fractile_pow_weight",
  },
  {
      "name": "cascade_pcestr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_cestr_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_cestr_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_cestr_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_cestr_raw_pow_weight",
      "use_min_rank": True
  },
  {
      "name": "cascade_pepstr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_epstr_score",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_epstr_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_epstr_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_epstr_raw_pow_weight",
      "use_min_rank": True,
      "fractile_value_attr": "cascade_pepstr_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_pepstr_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_pepstr_fractile_pow_weight",
  },
  {
      "name": "cascade_pwatch_time",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_pwatch_time",
      "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_pwatch_time",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_watchtime_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_pwatch_time_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_pwatch_time_raw_pow_weight",
      "fractile_value_attr": "cascade_pwatch_time_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_pwatch_time_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_pwatch_time_fractile_pow_weight",
  },
  {
      "name": "cascade_pcltr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_pcltr",
      "power_weight_attr": "fountain_fast_ensemble_weight_cascade_pcltr",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "variant_weight": "fountain_fast_ensemble_variant_weight_cascade_pcltr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_collect_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_collect_raw_pow_weight",
      "use_min_rank": True,
      "fractile_value_attr": "cascade_pcltr_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_pcltr_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_pcltr_fractile_pow_weight",
  },
  {
      "name": "cascade_phtr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_phtr",
      "power_weight_attr": "fountain_fast_ensemble_weight_cascade_phtr",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_hate_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_hate_raw_pow_weight",
      "rank_cliff_attr": "fountain_fast_cascade_ensemble_hate_rank_cliff_attr",
      "rank_cliff_ratio_attr": "fountain_fast_cascade_ensemble_hate_rank_cliff_ratio_attr",
      "rank_height_attr": "fountain_fast_cascade_ensemble_hate_rank_height_attr",
      "cliff_score_bias_attr": "fountain_fast_cascade_ensemble_hate_cliff_score_bias_attr",
      "score_threshold": "fountain_fast_cascade_ensemble_htr_que_cliff_score_threshold"
  },
  {
      "name": "cascade_pwtd",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_pwtd",
      "power_weight_attr": "fountain_fast_ensemble_weight_cascade_pwtd",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_watchtime_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_pwtd_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_pwtd_raw_pow_weight",
  },
  {
      "name": "cascade_wtd_kai_mix",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_kai_mix",
      "power_weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_kai_mix",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_wtd_kai_mix_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_wtd_kai_mix_raw_pow_weight",
      "fractile_value_attr": "cascade_pwtd_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_pwtd_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_pwtd_fractile_pow_weight",
  },
  {
      "name": "cascade_ftr_kai_duration",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_ftr_kai_duration",
      "power_weight_attr": "fountain_fast_ensemble_weight_cascade_ftr_kai_duration",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_watchtime_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_ftr_kai_duration_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_ftr_kai_duration_raw_pow_weight",
  },
  {
      "name": "cascade_ipw_opt_ftr",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_ipw_opt_ftr",
      "power_weight_attr": "fountain_fast_ensemble_weight_cascade_ipw_opt_ftr",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_watchtime_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_ipw_opt_ftr_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_ipw_opt_ftr_raw_pow_weight",
  },
  {
      "name": "cascade_pcotr",
      "weight": 0.0,
      "weight_attr": "xlife_fountain_fast_ensemble_weight_cascade_pcotr",
      "power_weight_attr": "xlife_fountain_fast_ensemble_weight_cascade_pcotr",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_vv_smooth_attr",
  },
  {
      "name": "cascade_slide_kai",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_cascade_slide_kai",
      "power_weight_attr": "fountain_fast_ensemble_weight_cascade_slide_kai",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_vv_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_slide_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_slide_raw_pow_weight",
      "fractile_value_attr": "cascade_slide_kai_fractile_score",
      "fractile_weight_attr": "fountain_fast_cascade_ensemble_slide_kai_fractile_weight",
      "fractile_pow_weight_attr": "fountain_fast_cascade_ensemble_slide_kai_fractile_pow_weight",
  },
  {
      "name": "cascade_action_once_interact_score",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_action_once_interact_score",
      "power_weight_attr": "fountain_fast_ensemble_weight_action_once_interact_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_interact_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_action_once_interact_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_action_once_interact_raw_pow_weight",
  },
  {
      "name": "cascade_action_once_watchtime_score",
      "weight": 0.0,
      "weight_attr": "fountain_fast_ensemble_weight_action_once_watchtime_score",
      "power_weight_attr": "fountain_fast_ensemble_weight_action_once_watchtime_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
      "smooth_attr": "fountain_fast_cascade_ensemble_watchtime_smooth_attr",
      "raw_weight_attr": "fountain_fast_cascade_ensemble_action_once_watchtime_raw_weight",
      "raw_pow_weight_attr": "fountain_fast_cascade_ensemble_action_once_watchtime_raw_pow_weight",
  },
  {
      "name": "topk_mgs_expected_score",
      "weight": 0.0,
      "weight_attr": "life_fountain_fast_ensemble_weight_topk_mgs_expected_score",
      "power_weight_attr": "life_fountain_fast_ensemble_weight_topk_mgs_expected_score",
      "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
  },
]

# 粗排第二阶段分组队列
cascade_hierarchial_vv_queues = [
    {
        "name": "cascade_pctr",
        "weight": 0.2,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_click_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_click_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pctr_debias",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_pctr_debias",
        "temperature_attr": "fountain_variant_mc_temperature",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_pctr_debias"
    },
    {
        "name": "cascade_ftr_kai",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_ftr_kai",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_ftr_kai",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_kai_mix",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_kai_mix",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_kai_mix",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_act_kai",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_act_kai",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_act_kai",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_slide_kai",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_slide_kai",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_slide_kai",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_ftr_diff_score",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_ftr_diff_score",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_ftr_diff_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_long_term_interest_ee_score",
        "weight": 0.5,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_long_term_interest_ee_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_long_term_interest_ee_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_percent",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_percent",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_percent",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_duration_mix",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_duration_mix",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_duration_mix",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
]

cascade_hierarchial_act_queues = [
    {
        "name": "cascade_pltr",
        "weight": 0.25,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_like_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_like_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pwtr",
        "weight": 0.18,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_follow_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_follow_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pftr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_forward_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_forward_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_ptr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_profile_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_profile_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pcmtr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_comment_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_comment_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pcestr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_cestr_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_cestr_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pepstr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_epstr_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_epstr_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pltr_debias",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_pltr_debias",
        "temperature_attr": "fountain_variant_mc_temperature",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_pltr_debias"
    },
    {
        "name": "cascade_pwtr_debias",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_pwtr_debias_rate",
        "temperature_attr": "fountain_variant_mc_temperature",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_pwtr_debias_rate"
    },
    {
        "name": "emp_htr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_emp_htr",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_emp_htr",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
        "reverse_order": True,
    },
    {
        "name": "cascade_pcltr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_pcltr",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_pcltr",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
        "variant_weight": "fountain_fast_ensemble_variant_weight_cascade_pcltr"
    },
    {
        "name": "cascade_phtr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_phtr",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_phtr",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pcotr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_pcotr",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_pcotr",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_action_once_interact_score",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_action_once_interact_score",
        "power_weight_attr": "fountain_fast_ensemble_weight_action_once_interact_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
]

cascade_hierarchial_ptime_queues = [
    {
        "name": "cascade_longview_score",
        "weight": 0.1,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_longview_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_longview_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_psvtr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_shortview_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_shortview_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
        "reverse_order": True,
    },
    {
        "name": "cascade_shortview_score2",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_shortview_score2",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_shortview_score2",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_pwatch_time",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_pwatch_time",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_pwatch_time",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_longview_score_debias",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_longview_score_debias",
        "temperature_attr": "fountain_variant_mc_temperature",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_longview_score_debias"
    },
    {
        "name": "cascade_psvtr_debias",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_psvtr_debias",
        "temperature_attr": "fountain_variant_mc_temperature",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_psvtr_debias"
    },
    {
        "name": "cascade_pwatch_time_debias",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_pwatch_time_debias",
        "temperature_attr": "fountain_variant_mc_temperature",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_pwatch_time_debias"
    },
    {
        "name": "cascade_wtd_kai",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_kai",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_wtd_kai",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_ftr_kai_duration",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_ftr_kai_duration",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_ftr_kai_duration",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_ipw_opt_ftr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_ipw_opt_ftr",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_ipw_opt_ftr",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_action_once_watchtime_score",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_action_once_watchtime_score",
        "power_weight_attr": "fountain_fast_ensemble_weight_action_once_watchtime_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
]

cascade_hierarchial_queues = [
    {
        "name": "cascade_ensemble_score",
        "weight": 0.5,
        "weight_attr": "fountain_cascade_hierarchial_ensemble_weight",
        "power_weight_attr": "fountain_cascade_hierarchial_ensemble_weight",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_hierarchial_vv_score",
        "weight": 0.5,
        "weight_attr": "fountain_cascade_hierarchial_vv_weight",
        "power_weight_attr": "fountain_cascade_hierarchial_vv_weight",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_hierarchial_act_score",
        "weight": 0.5,
        "weight_attr": "fountain_cascade_hierarchial_act_weight",
        "power_weight_attr": "fountain_cascade_hierarchial_act_weight",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_hierarchial_ptime_score",
        "weight": 0.5,
        "weight_attr": "fountain_cascade_hierarchial_ptime_weight",
        "power_weight_attr": "fountain_cascade_hierarchial_ptime_weight",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_score",
        "weight": 0.5,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_distill_fast_rank",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_prerank_ensemble_score",
        "power_weight_attr": "fountain_fast_ensemble_power_weight_cascade_prerank_ensemble_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    },
    {
        "name": "cascade_longterm_score",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_weight_cascade_longterm_score",
        "power_weight_attr": "fountain_fast_ensemble_weight_cascade_longterm_score",
        "temperature_attr": "fountain_fast_cascade_ensemble_temperature",
    }
]

# prerank
cascade_ensemble_prerank_sort_queues = [
    {
        "name": "cascade_pctr",
        "weight": 0.2,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_click_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_click_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pltr",
        "weight": 0.25,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_like_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_like_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pwtr",
        "weight": 0.18,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_follow_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_follow_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pftr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_forward_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_forward_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_longview_score",
        "weight": 0.1,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_longview_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_longview_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_psvtr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_shortview_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_shortview_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
        "reverse_order": True,
    },
    {
        "name": "cascade_shortview_score2",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_shortview_score2",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_shortview_score2",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_ptr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_profile_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_profile_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pcmtr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_comment_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_comment_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pcestr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_cestr_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_cestr_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pepstr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_epstr_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_epstr_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pwatch_time",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_pwatch_time",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_pwatch_time",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_distill_fast_rank",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_distill_fast_rank",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_distill_fast_rank",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
        "raw_weight_attr": "fountain_fast_prerank_ensemble_distill_rank_raw_weight",
        "raw_pow_weight_attr": "fountain_fast_prerank_ensemble_distill_rank_raw_pow_weight",
    },
    {
        "name": "cascade_pcltr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_pcltr",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_pcltr",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_phtr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_phtr",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_phtr",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pwtd",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_pwtd",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_pwtd",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_ftr_kai",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_ftr_kai",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_ftr_kai",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_kai_mix",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_kai_mix",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_kai_mix",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_kai",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_kai",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_kai",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_act_kai",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_act_kai",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_act_kai",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_ftr_kai_duration",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_ftr_kai_duration",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_ftr_kai_duration",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_ipw_opt_ftr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_ipw_opt_ftr",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_ipw_opt_ftr",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_pcotr",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_pcotr",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_pcotr",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_slide_kai",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_slide_kai",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_slide_kai",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_action_once_interact_score",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_action_once_interact",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_action_once_interact",
        "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    },
    {
        "name": "cascade_action_once_watchtime_score",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_action_once_watchtime",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_action_once_watchtime",
        "temperature_attr": "fountain_cascade_variant_cluster_sort_temperature",
    },
    {
        "name": "prerank_score",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_weight_prerank_score",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_weight_prerank_score",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_percent",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_percent",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_percent",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_duration_mix",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_duration_mix",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_duration_mix",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_90p",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_90p",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_90p",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_wtd_80p",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_80p",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_wtd_80p",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
    },
    {
        "name": "cascade_distill_rerank",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_distill_rerank",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_distill_rerank",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
        "raw_weight_attr": "fountain_fast_prerank_ensemble_distill_rerank_raw_weight",
        "raw_pow_weight_attr": "fountain_fast_prerank_ensemble_distill_rerank_raw_pow_weight",
    },
    {
        "name": "cascade_distill_show",
        "weight": 0.0,
        "weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_distill_show",
        "power_weight_attr": "fountain_fast_ensemble_prerank_weight_cascade_distill_show",
        "temperature_attr": "fountain_fast_cascade_prerank_ensemble_temperature",
        "raw_weight_attr": "fountain_fast_prerank_ensemble_distill_show_raw_weight",
        "raw_pow_weight_attr": "fountain_fast_prerank_ensemble_distill_show_raw_pow_weight",
    },
]

# 第一轮纯净值队列
cascade_pure_value_queue = [
    {
        "name": "cascade_score",
        "use_mapping": "fountain_pure_value_cascade_score_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_score_weight"
    },
    {
        "name": "cascade_pctr",
        "use_mapping": "fountain_pure_value_cascade_pctr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pctr_weight"
    },
    {
        "name": "cascade_pltr",
        "use_mapping": "fountain_pure_value_cascade_pltr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pltr_weight"
    },
    {
        "name": "cascade_pwtr",
        "use_mapping": "fountain_pure_value_cascade_pwtr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pwtr_weight"
    },
    {
        "name": "cascade_pftr",
        "use_mapping": "fountain_pure_value_cascade_pftr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pftr_weight"
    },
    {
        "name": "cascade_longview_score",
        "use_mapping": "fountain_pure_value_cascade_longview_score_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_longview_score_weight"
    },
    {
        "name": "cascade_psvtr",
        "use_mapping": "fountain_pure_value_cascade_psvtr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_psvtr_weight"
    },
    {
        "name": "cascade_shortview_score2",
        "use_mapping": "fountain_pure_value_cascade_shortview_score2_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_shortview_score2_weight"
    },
    {
        "name": "cascade_ptr",
        "use_mapping": "fountain_pure_value_cascade_ptr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_ptr_weight"
    },
    {
        "name": "cascade_pcmtr",
        "use_mapping": "fountain_pure_value_cascade_pcmtr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pcmtr_weight"
    },
    {
        "name": "cascade_pcestr",
        "use_mapping": "fountain_pure_value_cascade_pcestr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pcestr_weight"
    },
    {
        "name": "cascade_pwatch_time",
        "use_mapping": "fountain_pure_value_cascade_pwatch_time_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pwatch_time_weight"
    },
    {
        "name": "cascade_distill_fast_rank",
        "use_mapping": "fountain_pure_value_cascade_distill_fast_rank_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_distill_fast_rank_weight"
    },
    {
        "name": "cascade_pcltr",
        "use_mapping": "fountain_pure_value_cascade_pcltr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pcltr_weight"
    },
    {
        "name": "cascade_phtr",
        "use_mapping": "fountain_pure_value_cascade_phtr_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_phtr_weight"
    },
    {
        "name": "cascade_pwtd",
        "use_mapping": "fountain_pure_value_cascade_pwtd_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_pwtd_weight"
    },
    {
        "name": "cascade_ftr_kai",
        "use_mapping": "fountain_pure_value_cascade_ftr_kai_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_ftr_kai_weight"
    },
    {
        "name": "cascade_ftr_kai_duration",
        "use_mapping": "fountain_pure_value_cascade_ftr_kai_duration_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_ftr_kai_duration_weight"
    },
    {
        "name": "cascade_slide_kai",
        "use_mapping": "fountain_pure_value_cascade_slide_kai_use_mapping",
        "weight_attr": "fountain_pure_value_cascade_slide_kai_weight"
    },
]


mc_pxtr_fractile_score_queues = [
  {
    "name": "pwatch_time",
    "xtr_attr": "cascade_pwatch_time",
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_pwatch_time_wgt",
    "fractile_value_attr": "cascade_pwatch_time_fractile_score"
  },
  {
    "name": "pwtd",
    "xtr_attr": "cascade_wtd_kai_mix",  # 反解时长
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_wtd_wgt",
    "fractile_value_attr": "cascade_pwtd_fractile_score"
  },
  {
    "name": "pctr",
    "xtr_attr": "cascade_pctr",
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_ctr_wgt",
    "fractile_value_attr": "cascade_pctr_fractile_score"
  },
  {
    "name": "pslide",
    "xtr_attr": "cascade_slide_kai",
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_slide_wgt",
    "fractile_value_attr": "cascade_slide_kai_fractile_score"
  },
  {
    "name": "pltr",
    "xtr_attr": "cascade_pltr",
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_ltr_wgt",
    "fractile_value_attr": "cascade_pltr_fractile_score"
  },
  {
    "name": "pwtr",
    "xtr_attr": "cascade_pwtr",
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_wtr_wgt",
    "fractile_value_attr": "cascade_pwtr_fractile_score"
  },
  {
    "name": "pcmtr",
    "xtr_attr": "cascade_pcmtr",
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_cmtr_wgt",
    "fractile_value_attr": "cascade_pcmtr_fractile_score"
  },
  {
    "name": "pcltr",
    "xtr_attr": "cascade_pcltr",
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_cltr_wgt",
    "fractile_value_attr": "cascade_pcltr_fractile_score"
  },
  {
    "name": "pepstr",
    "xtr_attr": "cascade_pepstr",
    "weight_attr": "fountain_mc_pxtr_fractile_ensemble_pepstr_wgt",
    "fractile_value_attr": "cascade_pepstr_fractile_score"
  },
]
