#!/usr/bin/env python3
# coding=utf-8

#prerank 阶段相关队列
prerank_ensemble_sort_queues = [
  {
    "name" : "prerank_action_once_score",
    "weight" : 0.0,
    "weight_attr" : "explore_prerank_ensemble_action_once_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_action_once_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_action_once_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_action_once_raw_power_weight",
  },
  {
    "name" : "cascade_prerank_pctr",
    "weight" : 1.2,
    "weight_attr" : "explore_prerank_ensemble_prerank_pctr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_prerank_pctr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_cascade_prerank_pctr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_cascade_prerank_pctr_raw_power_weight",
  },
  {
    "name" : "cascade_prerank_pltr",
    "weight" : 1.0,
    "weight_attr" : "explore_prerank_ensemble_prerank_pltr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_prerank_pltr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_cascade_prerank_pltr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_cascade_prerank_pltr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pctr",
    "weight" : 0.1,
    "weight_attr" : "explore_prerank_ensemble_pctr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pctr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pctr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pctr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pltr",
    "weight" : 0.2,
    "weight_attr" : "explore_prerank_ensemble_pltr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pltr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pltr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pltr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pwtr",
    "weight" : 0.45,
    "weight_attr" : "explore_prerank_ensemble_pwtr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pwtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pwtr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pwtr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pftr",
    "weight" : 0.05,
    "weight_attr" : "explore_prerank_ensemble_pftr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pftr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pftr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pftr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_plvtr",
    "weight" : 0.2,
    "weight_attr" : "explore_prerank_ensemble_plvtr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_plvtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_plvtr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_plvtr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_plvtr2",
    "weight" : 0.12,
    "weight_attr" : "explore_prerank_ensemble_plvtr2_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_plvtr2_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_plvtr2_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_plvtr2_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_psvtr",
    "weight" : -0.1,
    "weight_attr" : "explore_prerank_ensemble_psvtr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_psvtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
  },
  {
    "name": "prerank_mc_ensemble_ptr",
    "weight": 0.05,
    "weight_attr": "explore_prerank_ensemble_ptr_power_weight",
    "power_weight_attr": "explore_prerank_ensemble_ptr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_ptr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_ptr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pepstr",
    "weight" : 0.3,
    "weight_attr" : "explore_prerank_ensemble_pepstr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pepstr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pepstr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pepstr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pcmtr",
    "weight" : 0.18,
    "weight_attr" : "explore_prerank_ensemble_pcmtr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pcmtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pcmtr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pcmtr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pwatch_time",
    "weight" : 0.45,
    "weight_attr" : "explore_prerank_ensemble_pwatch_time_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pwatch_time_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pwatch_time_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pwatch_time_raw_power_weight",
  },
  {
    "name": "prerank_mc_ensemble_peftr",
    "weight": 0.5,
    "weight_attr": "explore_prerank_ensemble_peftr_power_weight",
    "power_weight_attr": "explore_prerank_ensemble_peftr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_peftr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_peftr_raw_power_weight",
  },
  {
    "name": "prerank_mc_ensemble_pefctr",
    "weight": 0.5,
    "weight_attr": "explore_prerank_ensemble_pefctr_power_weight",
    "power_weight_attr": "explore_prerank_ensemble_pefctr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
  },
  {
    "name" : "prerank_mc_ensemble_pcltr",
    "weight" : 0.0,
    "weight_attr" : "explore_prerank_ensemble_pcltr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pcltr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pcltr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pcltr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pwtd",
    "weight" : 0.0,
    "weight_attr" : "explore_prerank_ensemble_pwtd_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pwtd_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pwtd_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pwtd_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pcptr",
    "weight" : 0.0,
    "weight_attr" : "explore_prerank_ensemble_pcptr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_pcptr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_pcptr_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_pcptr_raw_power_weight",
  },
  {
    "name": "prerank_mc_phtr",  #粗排 htr
    "weight": 0.0,
    "reverse_order": True,
    "weight_attr": "explore_prerank_ensemble_phtr_power_weight",
    "power_weight_attr": "explore_prerank_ensemble_phtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "rank_height_attr": "explore_prerank_ensemble_phtr_rank_height",
  },
  {
    "name" : "prerank_mc_ensemble_cascade_score",
    "weight" : 0.0,
    "weight_attr" : "explore_prerank_ensemble_cascade_score_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_cascade_score_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_prerank_ensemble_cascade_score_raw_weight",
    "raw_power_weight_attr": "explore_prerank_ensemble_cascade_score_raw_power_weight",
  },
  {
    "name" : "prerank_life_ctr",
    "weight" : 0.0,
    "weight_attr" : "explore_prerank_ensemble_life_ctr_power_weight",
    "power_weight_attr" : "explore_prerank_ensemble_life_ctr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
  }
]

pic_prerank_ensemble_sort_queues = [
  {
    "name" : "prerank_action_once_score",
    "weight" : 0.0,
    "weight_attr" : "explore_pic_prerank_ensemble_action_once_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_action_once_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_action_once_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_action_once_raw_power_weight",
  },
  {
    "name" : "cascade_prerank_pctr",
    "weight" : 1.2,
    "weight_attr" : "explore_pic_prerank_ensemble_prerank_pctr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_prerank_pctr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_cascade_prerank_pctr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_cascade_prerank_pctr_raw_power_weight",
  },
  {
    "name" : "cascade_prerank_pltr",
    "weight" : 1.0,
    "weight_attr" : "explore_pic_prerank_ensemble_prerank_pltr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_prerank_pltr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_cascade_prerank_pltr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_cascade_prerank_pltr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pctr",
    "weight" : 0.1,
    "weight_attr" : "explore_pic_prerank_ensemble_pctr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_pctr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_pctr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_pctr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pltr",
    "weight" : 0.2,
    "weight_attr" : "explore_pic_prerank_ensemble_pltr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_pltr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_pltr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_pltr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pwtr",
    "weight" : 0.45,
    "weight_attr" : "explore_pic_prerank_ensemble_pwtr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_pwtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_pwtr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_pwtr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pftr",
    "weight" : 0.05,
    "weight_attr" : "explore_pic_prerank_ensemble_pftr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_pftr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_pftr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_pftr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_plvtr",
    "weight" : 0.2,
    "weight_attr" : "explore_pic_prerank_ensemble_plvtr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_plvtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_plvtr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_plvtr_raw_power_weight",
  },
  {
    "name": "prerank_mc_ensemble_ptr",
    "weight": 0.05,
    "weight_attr": "explore_pic_prerank_ensemble_ptr_power_weight",
    "power_weight_attr": "explore_pic_prerank_ensemble_ptr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_ptr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_ptr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pepstr",
    "weight" : 0.3,
    "weight_attr" : "explore_pic_prerank_ensemble_pepstr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_pepstr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_pepstr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_pepstr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pcmtr",
    "weight" : 0.18,
    "weight_attr" : "explore_pic_prerank_ensemble_pcmtr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_pcmtr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_pcmtr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_pcmtr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pwatch_time",
    "weight" : 0.45,
    "weight_attr" : "explore_pic_prerank_ensemble_pwatch_time_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_pwatch_time_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_pwatch_time_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_pwatch_time_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_pcltr",
    "weight" : 0.0,
    "weight_attr" : "explore_pic_prerank_ensemble_pcltr_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_pcltr_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_pcltr_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_pcltr_raw_power_weight",
  },
  {
    "name" : "prerank_mc_ensemble_cascade_score",
    "weight" : 0.0,
    "weight_attr" : "explore_pic_prerank_ensemble_cascade_score_power_weight",
    "power_weight_attr" : "explore_pic_prerank_ensemble_cascade_score_power_weight",
    "temperature_attr" : "explore_prerank_ensemble_temperature",
    "raw_weight_attr": "explore_pic_prerank_ensemble_cascade_score_raw_weight",
    "raw_power_weight_attr": "explore_pic_prerank_ensemble_cascade_score_raw_power_weight",
  }
]
