#!/usr/bin/env python3
# coding=utf-8

#粗排屏队列，

#第一轮分桶排序

cluster_variant_sort_queue = [
            {
              "name": "cascade_prerank_pctr",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_prerank_pctr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_prerank_pctr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_prerank_pctr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_prerank_pctr_raw_power_weight",
            },
            {
              "name": "cascade_prerank_pltr",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_prerank_pltr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_prerank_pltr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_prerank_pltr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_prerank_pltr_raw_power_weight",
            },
            {
              "name": "cascade_prerank_prstr",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_prerank_prstr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_prerank_prstr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_prerank_prstr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_prerank_prstr_raw_power_weight",
            },
            {
              "name" : "cascade_score", # 1
              "weight" : 1.2,
              "power_weight_attr" : "explore_mc_ensemble_s1_cascade_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_cascade_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_cascade_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_cascade_score_raw_power_weight",
            },
            {
              "name" : "mc_ensemble_pctr",  # 2
              "weight" : 0.05,
              "power_weight_attr" : "explore_mc_ensemble_s1_pctr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pctr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "avg_xtr" : "explore_mc_ensemble_pctr_avg_xtr",
              "min_ratio" : "explore_mc_ensemble_pctr_min_ratio",
              "max_ratio" : "explore_mc_ensemble_pctr_max_ratio",
              "dynamic_weight" : "explore_mc_ensemble_pctr_dynamic_weight",
              "user_xtr" : "realtime_ctr",
              "raw_weight_attr": "explore_mc_ensemble_s1_pctr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pctr_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_pctr_normalize_alpha",
              "fractile_name": "mc_ensemble_pctr_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_pctr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_pctr_fractile_power_weight",
            },
            {
              "name" : "mc_ensemble_pltr", # 3
              "weight" : 0.19,
              "power_weight_attr" : "explore_mc_ensemble_s1_pltr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pltr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "avg_xtr" : "explore_mc_ensemble_pltr_avg_xtr",
              "min_ratio" : "explore_mc_ensemble_pltr_min_ratio",
              "max_ratio" : "explore_mc_ensemble_pltr_max_ratio",
              "dynamic_weight" : "explore_mc_ensemble_pltr_dynamic_weight",
              "user_xtr": "realtime_ltr",
              "raw_weight_attr": "explore_mc_ensemble_s1_pltr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pltr_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_pltr_normalize_alpha",
              "fractile_name": "mc_ensemble_pltr_fractile",
              "fractile_weight_attr": "pic_explore_mc_ensemble_pltr_fractile_weight",
              "fractile_power_weight_attr": "pic_explore_mc_ensemble_pltr_fractile_power_weight",
            },
            {
              "name" : "mc_ensemble_pwtr",  # 4
              "weight" : 0.1,
              "power_weight_attr" : "explore_mc_ensemble_s1_pwtr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pwtr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "avg_xtr" : "explore_mc_ensemble_pwtr_avg_xtr",
              "min_ratio" : "explore_mc_ensemble_pwtr_min_ratio",
              "max_ratio" : "explore_mc_ensemble_pwtr_max_ratio",
              "dynamic_weight" : "explore_mc_ensemble_pwtr_dynamic_weight",
              "user_xtr" : "realtime_wtr",
              "raw_weight_attr": "explore_mc_ensemble_s1_pwtr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pwtr_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_pwtr_normalize_alpha",
              "fractile_name": "mc_ensemble_pwtr_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_pwtr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_pwtr_fractile_power_weight",
            },
            {
              "name" : "mc_ensemble_pftr", # 5
              "weight" : 0.06,
              "power_weight_attr" : "explore_mc_ensemble_s1_pftr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pftr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "avg_xtr" : "explore_mc_ensemble_pftr_avg_xtr",
              "min_ratio" : "explore_mc_ensemble_pftr_min_ratio",
              "max_ratio" : "explore_mc_ensemble_pftr_max_ratio",
              "dynamic_weight": "explore_mc_ensemble_pftr_dynamic_weight",
              "user_xtr": "realtime_ftr",
              "raw_weight_attr": "explore_mc_ensemble_s1_pftr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pftr_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_pftr_normalize_alpha",
              "fractile_name": "mc_ensemble_pftr_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_pftr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_pftr_fractile_power_weight",
            },
            {
              "name" : "mc_ensemble_plvtr", # 7
              "weight" : 0.15,
              "power_weight_attr" : "explore_mc_ensemble_s1_plvtr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_plvtr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_plvtr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_plvtr_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_plvtr_normalize_alpha",
              "fractile_name": "mc_ensemble_plvtr_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_plvtr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_plvtr_fractile_power_weight"
            },
            {
              "name" : "mc_ensemble_plvtr2", # 8
              "weight" : 0.12,
              "power_weight_attr" : "explore_mc_ensemble_s1_plvtr2_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_plvtr2_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_plvtr2_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_plvtr2_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_plvtr2_normalize_alpha",
              "fractile_name": "mc_ensemble_plvtr2_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_plvtr2_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_plvtr2_fractile_power_weight",
            },
            {
              "name" : "mc_ensemble_psvtr",  # 9
              "weight" : -0.1,
              "power_weight_attr" : "explore_mc_ensemble_s1_psvtr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_psvtr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature"
            },
            {
              "name" : "mc_ensemble_pepstr",  # 10
              "weight" : 0.12,
              "power_weight_attr" : "explore_mc_ensemble_s1_pepstr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pepstr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pepstr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pepstr_raw_power_weight",
              "fractile_name": "mc_ensemble_pepstr_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_pepstr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_pepstr_fractile_power_weight",
            },
            {
              "name" : "mc_ensemble_pcestr",  # 11
              "weight" : 0.12,
              "power_weight_attr" : "explore_mc_ensemble_s1_pcestr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pcestr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pcestr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pcestr_raw_power_weight",
            },
            {
              "name" : "mc_ensemble_pcmtr",  # 12
              "weight" : 0.11,
              "power_weight_attr" : "explore_mc_ensemble_s1_pcmtr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pcmtr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pcmtr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pcmtr_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_pcmtr_normalize_alpha",
              "fractile_name" : "mc_ensemble_pcmtr_fractile",  # 12
              "fractile_weight_attr": "explore_mc_ensemble_s1_pcmtr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_pcmtr_fractile_power_weight",
            },
            {
              "name" : "mc_ensemble_pptime",  # 13
              "weight" : 0.3,
              "power_weight_attr" : "explore_mc_ensemble_s1_pptime_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pptime_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pptime_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pptime_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_pptime_normalize_alpha"
            },
            {
              "name" : "mc_ensemble_pwatch_time",  # 14
              "weight" : 0.32,
              "power_weight_attr" : "explore_mc_ensemble_s1_pwatch_time_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pwatch_time_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pwatch_time_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pwatch_time_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_pwatch_time_normalize_alpha",
              "fractile_name": "mc_ensemble_pwatch_time_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_pwatch_time_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_pwatch_time_fractile_power_weight",
            },
            {
              "name": "mc_ensemble_age_score",  # UNKNOWN
              "weight": 1.0,
              "weight_attr": "explore_mc_ensemble_s1_age_score_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_ensemble_peftr",  # UNKNOWN
              "weight": 0.5,
              "power_weight_attr": "explore_mc_ensemble_s1_eftr_score_power_weight",
              "weight_attr": "mc_eftr_ensemble_sort_weight_s1",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_peftr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_peftr_raw_power_weight",
              "fractile_name": "mc_ensemble_peftr_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_peftr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_peftr_fractile_power_weight",
            },
            {
              "name": "mc_ensemble_pefctr",  # UNKNOWN
              "weight": 0.5,
              "power_weight_attr": "explore_mc_ensemble_s1_efctr_score_power_weight",
              "weight_attr": "mc_efctr_ensemble_sort_weight_s1",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pefctr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pefctr_raw_power_weight",
              "fractile_name": "mc_ensemble_pefctr_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_pefctr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_pefctr_fractile_power_weight",
            },
            {
              "name": "mc_ensemble_pcptr",  # wtd队列
              "weight": 1.0,
              "power_weight_attr": "explore_mc_ensemble_s1_cascade_pcptr_power_weight",
              "weight_attr": "mc_cptr_ensemble_sort_weight_s1",
              "temperature_attr": "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_ensemble_pcltr",  #UNKNOWN
              "weight": 0.0,
              "weight_attr": "explore_mc_ensemble_s1_pcltr_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
              "variant_weight" : "explore_mc_ensemble_s1_pcltr_variant_weight",
              "avg_xtr" : "avg_cltr",
              "min_ratio" : "explore_mc_ensemble_pcltr_min_ratio",
              "max_ratio" : "explore_mc_ensemble_pcltr_max_ratio",
              "dynamic_weight" : "explore_mc_ensemble_pcltr_dynamic_weight",
              "user_xtr": "realtime_cltr",
              "raw_weight_attr": "explore_mc_ensemble_s1_pcltr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pcltr_raw_power_weight",
              "fractile_name": "mc_ensemble_pcltr_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_pcltr_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_pcltr_fractile_power_weight",
            },
            {
              "name": "cascade_pwtd",  # 完播优化队列
              "weight": 1.0,
              "power_weight_attr": "explore_mc_ensemble_s1_cascade_pwtd_power_weight",
              "weight_attr": "mc_wtd_ensemble_sort_weight_s1",
              "temperature_attr": "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_ensemble_pfptr",  #粗排播放完成度队列
              "weight": 1.0,
              "power_weight_attr": "explore_mc_ensemble_s1_pfptr_power_weight"    ,
              "weight_attr": "explore_mc_ensemble_s1_pfptr_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pfptr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pfptr_raw_power_weight",
            },
            {
              "name": "mc_ensemble_ordinal_wtd",  
              "weight": 1.0,
              "power_weight_attr": "explore_mc_ensemble_s1_ordinal_wtd_weight",
              "weight_attr": "explore_mc_ensemble_s1_ordinal_wtd_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
            },
            {
              "name": "mc_ensemble_ordinal_prob",  
              "weight": 1.0,
              "power_weight_attr": "explore_mc_ensemble_s1_ordinal_prob_weight",
              "weight_attr": "explore_mc_ensemble_s1_ordinal_prob_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
            },
            {
              "name": "cascade_corr_pctr_psvr",  #粗排 LTR
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_prerank_cascade_corr_pctr_psvr_power_weight"    ,
              "weight_attr": "explore_mc_ensemble_s1_prerank_cascade_corr_pctr_psvr_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
            },
            {
              "name": "cascade_phtr",  #粗排 htr
              "weight": 0.0,
              "reverse_order": True,
              "power_weight_attr": "explore_mc_ensemble_s1_phtr_power_weight",
              "weight_attr": "explore_mc_ensemble_s1_phtr_power_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
            },
            {
              "name": "cascade_phtr",  #粗排 htr 正序
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_phtr_in_order_power_weight",
              "weight_attr": "explore_mc_ensemble_s1_phtr_in_order_power_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature",
            },
            {
              "name": "colossus_ann_rank_score",  # colossus_ann rank score队列
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_colossus_ann_rank_power_weight",
              "weight_attr": "explore_mc_ensemble_s1_colossus_ann_rank_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_ensemble_smooth_age_score",  # smooth age score
              "weight": 0.0,
              "weight_attr": "explore_mc_ensemble_s1_smooth_age_score_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_ensemble_emp_pop_score",  # empirical popular score
              "weight": 0.0,
              "weight_attr": "explore_mc_ensemble_s1_emp_pop_score_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_htr_cost_score",  #粗排 htr 机会成本
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_phtr_cost_power_weight",
              "weight_attr": "explore_mc_ensemble_s1_phtr_cost_power_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_interact_fusion_score", #互动 action-once
              "weight": 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_interact_fusion_score_weight",
              "weight_attr": "explore_mc_ensemble_s1_interact_fusion_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_watch_time_fusion_score", #时长 action-once
              "weight": 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_watch_time_fusion_score_weight",
              "weight_attr": "explore_mc_ensemble_s1_watch_time_fusion_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature"
            },
            {
              "name" : "mc_ensemble_psvtr2",
              "reverse_order": True,
              "weight" : 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_psvtr2_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_psvtr2_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "mc_ensemble_prerank_wtd",
              "weight": 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_prerank_wtd_power_weight",
              "weight_attr": "explore_mc_ensemble_s1_prerank_wtd_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr" : "explore_mc_ensemble_s1_prerank_wtd_raw_weight",
              "raw_power_weight_attr" : "explore_mc_ensemble_s1_prerank_wtd_raw_power_weight",
            },
            {
              "name": "prerank_wltr_in_s1",
              "weight": 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_prerank_wltr_in_s1_power_weight",
              "weight_attr": "explore_mc_ensemble_s1_prerank_wltr_in_s1_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr" : "explore_mc_ensemble_s1_prerank_wltr_in_s1_raw_weight",
              "raw_power_weight_attr" : "explore_mc_ensemble_s1_prerank_wltr_in_s1_raw_power_weight",
            },
            {
              "name": "cascade_pctr_corr",
              "weight": 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_cascade_pctr_corr_power_weight",
              "weight_attr": "explore_mc_ensemble_s1_cascade_pctr_corr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr" : "explore_mc_ensemble_s1_cascade_pctr_corr_raw_weight",
              "raw_power_weight_attr" : "explore_mc_ensemble_s1_cascade_pctr_corr_raw_power_weight",
            },
            {
              "name" : "mc_ensemble_pwtd_inverse",
              "weight" : 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_pwtd_inverse_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_pwtd_inverse_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pwtd_inverse_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pwtd_inverse_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_pwtd_inverse_normalize_alpha",
              "fractile_name": "cascade_pwtd_inverse_fractile",
              "fractile_weight_attr": "explore_mc_ensemble_s1_wtd_inverse_fractile_weight",
              "fractile_power_weight_attr": "explore_mc_ensemble_s1_wtd_inverse_fractile_power_weight",
            },
            {
              "name" : "mc_ensemble_psvtr",
              "reverse_order": True,
              "weight" : 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_psvtr_v2_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_psvtr_v2_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature"
            },
            {
              "name" : "cascase_life_ctr",
              "weight" : 0.0,
              "power_weight_attr" : "explore_mc_ensemble_s1_lifetab_pctr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_lifetab_pctr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "avg_xtr" : "explore_mc_ensemble_lifetab_pctr_avg_xtr",
              "min_ratio" : "explore_mc_ensemble_lifetab_pctr_min_ratio",
              "max_ratio" : "explore_mc_ensemble_lifetab_pctr_max_ratio",
              "dynamic_weight" : "explore_mc_ensemble_lifetab_pctr_dynamic_weight",
              "user_xtr" : "realtime_ctr",
              "raw_weight_attr": "explore_mc_ensemble_s1_lifetab_pctr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_lifetab_pctr_raw_power_weight",
              "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s1_lifetab_pctr_normalize_alpha"
            },
            {
              "name": "cascade_prerank_score",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_prerank_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_prerank_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_prerank_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_prerank_score_raw_power_weight",
            },
            {
              "name": "hate_similar_score_by_mc_embedding",
              "reverse_order": True,
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_hate_similar_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_hate_similar_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_hate_similar_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_hate_similar_score_raw_power_weight",
            },
            {
              "name": "fountain_efficiency_vv",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_fountain_efficiency_vv_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_fountain_efficiency_vv_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_fountain_efficiency_vv_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_fountain_efficiency_vv_raw_power_weight",
            },
            {
              "name": "search_score",  # search_score 队列
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_search_score_rank_power_weight",
              "weight_attr": "explore_mc_ensemble_s1_search_score_rank_weight",
              "temperature_attr": "explore_mc_ensemble_s1_temperature"
            },
            {
              "name": "cascade_fc_pevr",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_fc_pevr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_fc_pevr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_fc_pevr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_fc_pevr_raw_power_weight",
            },
            {
              "name": "mc_ensemble_pevr",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_mc_ensemble_pevr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_mc_ensemble_pevr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_mc_ensemble_pevr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_mc_ensemble_pevr_raw_power_weight",
            },
            {
              "name": "social_ltv_score1",  # cascade UA队列
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_ua_ltv_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_ua_ltv_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_ua_ltv_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_ua_ltv_raw_power_weight",
            },
            {
              "name": "explore_photo_trend_score",  # 视频趋势分队列
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_trend_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_trend_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_trend_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_trend_score_raw_power_weight",
            },
            {
              "name": "cascade_update_xtr_fix_mc_s1_score",  # 视频日龄xtr校准
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_update_xtr_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_update_xtr_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_update_xtr_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_update_xtr_score_raw_power_weight",
            },
            {
              "name": "cascade_hetu_one_xtr_debias_mc_s1_score",  # 视频hetu校准
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_hetu_one_xtr_debias_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_hetu_one_xtr_debias_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_hetu_one_xtr_debias_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_hetu_one_xtr_debias_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_hetu_one_xtr_debias_score_raw_power_weight",
            },
            {
              "name": "user_group_interest_tgi_score",  # 十大人群消费TGI
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_user_group_interest_tgi_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_user_group_interest_tgi_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_user_group_interest_tgi_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_user_group_interest_tgi_score_raw_power_weight",
            },
            {
              "name": "explore_mc_bad_cover_similarity_score",  # 封面审劣质相似
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_explore_mc_bad_sense_similarity_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_explore_mc_bad_sense_similarity_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_explore_mc_bad_sense_similarity_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_explore_mc_bad_sense_similarity_score_raw_power_weight",
            },
            {
              "name": "mc_ensemble_pftr_dur_social",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_pftr_dur_power_weight_social",
              "weight_attr" : "explore_mc_ensemble_s1_pftr_dur_weight_social",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_pftr_dur_raw_weight_social",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_pftr_dur_raw_power_weight_social",
            },
            {
              "name": "intrest_adjust_score",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_intrest_adjust_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_intrest_adjust_score_power_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_intrest_adjust_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_intrest_adjust_score_raw_power_weight",
            },
            {
              "name": "user_career_interest_tagnex_tgi_score",
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_user_career_interest_tagnex_tgi_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_user_career_interest_tagnex_tgi_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_user_career_interest_tagnex_tgi_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_user_career_interest_tagnex_tgi_score_raw_power_weight",
            },
            {
              "name": "cascading_explore_gamora_interest_ptr",  # 2026-01-26 by guohao
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_cascading_explore_gamora_interest_ptr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_cascading_explore_gamora_interest_ptr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_cascading_explore_gamora_interest_ptr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_cascading_explore_gamora_interest_ptr_raw_power_weight",
            },
            {
              "name": "cascading_explore_gamora_interest_ltr", # 2026-01-26 by guohao
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_cascading_explore_gamora_interest_ltr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_cascading_explore_gamora_interest_ltr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_cascading_explore_gamora_interest_ltr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_cascading_explore_gamora_interest_ltr_raw_power_weight",
            },
            {
              "name": "user_age_interest_tagnex_tgi_score", # 2026-03-30 by wuyichun
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_user_age_interest_tagnex_tgi_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_user_age_interest_tagnex_tgi_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_user_age_interest_tagnex_tgi_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_user_age_interest_tagnex_tgi_score_raw_power_weight",
            },
            {
              "name": "photo_history_interest_score_with_mc_ctr", # 2026-04-12 by guohao
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_photo_history_interest_score_with_mc_ctr_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_photo_history_interest_score_with_mc_ctr_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_photo_history_interest_score_with_mc_ctr_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_photo_history_interest_score_with_mc_ctr_raw_power_weight",
            },
            {
              "name": "user_age_interest_tagnex_tgi_product_pxtr_score", # 2026-04-28 by wuyichun
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_user_age_interest_tagnex_tgi_product_pxtr_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_user_age_interest_tagnex_tgi_product_pxtr_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_user_age_interest_tagnex_tgi_product_pxtr_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_user_age_interest_tagnex_tgi_product_pxtr_score_raw_power_weight",
            },
            {
              "name": "user_no_bias_interest_tagnex_tgi_score", # 2026-05-09 by juyi
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_user_no_bias_interest_tagnex_tgi_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_user_no_bias_interest_tagnex_tgi_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_user_no_bias_interest_tagnex_tgi_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_user_no_bias_interest_tagnex_tgi_score_raw_power_weight",
            },
            {
              "name": "user_no_bias_interest_tagnex_tgi_product_pxtr_score", # 2026-05-09 by juyi
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_user_no_bias_interest_tagnex_tgi_product_pxtr_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_user_no_bias_interest_tagnex_tgi_product_pxtr_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_user_no_bias_interest_tagnex_tgi_product_pxtr_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_user_no_bias_interest_tagnex_tgi_product_pxtr_score_raw_power_weight",
            },
            {
              "name": "user_stage_interest_tagnex_tgi_product_pxtr_score", # 2026-05-12 by wuyichun
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_user_stage_interest_tagnex_tgi_product_pxtr_score_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_user_stage_interest_tagnex_tgi_product_pxtr_score_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_user_stage_interest_tagnex_tgi_product_pxtr_score_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_user_stage_interest_tagnex_tgi_product_pxtr_score_raw_power_weight",
            },
            {
              "name": "cascade_fc_pvtr2", # 2026-05-20 by wangyalong03
              "weight": 0.0,
              "power_weight_attr": "explore_mc_ensemble_s1_cascade_fc_pvtr2_power_weight",
              "weight_attr" : "explore_mc_ensemble_s1_cascade_fc_pvtr2_weight",
              "temperature_attr" : "explore_mc_ensemble_s1_temperature",
              "raw_weight_attr": "explore_mc_ensemble_s1_cascade_fc_pvtr2_raw_weight",
              "raw_power_weight_attr": "explore_mc_ensemble_s1_cascade_fc_pvtr2_raw_power_weight",
            }
        ]

cluster_variant_sort_weight_param_dict = {
  "ctr": "explore_mc_ensemble_s1_pctr_weight", 
  "watchtime": "explore_mc_ensemble_s1_pwtd_inverse_weight",
  "ltr": "explore_mc_ensemble_s1_pltr_weight",
  "cmtr": "explore_mc_ensemble_s1_pcmtr_weight",
  "wtr": "explore_mc_ensemble_s1_pwtr_weight",
  "cltr": "explore_mc_ensemble_s1_pcltr_weight",
  "ftr": "explore_mc_ensemble_s1_pftr_weight",
}


explore_pic_cascase_final_queue = [
  {
    "name" : "picture_mc_stage1_score",
    "weight" : 0.0,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pic_stage1_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "cascade_score",
    "weight" : 1.4,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_cascade_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_pctr",
    "weight" : 0.2,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pctr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pctr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pctr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pctr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pctr_dynamic_weight",
    "user_xtr" : "realtime_ctr",
    "raw_weight_attr": "pic_explore_mc_ensemble_pctr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pctr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pltr",
    "weight" : 0.2,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pltr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pltr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pltr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pltr_dynamic_weight",
    "user_xtr" : "realtime_ltr",
    "raw_weight_attr": "pic_explore_mc_ensemble_pltr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pltr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pwtr",
    "weight" : 0.45,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pwtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pwtr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pwtr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pwtr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pwtr_dynamic_weight",
    "user_xtr" : "realtime_wtr",
    "raw_weight_attr": "pic_explore_mc_ensemble_pwtr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pwtr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pftr",
    "weight" : 0.05,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pftr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pftr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pftr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pftr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pftr_dynamic_weight",
    "user_xtr" : "realtime_ftr",
    "raw_weight_attr": "pic_explore_mc_ensemble_pftr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pftr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pcltr",
    "weight" : 0.0,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pcltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "avg_cltr",
    "min_ratio" : "explore_mc_ensemble_pcltr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pcltr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pcltr_dynamic_weight",
    "user_xtr": "realtime_cltr",
    "raw_weight_attr": "pic_explore_mc_ensemble_pcltr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pcltr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pcmtr",
    "weight" : 0.18,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pcmtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "pic_explore_mc_ensemble_pcmtr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pcmtr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_plvtr",
    "weight" : 0.2,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_plvtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "pic_explore_mc_ensemble_plvtr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_plvtr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_plvtr2",
    "weight" : 0.12,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_plvtr2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "pic_explore_mc_ensemble_plvtr2_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_plvtr2_raw_power_weight",
  },
  {
    "name": "mc_ensemble_ptr",
    "weight": 0.05,
    "power_weight_attr": "pic_explore_mc_ensemble_s2_ptr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "pic_explore_mc_ensemble_pptr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pptr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pepstr",
    "weight" : 0.3,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pepstr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "pic_explore_mc_ensemble_pepstr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pepstr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pcestr",
    "weight" : 0.18,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pcestr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "pic_explore_mc_ensemble_pcestr_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_pcestr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pwatch_time",
    "weight" : 0.45,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pwatch_time_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "pic_explore_mc_ensemble_ppwatch_time_raw_weight",
    "raw_power_weight_attr": "pic_explore_mc_ensemble_ppwatch_time_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pptime",
    "weight" : 0.4,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_pptime_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "produce_cascade_mtctr",
    "weight": 0.0,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_produce_cascade_mtctr_score_power_weight",
    "weight_attr": "pic_explore_mc_ensemble_s2_produce_cascade_mtctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "produce_cascade_twhtr",
    "weight": 0.0,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_produce_cascade_twhtr_score_power_weight",
    "weight_attr": "pic_explore_mc_ensemble_s2_produce_cascade_twhtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "produce_cascade_mtcotr",
    "weight": 0.0,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_produce_cascade_mtcotr_score_power_weight",
    "weight_attr": "pic_explore_mc_ensemble_s2_produce_cascade_mtcotr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "produce_cascade_mtjtr",
    "weight": 0.0,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_produce_cascade_mtjtr_score_power_weight",
    "weight_attr": "pic_explore_mc_ensemble_s2_produce_cascade_mtjtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "produce_cascade_sjctr",
    "weight": 0.0,
    "power_weight_attr" : "pic_explore_mc_ensemble_s2_produce_cascade_sjctr_score_power_weight",
    "weight_attr": "pic_explore_mc_ensemble_s2_produce_cascade_sjctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "cascade_phtr",
    "weight": 0.0,
    "reverse_order": True,
    "power_weight_attr": "pic_explore_mc_ensemble_s2_phtr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  }
]
 

hot_mc_pxtr_fractile_score_queues = [
  {
    "name": "plvtr",
    "xtr_attr": "mc_ensemble_plvtr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_plvtr_wgt",
    "fractile_value_attr": "mc_ensemble_plvtr_fractile",
    "need_fractile_value_attr": "mc_ensemble_plvtr_need_fractile",
  },
  {
    "name": "pltr",
    "xtr_attr": "mc_ensemble_pltr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pltr_wgt",
    "fractile_value_attr": "mc_ensemble_pltr_fractile",
    "need_fractile_value_attr": "mc_ensemble_pltr_need_fractile",
  },
  {
    "name": "peftr",
    "xtr_attr": "mc_ensemble_peftr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_peftr_wgt",
    "fractile_value_attr": "mc_ensemble_peftr_fractile",
    "need_fractile_value_attr": "mc_ensemble_peftr_need_fractile",
  },
  {
    "name": "psvtr",
    "xtr_attr": "mc_ensemble_psvtr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_psvtr_wgt",
  },
  {
    "name": "pcmtr",
    "xtr_attr": "mc_ensemble_pcmtr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pcmtr_wgt",
    "fractile_value_attr": "mc_ensemble_pcmtr_fractile",
    "need_fractile_value_attr": "mc_ensemble_pcmtr_need_fractile",
  },
  {
    "name": "pefctr",
    "xtr_attr": "mc_ensemble_pefctr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pefctr_wgt",
    "fractile_value_attr": "mc_ensemble_pefctr_fractile",
    "need_fractile_value_attr": "mc_ensemble_pefctr_need_fractile",
  },
  {
    "name": "pctr",
    "xtr_attr": "mc_ensemble_pctr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pctr_wgt",
    "fractile_value_attr": "mc_ensemble_pctr_fractile",
    "need_fractile_value_attr": "mc_ensemble_pctr_need_fractile",
  },
  {
    "name": "pftr",
    "xtr_attr": "mc_ensemble_pftr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pftr_wgt",
    "fractile_value_attr": "mc_ensemble_pftr_fractile",
    "need_fractile_value_attr": "mc_ensemble_pftr_need_fractile",
  },
  {
    "name": "pwtr",
    "xtr_attr": "mc_ensemble_pwtr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pwtr_wgt",
    "fractile_value_attr": "mc_ensemble_pwtr_fractile",
    "need_fractile_value_attr": "mc_ensemble_pwtr_need_fractile",
  },
  {
    "name": "pcltr",
    "xtr_attr": "mc_ensemble_pcltr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pcltr_wgt",
    "fractile_value_attr": "mc_ensemble_pcltr_fractile",
    "need_fractile_value_attr": "mc_ensemble_pcltr_need_fractile",
  },
  {
    "name": "plvtr2",
    "xtr_attr": "mc_ensemble_plvtr2",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_plvtr2_wgt",
    "fractile_value_attr": "mc_ensemble_plvtr2_fractile",
    "need_fractile_value_attr": "mc_ensemble_plvtr2_need_fractile",
  },
  {
    "name": "pwatch_time",
    "xtr_attr": "mc_ensemble_pwatch_time",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pwatch_time_wgt",
    "fractile_value_attr": "mc_ensemble_pwatch_time_fractile",
    "need_fractile_value_attr": "mc_ensemble_pwatch_time_need_fractile",
  },
  {
    "name": "ptr",
    "xtr_attr": "mc_ensemble_ptr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_ptr_wgt",
  },
  {
    "name": "pepstr",
    "xtr_attr": "mc_ensemble_pepstr",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pepstr_wgt",
    "fractile_value_attr": "mc_ensemble_pepstr_fractile",
    "need_fractile_value_attr": "mc_ensemble_pepstr_need_fractile",
  },
  {
    "name": "wtd_inverse",
    "xtr_attr": "cascade_pwtd_inverse",
    "weight_attr": "hot_mc_pxtr_fractile_ensemble_pwtd_inverse_wgt",
    "fractile_value_attr": "cascade_pwtd_inverse_fractile",
    "need_fractile_value_attr": "cascade_pwtd_inverse_need_fractile",
  },
]
