#!/usr/bin/env python3
# coding=utf-8

#粗排 2 阶段相关队列

final_channel_sort_queues = [
  {
    "name" : "cascade_score",
    "weight" : 1.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "cascade_corr_pctr_psvr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_corr_pctr_psvr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_cascade_corr_pctr_psvr_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_cascade_corr_pctr_psvr_rank_cliff_threshold",
  },
  {
    "name" : "mc_ensemble_pctr",
    "weight" : 0.1,
    "power_weight_attr" : "explore_mc_ensemble_s2_pctr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pctr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pctr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pctr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pctr_dynamic_weight",
    "user_xtr" : "realtime_ctr",
    "rank_cliff_attr": "explore_mc_ensemble_pctr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pctr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pctr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pctr_raw_power_weight",
    "fractile_name": "mc_ensemble_pctr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pctr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pctr_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pctr_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_pctr_rank_cliff_threshold",
  },
  {
    "name" : "mc_ensemble_pltr",
    "weight" : 0.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_pltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pltr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pltr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pltr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pltr_dynamic_weight",
    "user_xtr" : "realtime_ltr",
    "rank_cliff_attr": "explore_mc_ensemble_pltr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pltr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pltr_rank_cliff_min",
    "score_threshold": "user_emp_ltr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pltr_raw_power_weight",
    "fractile_name": "mc_ensemble_pltr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pltr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pltr_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pltr_use_superscript_rank}}"
  },
  {
    "name" : "mc_ensemble_pwtr",
    "weight" : 0.45,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pwtr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pwtr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pwtr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pwtr_dynamic_weight",
    "user_xtr" : "realtime_wtr",
    "rank_cliff_attr": "explore_mc_ensemble_pwtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pwtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pwtr_rank_cliff_min",
    "score_threshold": "user_emp_wtr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pwtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pwtr_raw_power_weight",
    "fractile_name": "mc_ensemble_pwtr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pwtr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pwtr_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pwtr_use_superscript_rank}}"
  },
  {
    "name" : "mc_ensemble_pftr",
    "weight" : 0.05,
    "power_weight_attr" : "explore_mc_ensemble_s2_pftr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_pftr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_pftr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pftr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pftr_dynamic_weight",
    "user_xtr" : "realtime_ftr",
    "rank_cliff_attr": "explore_mc_ensemble_pftr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pftr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pftr_rank_cliff_min",
    "score_threshold": "user_emp_ftr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pftr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pftr_raw_power_weight",
    "fractile_name": "mc_ensemble_pftr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pftr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pftr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_plvtr",
    "weight" : 0.2,
    "power_weight_attr" : "explore_mc_ensemble_s2_plvtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_plvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_plvtr_raw_power_weight",
    "fractile_name": "mc_ensemble_plvtr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_plvtr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_plvtr_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_plvtr_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_plvtr_rank_cliff_threshold",
  },
  {
    "name" : "mc_ensemble_plvtr2",
    "weight" : 0.12,
    "power_weight_attr" : "explore_mc_ensemble_s2_plvtr2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_plvtr2_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_plvtr2_raw_power_weight",
    "fractile_name": "mc_ensemble_plvtr2_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_plvtr2_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_plvtr2_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_plvtr2_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_plvtr2_rank_cliff_threshold",
  },
  {
    "name" : "mc_ensemble_psvtr",
    "weight" : -0.1,
    "power_weight_attr" : "explore_mc_ensemble_s2_psvtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ensemble_ptr",
    "weight": 0.05,
    "power_weight_attr": "explore_mc_ensemble_s2_ptr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_ensemble_pptr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pptr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pptr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pptr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pptr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pepstr",
    "weight" : 0.3,
    "power_weight_attr" : "explore_mc_ensemble_s2_pepstr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pepstr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pepstr_raw_power_weight",
    "fractile_name": "mc_ensemble_pepstr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pepstr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pepstr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_pcestr",
    "weight" : 0.18,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcestr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pcestr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcestr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_pcmtr",
    "weight" : 0.18,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcmtr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_ensemble_pcmtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pcmtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pcmtr_rank_cliff_min",
    "score_threshold": "user_emp_cmtr_cas_threshold",
    "raw_weight_attr": "explore_mc_ensemble_pcmtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcmtr_raw_power_weight",
    "fractile_name" : "mc_ensemble_pcmtr_fractile",  # 12
    "fractile_weight_attr": "explore_mc_ensemble_s2_pcmtr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pcmtr_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pcmtr_use_superscript_rank}}"
  },
  {
    "name" : "mc_ensemble_pptime",
    "weight" : 0.4,
    "power_weight_attr" : "explore_mc_ensemble_s2_pptime_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_pwatch_time",
    "weight" : 0.45,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwatch_time_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_ppwatch_time_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_ppwatch_time_raw_power_weight",
    "fractile_name": "mc_ensemble_pwatch_time_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pwatch_time_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pwatch_time_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pwatch_time_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_pwatch_time_rank_cliff_threshold",
  },
  {
    "name": "mc_ensemble_peftr",
    "weight": 0.5,
    "power_weight_attr": "explore_mc_ensemble_s2_eftr_score_power_weight",
    "weight_attr": "mc_eftr_ensemble_sort_weight_s2",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_peftr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_peftr_raw_power_weight",
    "fractile_name": "mc_ensemble_peftr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_peftr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_peftr_fractile_power_weight",
  },
  {
    "name": "mc_ensemble_pefctr",
    "weight": 0.5,
    "power_weight_attr": "explore_mc_ensemble_s2_efctr_score_power_weight",
    "weight_attr": "mc_efctr_ensemble_sort_weight_s2",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_pefctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pefctr_raw_power_weight",
    "fractile_name": "mc_ensemble_pefctr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pefctr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pefctr_fractile_power_weight",
  },
  {
    "name" : "mc_ensemble_pcltr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pcltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "variant_weight" : "explore_mc_ensemble_s2_pcltr_variant_weight",
    "avg_xtr" : "avg_cltr",
    "min_ratio" : "explore_mc_ensemble_pcltr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_pcltr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_pcltr_dynamic_weight",
    "user_xtr": "realtime_cltr",
    "rank_cliff_attr": "explore_mc_ensemble_pcltr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pcltr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pcltr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_pcltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_pcltr_raw_power_weight",
    "fractile_name": "mc_ensemble_pcltr_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_pcltr_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_pcltr_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pcltr_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_pcltr_rank_cliff_threshold",
  },
  {
    "name" : "mc_ensemble_pwtd",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pwtd_power_weight",
    "weight_attr" : "mc_wtd_ensemble_sort_weight_s2",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_ensemble_pwtd_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_pwtd_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_pwtd_rank_cliff_min",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pwtd_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_pwtd_rank_cliff_threshold",
  },
  {
    "name": "mc_ensemble_pwtd_inverse", 
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_pwtd_inverse_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_pwtd_inverse_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_pwtd_inverse_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_pwtd_inverse_raw_power_weight",
    "fractile_name": "cascade_pwtd_inverse_fractile",
    "fractile_weight_attr": "explore_mc_ensemble_s2_wtd_inverse_fractile_weight",
    "fractile_power_weight_attr": "explore_mc_ensemble_s2_wtd_inverse_fractile_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pwtd_inverse_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_pwtd_inverse_rank_cliff_threshold",
  },
  {
    "name": "mc_ensemble_pfptr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_pfptr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_pfptr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_pfptr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_pfptr_raw_power_weight",
  },
  {
    "name": "mc_ensemble_ordinal_wtd",  
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_ordinal_wtd_weight",
    "weight_attr": "explore_mc_ensemble_s2_ordinal_wtd_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_ensemble_ordinal_prob",  
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_ordinal_prob_weight",
    "weight_attr": "explore_mc_ensemble_s2_ordinal_prob_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "diversity_fr",  #粗排播放完成度队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_diversity_fr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_diversity_fr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "use_new_pow_func": "explore_diversity_fr_use_new_pow_func",
    "new_pow_func_coeff": "explore_diversity_fr_new_pow_func_coeff",
    "new_pos_func_bias": "explore_diversity_fr_new_pos_func_bias"
  },
  {
    "name": "hate_fr",  #粗排topkmgs hate 队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_hate_fr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_hate_fr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "use_new_pow_func": "explore_hate_fr_use_new_pow_func",
    "new_pow_func_coeff": "explore_hate_fr_new_pow_func_coeff",
    "new_pos_func_bias": "explore_hate_fr_new_pos_func_bias"
  },
  {
    "name": "mc_ensemble_prerank_er",  #粗排 LTR
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_prerank_er_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_prerank_er_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "cascade_phtr",  #粗排 htr
    "weight": 0.0,
    "reverse_order": True,
    "power_weight_attr": "explore_mc_ensemble_s2_phtr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_phtr_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "rank_cliff_attr": "explore_mc_s2_ensemble_phtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_s2_ensemble_phtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_s2_ensemble_phtr_rank_cliff_min",
    "rank_height_attr": "explore_mc_s2_ensemble_phtr_rank_height",
  },
  {
    "name": "cascade_phtr",  #粗排 htr 正序
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_phtr_in_order_power_weight",
    "weight_attr": "explore_mc_s2_phtr_in_order_power_weight",
    "temperature_attr": "explore_mc_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_phtr_in_order_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_phtr_in_order_raw_power_weight",
    "score_threshold": "explore_mc_s2_phtr_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_phtr_in_order_rank_height",
  },
  {
    "name": "cascade_phtr",  #粗排 emp htr 正序
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_emp_phtr_in_order_power_weight",
    "weight_attr": "explore_mc_s2_emp_phtr_in_order_power_weight",
    "temperature_attr": "explore_mc_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_emp_phtr_in_order_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_emp_phtr_in_order_raw_power_weight",
    "score_threshold": "explore_mc_s2_emp_phtr_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_emp_phtr_in_order_rank_height",
  },
  {
    "name": "cascade_fc_s2_pctr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_fc_pctr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_fc_pctr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fc_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fc_pctr_raw_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_fc_pctr_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_fc_pctr_rank_cliff_threshold",
  },
  {
    "name": "cascade_fc_s2_plvtr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_fc_plvtr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_fc_plvtr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fc_plvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fc_plvtr_raw_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_fc_plvtr_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_fc_plvtr_rank_cliff_threshold",
  },
  {
    "name": "cascade_fc_s2_psvtr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_fc_psvtr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_fc_psvtr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fc_psvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fc_psvtr_raw_power_weight",
  },
  {
    "name": "cascade_fc_s2_pvtr",  #粗排播放完成度队列
    "weight": 1.0,
    "power_weight_attr": "explore_mc_ensemble_s2_fc_pvtr_power_weight"    ,
    "weight_attr": "explore_mc_ensemble_s2_fc_pvtr_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fc_pvtr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fc_pvtr_raw_power_weight",
  },
  {
    "name": "pdn_rank_score",  #pdn召回rank score队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_pdn_rank_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_pdn_rank_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "comirec_rank_score",  #comirec召回rank score队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_comirec_rank_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_comirec_rank_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "colossus_ann_rank_score",  #colossus ann召回rank score队列
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_colossus_ann_rank_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_colossus_ann_rank_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_smooth_age_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_smooth_age_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_emp_pop_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_emp_pop_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_htr_cost_score",  #粗排 htr 机会成本
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_phtr_cost_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_phtr_cost_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "global_emphtr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_global_emp_phtr_in_order_power_weight",
    "weight_attr": "explore_mc_s2_global_emp_phtr_in_order_power_weight",
    "temperature_attr": "explore_mc_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_global_emp_phtr_in_order_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_global_emp_phtr_in_order_raw_power_weight",
    "score_threshold": "explore_mc_s2_global_emp_phtr_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_global_emp_phtr_in_order_rank_height",
  },
  {
    "name": "emp_report_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_emp_report_score_in_order_power_weight",
    "weight_attr": "explore_mc_s2_emp_report_score_in_order_power_weight",
    "temperature_attr": "explore_mc_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_emp_report_score_in_order_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_emp_report_score_in_order_raw_power_weight",
    "score_threshold": "explore_mc_s2_emp_report_score_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_emp_report_score_in_order_rank_height",
  },
  {
    "name": "emp_sharpe_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_emp_sharpe_score_power_weight",
    "weight_attr": "explore_mc_s2_emp_sharpe_score_power_weight",
    "temperature_attr": "explore_mc_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_emp_sharpe_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_emp_sharpe_score_raw_power_weight",
    "score_threshold": "explore_mc_s2_emp_sharpe_score_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_emp_sharpe_score_rank_height",
  },
  {
    "name": "mc_interact_fusion_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_interact_fusion_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_interact_fusion_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_watch_time_fusion_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_watch_time_fusion_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_watch_time_fusion_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "mc_ensemble_psvtr2",
    "reverse_order": True,
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_psvtr2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_elive_ctcvr_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_elive_ctcvr_score_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_elive_ctcvr_score_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "mc_elive_ctcvr_gmv_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_elive_ctcvr_gmv_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_elive_ctcvr_gmv_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name": "produce_cascade_mtctr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_mtctr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtctr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_twhtr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_twhtr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_twhtr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_mtcotr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_mtcotr_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_csti",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_csti_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_csti_score_raw_power_weight",
  },
  {
    "name": "produce_cascade_sjctr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_produce_cascade_sjctr_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_produce_cascade_sjctr_score_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_prerank_wtd",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_prerank_wtd_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_prerank_wtd_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_prerank_wtd_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_wtd_raw_power_weight",
  },
  {
    "name" : "prerank_wltr_in_s1",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_prerank_wltr_in_s1_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_prerank_wltr_in_s1_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_prerank_wltr_in_s1_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_wltr_in_s1_raw_power_weight",
  },
  {
    "name" : "cascade_pctr_corr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_pctr_corr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_pctr_corr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_pctr_corr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_cascade_pctr_corr_raw_power_weight",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_cascade_pctr_corr_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_cascade_pctr_corr_rank_cliff_threshold",
  },
  {
    "name": "cascade_prerank_pctr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_prerank_pctr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pctr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pctr_raw_power_weight",
  },
  {
    "name": "cascade_prerank_pltr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_prerank_pltr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pltr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pltr_raw_power_weight",
  },
  {
    "name": "cascade_prerank_prstr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_prerank_prstr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_prerank_prstr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_prstr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_prstr_raw_power_weight",
  },
  {
    "name": "cover_view_predict_trans_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cover_view_predict_trans_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_cover_view_predict_trans_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "score_threshold": "explore_mc_ensemble_s2_cover_view_predict_trans_score_rank_cliff_threshold",
    "raw_weight_attr": "explore_mc_ensemble_s2_cover_view_predict_trans_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cover_view_predict_trans_score_raw_power_weight",
  },
  {
    "name": "sense_view_predict_trans_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_sense_view_predict_trans_score_weight",
    "weight_attr": "explore_mc_ensemble_s2_sense_view_predict_trans_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "score_threshold": "explore_mc_ensemble_s2_sense_view_predict_trans_score_rank_cliff_threshold",
    "raw_weight_attr": "explore_mc_ensemble_s2_sense_view_predict_trans_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_sense_view_predict_trans_score_raw_power_weight",
  },
  {
    "name": "is_user_short_develop_interest",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_user_short_develop_interest_weight",
    "weight_attr": "explore_mc_ensemble_s2_user_short_develop_interest_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "score_threshold": "explore_mc_ensemble_s2_user_short_develop_interest_rank_cliff_threshold",
    "raw_weight_attr": "explore_mc_ensemble_s2_user_short_develop_interest_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_user_short_develop_interest_raw_power_weight",
    "value_type": "int",
  },
  {
    "name": "cascading_comment_time_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_comment_time_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_comment_time_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_comment_time_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_comment_time_score_raw_power_weight",
  },
  {
    "name": "cascading_valid_play_score",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascading_valid_play_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascading_valid_play_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascading_valid_play_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascading_valid_play_score_raw_power_weight",
  },
  {
    "name": "cascading_explore_gamora_interest_ptr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_explore_gamora_interest_ptr_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_explore_gamora_interest_ptr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_explore_gamora_interest_ptr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_explore_gamora_interest_ptr_raw_power_weight",
  },
  {
    "name": "cascading_explore_gamora_interest_ltr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_explore_gamora_interest_ltr_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_explore_gamora_interest_ltr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_explore_gamora_interest_ltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_explore_gamora_interest_ltr_raw_power_weight",
  },
  {
    "name" : "mc_ensemble_psvtr",
    "reverse_order": True,
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_psvtr_v2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "cascade_pwtd",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_pwtd_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "cascase_life_ctr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_lifetab_pctr_power_weight",
    "weight_attr" : "explore_mc_ensemble_s2_lifetab_pctr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "avg_xtr" : "explore_mc_ensemble_lifetab_pctr_avg_xtr",
    "min_ratio" : "explore_mc_ensemble_lifetab_pctr_min_ratio",
    "max_ratio" : "explore_mc_ensemble_lifetab_pctr_max_ratio",
    "dynamic_weight" : "explore_mc_ensemble_lifetab_pctr_dynamic_weight",
    "user_xtr" : "realtime_ctr",
    "rank_cliff_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_lifetab_pctr_rank_cliff_min",
    "raw_weight_attr": "explore_mc_ensemble_lifetab_pctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_lifetab_pctr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_mc_ensemble_s2_lifetab_pctr_normalize_alpha"
  },
  {
    "name" : "cascade_prerank_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_prerank_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_prerank_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_prerank_score_raw_power_weight",
  },
  {
    "name" : "cascade_distill_read",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_dstill_read_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_dstill_read_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_dstill_read_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_dstill_read_raw_power_weight",
  },
  {
    "name" : "cascade_distill_finish",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_dstill_finish_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_dstill_finish_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_dstill_finish_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_dstill_finish_raw_power_weight",
  },
  {
    "name" : "cascade_distill_play_7s",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_dstill_play_7s_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_dstill_play_7s_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_dstill_play_7s_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_dstill_play_7s_raw_power_weight",
  },
  {
    "name" : "cascade_distill_play_60s",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_dstill_play_60s_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_dstill_play_60s_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_dstill_play_60s_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_dstill_play_60s_raw_power_weight",
  },
  {
    "name" : "is_same_location",
    "value_type": "int",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_same_location_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_same_location_weight",
    "raw_weight_attr": "explore_mc_ensemble_s2_same_location_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_same_location_raw_power_weight",
  },
  {
    "name" : "fountain_efficiency_vv",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_fountain_efficiency_vv_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_fountain_efficiency_vv_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_fountain_efficiency_vv_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_fountain_efficiency_vv_raw_power_weight",
  },
  {
    "name" : "social_ltv_score1",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_ua_ltv_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_ua_ltv_score_vv_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_ua_ltv_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_ua_ltv_score_raw_power_weight",
  },
  {
    "name" : "cascade_fc_pevr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_fc_pevr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_fc_pevr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_fc_pevr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_fc_pevr_raw_power_weight",
    "score_threshold": "explore_mc_s2_pevtr_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_pevtr_in_order_rank_height",
  },
  {
    "name" : "mc_ensemble_pevr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_mc_ensemble_pevr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_mc_ensemble_pevr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_mc_ensemble_pevr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_mc_ensemble_pevr_raw_power_weight",
    "score_threshold": "explore_mc_s2_mc_ensemble_pevr_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_mc_ensemble_pevr_in_order_rank_height",
  },
  {
    "name" : "cascade_explore_u2c_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_explore_u2c_score_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
  },
  {
    "name" : "explore_photo_trend_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_trend_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_trend_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_trend_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_trend_score_raw_power_weight"
  },
  {
    "name" : "cascade_upload_xtr_fix_mc_s2_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_upload_xtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_upload_xtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_upload_xtr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_upload_xtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_upload_xtr_score_raw_power_weight"
  },
  {
    "name" : "cascade_hetu_one_xtr_debias_mc_s2_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_hetu_one_xtr_debias_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_hetu_one_xtr_debias_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_hetu_one_xtr_debias_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_hetu_one_xtr_debias_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_hetu_one_xtr_debias_score_raw_power_weight"
  },
  {
    "name" : "cascade_slide_pctr_score",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_slide_pctr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_slide_pctr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_slide_pctr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_slide_pctr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_slide_pctr_score_raw_power_weight"
  },
  {
    "name": "cascade_slide_pltr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_slide_pltr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_slide_pltr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_slide_pltr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_slide_pltr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_slide_pltr_score_raw_power_weight"
  },
  {
    "name": "cascade_slide_pwtr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_slide_pwtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_slide_pwtr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_slide_pwtr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_slide_pwtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_slide_pwtr_score_raw_power_weight"
  },
  {
    "name": "cascade_slide_pcltr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_slide_pcltr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_slide_pcltr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_slide_pcltr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_slide_pcltr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_slide_pcltr_score_raw_power_weight"
  },
  {
    "name": "cascade_slide_pftr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_slide_pftr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_slide_pftr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_slide_pftr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_slide_pftr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_slide_pftr_score_raw_power_weight"
  },
  {
    "name": "cascade_slide_awesome_wtd_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_slide_awesome_wtd_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_slide_awesome_wtd_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_slide_awesome_wtd_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_slide_awesome_wtd_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_slide_awesome_wtd_score_raw_power_weight"
  },
  {
    "name": "cascade_sort_ratio_slide_pctr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pctr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pctr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pctr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pctr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pctr_score_raw_power_weight"
  },
  {
    "name": "cascade_sort_ratio_slide_pltr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pltr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pltr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pltr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pltr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pltr_score_raw_power_weight"
  },
  {
    "name": "cascade_sort_ratio_slide_pwtr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pwtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pwtr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pwtr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pwtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pwtr_score_raw_power_weight"
  },
  {
    "name": "cascade_sort_ratio_slide_pcmtr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcmtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcmtr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcmtr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcmtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcmtr_score_raw_power_weight"
  },
  {
    "name": "cascade_sort_ratio_slide_pcltr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcltr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcltr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcltr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcltr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pcltr_score_raw_power_weight"
  },
  {
    "name": "cascade_sort_ratio_slide_pftr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pftr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pftr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pftr_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pftr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_pftr_score_raw_power_weight"
  },
  {
    "name": "cascade_sort_ratio_slide_awesome_wtd_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_awesome_wtd_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_awesome_wtd_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_sort_ratio_slide_awesome_wtd_score_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_awesome_wtd_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_sort_ratio_slide_awesome_wtd_score_raw_power_weight"
  },
  {
    "name": "user_group_interest_tgi_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_user_group_interest_tgi_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_user_group_interest_tgi_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_user_group_interest_tgi_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_user_group_interest_tgi_score_raw_power_weight"
  },
  {
    "name" : "mc_ensemble_pftr",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pftr_power_weight_social",
    "weight_attr": "explore_mc_ensemble_s2_pftr_weight_social",
    "temperature_attr" : "explore_mc_ensemble_s2_pftr_temperature_social",
    "raw_weight_attr": "explore_mc_ensemble_pftr_raw_weight_social",
    "raw_power_weight_attr": "explore_mc_ensemble_pftr_raw_power_weight_social",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_pftr_use_superscript_rank}}",
    "score_threshold": "explore_mc_s2_pftr_rank_cliff_threshold",
  },
  {
    "name" : "mc_ensemble_pftr_dur_social",
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_pftr_dur_power_weight_social",
    "weight_attr": "explore_mc_ensemble_s2_pftr_dur_weight_social",
    "temperature_attr" : "explore_mc_ensemble_s2_pftr_dur_temperature_social",
    "raw_weight_attr": "explore_mc_ensemble_pftr_dur_raw_weight_social",
    "raw_power_weight_attr": "explore_mc_ensemble_pftr_dur_raw_power_weight_social",
  },
  {
    "name": "cascading_cover_htr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_raw_power_weight",
    "score_threshold": "explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_rank_height",
    "rank_cliff_attr": "explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_rank_cliff_min",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_cascade_explore_koc_cover_htr_use_superscript_rank}}",
  },
  {
    "name": "cascading_detail_htr",
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_raw_power_weight",
    "score_threshold": "explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_rank_height",
    "rank_cliff_attr": "explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_rank_cliff_min",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_cascade_explore_koc_detail_htr_use_superscript_rank}}",
  },
  {
    "name": "emp_cancel_like_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_emp_cancel_like_score_in_order_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_emp_cancel_like_score_in_order_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_emp_cancel_like_score_in_order_raw_power_weight",
    "score_threshold": "explore_mc_s2_emp_cancel_like_score_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_emp_cancel_like_score_in_order_rank_height",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_emp_cancel_like_score_use_superscript_rank}}"
  },
  {
    "name": "cascade_svtr_rid_ctr_mc_s2_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_s2_svtr_rid_ctr_score_in_order_power_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_s2_svtr_rid_ctr_score_in_order_raw_weight",
    "raw_power_weight_attr": "explore_mc_s2_svtr_rid_ctr_score_in_order_raw_power_weight",
    "score_threshold": "explore_mc_s2_svtr_rid_ctr_score_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_mc_s2_svtr_rid_ctr_score_in_order_rank_height",
    "use_superscript_rank": "{{explore_mc_ensemble_s2_svtr_rid_ctr_score_use_superscript_rank}}"
  },
  {
    "name": "user_career_interest_tagnex_tgi_score",
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_user_career_interest_tagnex_tgi_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_user_career_interest_tagnex_tgi_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_user_career_interest_tagnex_tgi_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_user_career_interest_tagnex_tgi_score_raw_power_weight"
  },
  {
    "name": "user_stage_interest_tagnex_tgi_score", # 2026-01-21 by wuyichun
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_user_stage_interest_tagnex_tgi_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_user_stage_interest_tagnex_tgi_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_user_stage_interest_tagnex_tgi_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_user_stage_interest_tagnex_tgi_score_raw_power_weight"
  },
  {
    "name": "cascade_prerank_pwtd", # 2026-02-27 by chenkai11
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pwtd_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pwtd_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pwtd_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_prerank_pwtd_raw_power_weight"
  },
  {
    "name": "cascade_rise_follow_boost_score", # 2026-03-18 by shenlei03
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_cascade_rise_follow_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_cascade_rise_follow_weight",
    "temperature_attr": "explore_mc_ensemble_s2_cascade_rise_follow_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_rise_follow_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_rise_follow_raw_pow_weight"
  },
  {
    "name": "photo_history_interest_score_with_mc_ctr", # 2026-04-12 by guohao
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_photo_history_interest_score_with_mc_ctr_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_photo_history_interest_score_with_mc_ctr_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_photo_history_interest_score_with_mc_ctr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_photo_history_interest_score_with_mc_ctr_raw_power_weight",
  },
  {
    "name": "user_age_interest_tagnex_tgi_product_pxtr_score", # 2026-04-28 by wuyichun
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_user_age_interest_tagnex_tgi_product_pxtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_user_age_interest_tagnex_tgi_product_pxtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_user_age_interest_tagnex_tgi_product_pxtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_user_age_interest_tagnex_tgi_product_pxtr_score_raw_power_weight",
  },
  {
    "name": "user_no_bias_interest_tagnex_tgi_score", # 2026-05-09 by juyi
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_user_no_bias_interest_tagnex_tgi_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_user_no_bias_interest_tagnex_tgi_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_user_no_bias_interest_tagnex_tgi_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_user_no_bias_interest_tagnex_tgi_score_raw_power_weight"
  },
  {
    "name": "user_no_bias_interest_tagnex_tgi_product_pxtr_score", # 2026-05-09 by juyi
    "weight": 0.0,
    "power_weight_attr": "explore_mc_ensemble_s2_user_no_bias_interest_tagnex_tgi_product_pxtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_user_no_bias_interest_tagnex_tgi_product_pxtr_score_weight",
    "temperature_attr": "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_user_no_bias_interest_tagnex_tgi_product_pxtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_user_no_bias_interest_tagnex_tgi_product_pxtr_score_raw_power_weight"
  },
  {
    "name": "user_stage_interest_tagnex_tgi_product_pxtr_score", # 2026-05-12 by wuyichun
    "weight": 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_user_stage_interest_tagnex_tgi_product_pxtr_score_power_weight",
    "weight_attr": "explore_mc_ensemble_s2_user_stage_interest_tagnex_tgi_product_pxtr_score_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_user_stage_interest_tagnex_tgi_product_pxtr_score_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_user_stage_interest_tagnex_tgi_product_pxtr_score_raw_power_weight",
  },
  {
    "name": "cascade_fc_pvtr2", # 2026-05-19 by wangyalong03
    "weight": 0.0,
    "weight_attr": "explore_mc_ensemble_s2_cascade_fc_pvtr2_weight",
    "power_weight_attr" : "explore_mc_ensemble_s2_cascade_fc_pvtr2_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_cascade_fc_pvtr2_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_cascade_fc_pvtr2_raw_power_weight",
  },
  {
    "name" : "cascade_debias_by_pcoc_pltr", # 2026-05-26 by liucong03
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_debias_pcoc_pltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_debias_pcoc_pltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_debias_pcoc_pltr_raw_power_weight",
  },
  {
    "name" : "cascade_debias_by_pcoc_pcltr", # 2026-05-26 by liucong03
    "weight" : 0.0,
    "power_weight_attr" : "explore_mc_ensemble_s2_debias_pcoc_pcltr_power_weight",
    "temperature_attr" : "explore_mc_ensemble_s2_temperature",
    "raw_weight_attr": "explore_mc_ensemble_s2_debias_pcoc_pcltr_raw_weight",
    "raw_power_weight_attr": "explore_mc_ensemble_s2_debias_pcoc_pcltr_raw_power_weight",
  },
]

final_channel_sort_weight_param_dict = {
  "ctr": "explore_mc_ensemble_s2_pctr_power_weight", 
  "watchtime": "explore_mc_ensemble_s2_pwtd_inverse_power_weight",
  "ltr": "explore_mc_ensemble_s2_pltr_power_weight",
  "cmtr": "explore_mc_ensemble_s2_pcmtr_power_weight",
  "wtr": "explore_mc_ensemble_s2_pwtr_power_weight",
  "cltr": "explore_mc_ensemble_s2_pcltr_power_weight",
  "ftr": "explore_mc_ensemble_s2_pftr_power_weight",
}

def add_queue_attr(queues):
  for queue in queues:
    queue_name = queue["name"]
    if "rank_alpha" not in queue:
      queue["rank_alpha"] = "explore_vrs_" + queue_name + "_" + "rank_alpha"
    if "rank_beta" not in queue:
      queue["rank_beta"] = "explore_vrs_" + queue_name + "_" + "rank_beta"
    if "rank_smooth" not in queue:
      queue["rank_smooth"] = "explore_vrs_" + queue_name + "_" + "rank_smooth"
    if "value_beta" not in queue:
      queue["value_beta"] = "explore_vrs_" + queue_name + "_" + "value_beta"
    if "value_alpha" not in queue:
      queue["value_alpha"] = "explore_vrs_" + queue_name + "_" + "value_alpha"
    if "value_omega" not in queue:
      queue["value_omega"] = "explore_vrs_" + queue_name + "_" + "value_omega"
    if "reverse_order" not in queue:
      queue["reverse_order"] = "explore_vrs_" + queue_name + "_" + "reverse_order"
    if "linear_continuous_multiplication" not in queue:
      queue["linear_continuous_multiplication"] = "explore_vrs_" + queue_name + "_" + "linear_continuous_multiplication"
    if "expand_alpha_scope" not in queue:
      queue["expand_alpha_scope"] = "explore_vrs_" + queue_name + "_" + "expand_alpha_scope"
    if "es_vrs_alpha" not in queue:
      queue["es_vrs_alpha"] = "explore_vrs_" + queue_name + "_" + "es_vrs_alpha"
    if "es_vrs_beta" not in queue:
      queue["es_vrs_beta"] = "explore_vrs_" + queue_name + "_" + "es_vrs_beta"
    if "es_vrs_omega" not in queue:
      queue["es_vrs_omega"] = "explore_vrs_" + queue_name + "_" + "es_vrs_omega"
    if "default" not in queue:
      queue["default"] = 0.0
    if "score_type" not in queue:
      queue["score_type"] = "double"
      
  return queues

def cascades2_value_and_rank_score_queues():
  queues = [
    {
      "name" : "cascade_score",
    },
    {
      "name" : "mc_ensemble_pctr",
    },
    {
      "name" : "mc_ensemble_pltr",
    },
    {
      "name" : "mc_ensemble_pwtr",
    },
    {
      "name" : "mc_ensemble_pftr",
    },
    {
      "name" : "mc_ensemble_plvtr",
    },
    {
      "name" : "mc_ensemble_plvtr2",
    },
    {
      "name" : "mc_ensemble_psvtr",
    },
    {
      "name": "mc_ensemble_ptr",
    },
    {
      "name" : "mc_ensemble_pcestr",
    },
    {
      "name" : "mc_ensemble_pcmtr",
    },
    {
      "name" : "mc_ensemble_pepstr",
    },
    {
      "name": "mc_ensemble_peftr",
    },
    {
      "name" : "mc_ensemble_pwatch_time",
    },
    {
      "name": "mc_ensemble_pefctr",
    },
    {
      "name" : "mc_ensemble_pcltr",
    },
    {
      "name" : "mc_ensemble_pwtd",
    },
    {
      "name": "mc_ensemble_pwtd_inverse", 
    },
    {
      "name": "mc_ensemble_pfptr",
    },
    {
      "name": "mc_ensemble_ordinal_wtd",  
    },
    {
      "name": "cascade_phtr",
    },
    {
      "name" : "mc_ensemble_psvtr2",
    },
    {
      "name" : "cascade_pctr_corr",
    },
    {
      "name" : "cascade_distill_read",
    },
    {
      "name" : "cascade_distill_finish",
    },
    {
      "name" : "cascade_distill_play_7s",
    },
    {
      "name" : "cascade_distill_play_60s",
    },
    {
      "name" : "fountain_efficiency_vv",
    },
    {
      "name" : "mc_s2_ensemble_pcptr",
    },
    {
      "name" : "cascade_prerank_pctr",
    },
    {
      "name" : "cascade_prerank_pltr",
    },
  ]
  queues = add_queue_attr(queues)
  return queues
