from retrieval import CommonModule

class PhotoInfoFetchingModule(CommonModule):
  def __init__(self, name: str) -> None:
    super().__init__(name)

  # explore_request_data_set_tags 的取值请参考 enum DataSetTrialTag 的定义
  # https://kdev.corp.kuaishou.com/git/community-science/kuaishou-ad-reco-base-proto/-/file-detail?branchName=master&filePath=src/main/proto/kuaishou/newsmodel/reco_base.proto&repoId=17967&repoName=kuaishou-ad-reco-base-proto
  # 默认值为 "1,6" 表示获取 DATA_SET_TAG_BASE 和 DATA_SET_TAG_7DAYS 数据集合
  def process(self):
    self.flow \
      .get_abtest_params(
        biz_name = "RECO_RPC",
        ab_params = [
          {
            "attr_name": "explore_request_data_set_tags",
            "default_value": "1,6",
            "param_name": "explore_request_data_set_tags",
            "param_type": "string",
            "report_ab_hit": "{{_ABTEST_REPORT_HIT_}}"
          },
        ],
        prioritized_suffix = "{{_ABTEST_SUFFIX_LIST_}}"
      ) \
      .get_item_attr_by_distributed_flat_index(
        photo_store_kconf_key = "reco.distributedIndex.hotPhotoInfoCommonIndex",
        use_dynamic_photo_store = True,
        photo_store_request_data_set_tags_attr = 'explore_request_data_set_tags',
        attrs = self.base_attr_config,
        additional_item_source={
          "reco_results": True,
          "common_attr": [
            "explore_recent_play_list",
            "explore_realshow_click_common_list",
            "interest_migration_pids",
            "explore_realshow_pids",
            "partial_time_based_selected_pids",
            "bs_short_view_pids",
            "standard_explore_realshow_pid_list",
            "explore_user_recent_click_list",
            "user_search_valid_play_pid_list",
            "recent_hate_pid_list",
            "explore_recent_interest_colossus_trigger_list",
            "interest_score_based_pids"
          ]
        }
      ) \
      .log_debug_info(
        item_attrs = [
          "photo_id",
          "author__id",
          "duration_ms",
          "upload_type",
          "upload_time",
          "author_age_info__age_segment",
          "is_merchant",
          "is_tnu_extend_index_photo",
          "cuckoo_info__is_cuckoo_photo",
          "percent_punish__data",
          "percent_punish__enabel_percent",
          "user_hash_tag_id",
          "photo_picture_count",
          "mmu_content_ids_33",
          "picture_type",
          "hetu_tag_level_info__hetu_cluster_id",
          "hetu_tag_level_info_v2__hetu_level_two",
          "is_hot_rank_photo",
          "data_set_tags",
          "collect_count",
          "cold_start_breakout_score",
          "audit_b_second_tag",
          "questionnaire_info__exposure_count",
          "questionnaire_info__negative_count",
          "questionnaire_info__positive_count",
          "questionnaire_info__unsure_count",
          "explore_questionnaire_info__exposure_count",
          "explore_questionnaire_info__negative_count",
          "explore_questionnaire_info__positive_count",
          "explore_questionnaire_info__unsure_count",
          "explore_punish_city",
          "explore_punish",
          "author__upload_count",
          "follow_count",
          "light_inc_photo_flag",
          "report_detail__low_report_count",
          "report_detail__total_report_count",
          "high_value_pic_flag",
          "plc_category_type"
        ],
        common_attrs = [
          "explore_request_data_set_tags"
        ],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "explore_recent_play_list",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "explore_realshow_click_common_list",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "interest_migration_pids",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "explore_realshow_pids",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "partial_time_based_selected_pids",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "bs_short_view_pids",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "standard_explore_realshow_pid_list",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "explore_user_recent_click_list",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "user_search_valid_play_pid_list",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "recent_hate_pid_list",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "explore_recent_interest_colossus_trigger_list",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      ) \
      .log_debug_info(
        item_list_from_attr = "interest_score_based_pids",
        item_attrs = [attr["name"] if not isinstance(attr, str) else attr for attr in self.base_attr_config],
        for_debug_request_only = True
      )

  @property
  def base_attr_config(self) -> list: 
    attrs = [
      "author__id",
      "cuckoo_info__is_cuckoo_photo",
      "cuckoo_info__author_type",
      "content_safety_level_with_namespace__level_hot_online",
      "percent_punish__data",
      "percent_punish__enabel_percent",
      "duration_ms",
      "upload_type",
      "upload_time",
      "photo_status",
      "is_merchant",
      "magic_face_id",
      "kuaishan_id",
      "outer_material_id",
      "topk_audit_level",
      "topk_audit_tag",
      "audit_hot_high_tag_level",
      "explore_operation_c_review_level",
      "audit_b_second_tag",
      "audit_hot_high_subdivision_level",
      "is_jianguan_risk_photo",
      "auto_audit_black_exempt_level_v1",
      "is_tnu_extend_index_photo",
      "long_term_high_level_photo",
      "photo_id",
      "dup_cluster_id",
      "pic_and_selfdup_id",
      "mmu_content_ids_3",
      "mmu_content_ids_8",
      "mmu_content_ids_9",
      "mmu_content_ids_10",
      "mmu_content_ids_14",
      "mmu_content_ids_15",
      "mmu_content_ids_16",
      "mmu_content_ids_17",
      "mmu_content_ids_33",
      "explore_stat",
      "hot_trend_generalized_info",
      "hetu_tag_level_info",
      "hetu_tag_level_info_v2",
      "hetu_tag_level_info__hetu_cluster_id",
      "hetu_tag_level_info__hetu_level_one",
      "hetu_tag_level_info__hetu_level_two",
      "hetu_tag_level_info__hetu_level_three",
      "hetu_tag_level_info__hetu_level_five",
      "hetu_tag_level_info__hetu_level_four",
      "hetu_tag_level_info__hetu_tag",
      "hetu_tag_level_info__hetu_face_id",
      "explore_stat__show_count",
      "explore_stat__real_show_count",
      "nebula_stats__real_show_count",
      "nebula_stats__like_count",
      "nebula_stats__comment_count",
      "nebula_stats__forward_count",
      "nebula_stats__follow_count",
      "nebula_stats__negative_count",
      "nebula_stats__report_count",
      "nebula_stats__short_play_count",
      "nebula_stats__view_length_sum",
      "nebula_stats__collect_count",
      "thanos_stats__real_show_count",
      "thanos_stats__like_count",
      "thanos_stats__comment_count",
      "thanos_stats__forward_count",
      "thanos_stats__follow_count",
      "thanos_stats__negative_count",
      "thanos_stats__report_count",
      "thanos_stats__short_play_count",
      "thanos_stats__view_length_sum",
      "thanos_stats__collect_count",
      "fountain_stats__real_show_count",
      "fountain_stats__like_count",
      "fountain_stats__comment_count",
      "fountain_stats__forward_count",
      "fountain_stats__follow_count",
      "fountain_stats__negative_count",
      "fountain_stats__report_count",
      "fountain_stats__short_play_count",
      "fountain_stats__view_length_sum",
      "fountain_stats__collect_count",
      "cover_origin_width",
      "cover_origin_height",
      "explore_stat__click_count",
      "explore_stat__like_count",
      "explore_stat__follow_count",
      "explore_stat__forward_count",
      "explore_stat__long_play_count",
      "explore_stat__short_play_count",
      "explore_stat__profile_enter_count",
      "explore_stat__negative_count",
      "explore_stat__comment_count",
      "explore_stat__view_length_sum",
      "explore_stat__report_detail__total_report_count",
      "explore_stat__external_download",
      "explore_stat__effective_play_count",
      "explore_stat__report_count",
      "explore_stat__collect_count",
      "report_detail__low_report_count",
      "report_detail__total_report_count",
      "live_photo_info__is_living",
      "mod",
      "tag",
      "photo_dnn_cluster_id",
      "author_high_score_v2",
      "mmu_img_cluster_v3",
      "mmu_img_cluster_v1",
      "mmu_img_cluster_v4",
      "mmu_cluster_music_id",
      "mmu_content_id",
      "ocr_cover_text_word_count",
      "music",
      "show_level_a",
      "show_level_b",
      "view_length_sum",
      "author__fans_count",
      "author__upload_count",
      "author__gender",
      "author_age_info__age_segment",
      "music_info__music_combo_id",
      "location__province_id",
      "location__city_id",
      "location__poi",
      "click_count",
      "like_count",
      "follow_count",
      "forward_count",
      "report_count",
      "click_upload_rate",
      "location",
      "author",
      "content_safety_level_with_namespace",
      "author_age_info",
      "lda_topic",
      "photo_high_end_status_bits",
      "long_term_photo",
      "user_hash_tag_id",
      "color",
      "comment_count",
      "chn",
      "height",
      "width",
      "filter",
      "infer_gender",
      "infer_year",
      "infer_gender_iter1",
      "infer_year_iter1",
      "location__community_type",
      "mmu_face_age",
      "mmu_face_gender",
      "mmu_photo_low_quality_model",
      "hetu_tag_level_info_v2__hetu_level_one",
      "hetu_tag_level_info_v2__hetu_level_two",
      "hetu_tag_level_info_v2__hetu_level_three",
      "hetu_tag_level_info_v2__hetu_tag",
      "is_high_other_photo",
      "review_pass_level_b",
      "explore_stat__report_detail__low_report_count",
      "author__explore_report_thirtyday__low_report_count",
      "sim_remove_dup_id",
      "author__explore_report_thirtyday__total_report_count",
      "title_evil_level",
      "ocr_cover_text_evil_level",
      "audit_hot_cover_level",
      "merchant_item_info__item_id_list",
      "merchant_photo_cart_relation",
      "caption_length",
      "picture_type",
      "risk_level",
      "shuffle_policy",
      "nearby_feeling",
      "photo_picture_count",
      "mmu_low_quality_model_score_40",
      "mmu_low_quality_model_score_42",
      "mmu_low_quality_model_score_46",
      "mmu_low_quality_model_score_52",
      "mmu_low_quality_model_score_63",
      "mmu_low_quality_model_score_64",
      "mmu_low_quality_model_score_90",
      "mmu_low_quality_model_score_104",
      "mmu_low_quality_model_score_123",
      "mmu_low_quality_model_score_143",
      "mmu_low_quality_model_score_145",
      "mmu_low_quality_model_score_150",
      "mmu_low_quality_model_score_151",
      "mmu_low_quality_model_score_163",
      "mmu_low_quality_model_score_164",
      "is_sirius_punish",
      "is_support_author",
      "is_big_v_white_author_photo",
      "is_hot_rank_photo",
      "data_set_tags",
      "collect_count",
      "cold_start_breakout_score",
      "enable_download",
      "questionnaire_info__exposure_count",
      "questionnaire_info__negative_count",
      "questionnaire_info__positive_count",
      "questionnaire_info__unsure_count",
      "explore_questionnaire_info__exposure_count",
      "explore_questionnaire_info__negative_count",
      "explore_questionnaire_info__positive_count",
      "explore_questionnaire_info__unsure_count",
      {"name": "explore_punish_city", "type": "int_list"},
      "explore_punish",
      "high_hot_audit_tag_v2",
      "video_quality_assessment_flag",
      "eyeshot_source",
      "audit_user_experiment_level",
      "young_inc_tags",
      "final_cross_section_first_class_id",
      "light_inc_photo_flag",
      "author__hetu_author_tag__hetu_level_one",
      "author__hetu_author_tag__hetu_level_two",
      "author__hetu_author_tag__hetu_level_three",
      "high_value_pic_flag",
      "audit_cold_review_level",
      "audit_risk_immd_tag",
      "video_cold_start_info__photo_dynamic_xtrs_str",
      "photo_category_info__ecom_intent_score",
      "data_set_tags_bit",
      "data_set_tags_bit_list",
      "magic_face_type",
      "hetu_sim_cluster_id",
      "plc_category_type",
      "mmu_repost_photo_info__is_repost_photo",
      "sirius_distribution_info__mark_cod",
      "live_photo_flag",
      "author_grade_key",
      "manjiao_markcode", # 慢脚专项，详情咨询 @liuhao07 @yangliu03 https://docs.corp.kuaishou.com/d/home/fcACmJ5D5riM4G-Av4SEwRJz2
      "photo_proinc_type",
      "secure_grading_action_code", # 安全审信号
      "author_max_item_score",
      "author_shop_score",
      "timeliness_flag",
      "coldstart_guarantee_value",
      "plc_business_type",
      "video_cold_start_info__author_tails__galaxyAuthorExpGroupInteger",
      "video_cold_start_info__author_tails__climb_retrieval_author_tail",
      "video_cold_start_info__author_tails__vcs_author_tail_161",
      "video_cold_start_info__explore_author_exp_tail",
      "author_liezhi_pic_count",
      "live_photo_duration",
      "community_survey_info__survey_title",
      "community_survey_info__cert_count",
      "community_survey_info__not_cert_count",
      "community_survey_info__uncert_count",
      "is_tv_station_bottom_bar",
      "hot_trend_generalized_info__source",
      "explore_stat__cancel_like_count",
      "interest_community_tag_id",
      "pic_good_comment_score",
      "cover_view_predict_score",
      "sense_view_predict_score",
      "cover_view_predict_score_v2",
      "sense_view_predict_score_v2",
      "pFindTotalSatisfactionScoreKV",
      "author_tail_int_index_map_34",
      "author_op_session_class",
      "explore_sid",
      "black_industry_filter__slide_recent_negative_count",
      "black_industry_filter__slide_recent_real_show_count",
      "black_industry_filter__slide_recent_report_count"
    ]
    return attrs
