ada_decay_rate: 0.99999
ada_epsilon: 1e-8
avg_decay_rate: 0.999993
back_propagate_input: true
embedding:
  create_threshold: 0
  initial_g2sum: 3
  initial_range: 1e-4
  learning_rate: 0.05
  slots_config:
  - common: false
    dim: 64
    dtype: float32
    expand: 1
    input_name: photo_id
    sized: true
    slots: '1016'
  - common: false
    dim: 64
    dtype: float32
    expand: 1
    input_name: photo_emb
    sized: true
    slots: '4103'
  - common: false
    dim: 2
    dtype: float32
    expand: 1
    input_name: photo_quality
    sized: true
    slots: '4104'
  - common: false
    dim: 1
    dtype: float32
    expand: 1
    input_name: last_step
    sized: true
    slots: '4003'
  - common: false
    dim: 1
    dtype: float32
    expand: 1
    input_name: ave_step
    sized: true
    slots: '4004'
  - common: false
    dim: 64
    dtype: float32
    expand: 1
    input_name: photo_author_id
    sized: true
    slots: '1026'
  - common: false
    dim: 64
    dtype: float32
    expand: 1
    input_name: photo_author_id_v2
    sized: true
    slots: '4200'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_fans_count
    sized: true
    slots: '1047'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_fans_count_2
    sized: true
    slots: '1048'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_upload_count
    sized: true
    slots: '1075'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_upload_count_2
    sized: true
    slots: '1076'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_click_count
    sized: true
    slots: '1077'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_click_count_2
    sized: true
    slots: '1078'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_like_count
    sized: true
    slots: '1079'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_like_count_2
    sized: true
    slots: '1080'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_follow_count
    sized: true
    slots: '1081'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_follow_count_2
    sized: true
    slots: '1082'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_long_view_count
    sized: true
    slots: '1083'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_long_view_count_2
    sized: true
    slots: '1084'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_emp_ctr
    sized: true
    slots: '1085'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_emp_ltr
    sized: true
    slots: '1086'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_emp_wtr
    sized: true
    slots: '1087'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_emp_lvtr
    sized: true
    slots: '1088'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_emp_svtr
    sized: true
    slots: '1089'
  - common: false
    dim: 16
    dtype: float32
    expand: 1
    input_name: photo_author_emp_watch_time
    sized: true
    slots: '1090'
  version_aware: true
  weight_bounds:
  - -10
  - 10
extra_params: []
extra_preds: user_emb colossus_playtime
global_init_range: 0.2
graph: ../conf/graph.pb
graph_output_labels:
- Identity_9:0
- Identity_29:0
- Identity_4:0
- Identity_24:0
- Identity_5:0
- Identity_6:0
- Identity_17:0
- Select_4:0
- Identity_11:0
- Identity_14:0
- Identity_2:0
- Select_11:0
- Identity_18:0
- Identity_25:0
- Identity_8:0
- Identity:0
- Identity_21:0
- Identity_7:0
- Identity_26:0
- Identity_13:0
- Identity_10:0
- Identity_12:0
- Identity_20:0
- Identity_15:0
- Identity_23:0
- Identity_27:0
- Identity_3:0
- Identity_22:0
- Identity_1:0
- Identity_16:0
graph_q_valid:
  all_evtr: Select_5:0
  all_lvtr: Select_5:0
  all_svr: Select_5:0
  cmef: Maximum_1:0
  cmtr: Select_15:0
  coltr: Select_17:0
  dtr: Select_16:0
  epst: Maximum_1:0
  ftr: Select_13:0
  ftr_os: Select_14:0
  hot_lvtr: Minimum:0
  htr: Select_18:0
  live: Identity_19:0
  ltr: Maximum_1:0
  mcp_match: Select_1:0
  ptr: Maximum_1:0
  scale_vtr: Maximum:0
  setr: Maximum:0
  setr2: Identity_28:0
  thanos_cmef: Select_1:0
  thanos_dfvtr: mul_2:0
  thanos_etcm: Select_1:0
  thanos_evtr: mul:0
  thanos_ftr: Select_1:0
  thanos_ltr: Select_1:0
  thanos_lvtr: mul_1:0
  thanos_svr: Select_1:0
  thanos_wtr: Select_1:0
  vtr: Identity_30:0
  wtr: Select_12:0
graph_targets:
- opt
graph_tensor_mapping:
  photo_top_layer: Tile_3:0
hyperparameter_kconf: null
input_type: 3
learning_rate: 5.0e-06
mom_decay_rate: 0.999
output_hidden_units: update_input continue_normlized_input slide_embedding slide_wide
  watch_time_wide position_weight_input
param:
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: label_embedding_matrix
  rown: 3
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: completion_embedding_matrix
  rown: 11
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: dense1/kernel
  rown: 192
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: dense1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 1
  name: dense2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: dense2/bias
  rank: 1
  rown: 1
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: add_pos/position_embedding
  rown: 1
  scale_by_rown: true
- coln: 256
  dims:
  - 1
  - 4
  - 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: special_token
  rown: 1
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: num_blocks_0/atten/rms_norm/scale
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_0/atten/self_attention/dense/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_0/atten/self_attention/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_0/atten/self_attention/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_0/atten/self_attention/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_0/atten/self_attention/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_0/atten/self_attention/dense_2/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: num_blocks_0/ffn/rms_norm/scale
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_0/ffn/multihead_attention/conv1d/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_0/ffn/multihead_attention/conv1d/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_0/ffn/multihead_attention/conv1d_1/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_0/ffn/multihead_attention/conv1d_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: num_blocks_1/atten/rms_norm/scale
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_1/atten/self_attention/dense/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_1/atten/self_attention/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_1/atten/self_attention/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_1/atten/self_attention/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_1/atten/self_attention/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_1/atten/self_attention/dense_2/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: num_blocks_1/ffn/rms_norm/scale
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_1/ffn/multihead_attention/conv1d/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_1/ffn/multihead_attention/conv1d/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_1/ffn/multihead_attention/conv1d_1/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_1/ffn/multihead_attention/conv1d_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: num_blocks_2/atten/rms_norm/scale
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_2/atten/self_attention/dense/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_2/atten/self_attention/dense/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_2/atten/self_attention/dense_1/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_2/atten/self_attention/dense_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_2/atten/self_attention/dense_2/kernel
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_2/atten/self_attention/dense_2/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 1
  init_range: 0
  name: num_blocks_2/ffn/rms_norm/scale
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_2/ffn/multihead_attention/conv1d/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_2/ffn/multihead_attention/conv1d/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 4096
  dims:
  - 1
  - 64
  - 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: num_blocks_2/ffn/multihead_attention/conv1d_1/kernel
  rown: 1
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: num_blocks_2/ffn/multihead_attention/conv1d_1/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: photo_quality_tower_mlp/photo_quality_tower_mlp_0/kernel
  rown: 416
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: photo_quality_tower_mlp/photo_quality_tower_mlp_0/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: photo_quality_tower_mlp/photo_quality_tower_mlp_final/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: photo_quality_tower_mlp/photo_quality_tower_mlp_final/bias
  rank: 1
  rown: 64
  scale_by_rown: true
- coln: 256
  dtype: float32
  init_mean: 0
  init_range: 1
  name: photo_cover_tower_mlp/photo_cover_tower_mlp_0/kernel
  rown: 416
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: photo_cover_tower_mlp/photo_cover_tower_mlp_0/bias
  rank: 1
  rown: 256
  scale_by_rown: true
- coln: 64
  dtype: float32
  init_mean: 0
  init_range: 1
  name: photo_cover_tower_mlp/photo_cover_tower_mlp_final/kernel
  rown: 256
  scale_by_rown: true
- coln: 1
  dtype: float32
  init_mean: 0
  init_range: 0
  name: photo_cover_tower_mlp/photo_cover_tower_mlp_final/bias
  rank: 1
  rown: 64
  scale_by_rown: true
q_names: photo_top_layer
step_placeholder: step:0
summary:
- len: 1912
  name: base_summary
- len: 2072
  name: stub_summary
summary_decay_rate: 0.999999
summary_init_n: 1e4
summary_init_squared_sum: 1e4
summary_squared_sum_epsilon: 1e-4
test_layers_at_joining: join join_forward update update_forward
test_layers_at_updating: update update_forward
test_mode: false
train_layers_at_joining: join
train_layers_at_updating: update
vec_input:
- common: false
  dim: 1000
  name: colossus_play_time_list
- common: false
  dim: 1000
  name: colossus_label_list
- common: false
  dim: 1000
  name: colossus_duration_list
- common: false
  dim: 1000
  name: colossus_channel_list
