---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiaotian.
--- DateTime: 2021-11-01 11:21
---
function Intersection(t1, t2)
    for k, v1 in pairs(t1) do
        for k, v2 in pairs(t2) do
            if v1 == v2 then
                return true
            end
        end
    end
    return false
end

function post_score_fast_adjust()
    local last_page_hetu_one = last_page_hetu_one_total and last_page_hetu_one_total or {}
    local last_page_hetu_two = last_page_hetu_two_total and last_page_hetu_two_total or {}
    local last_page_hetu_three = last_page_hetu_three_total and last_page_hetu_three_total or {}
    local last_page_hetu_tag = last_page_hetu_tag_total and last_page_hetu_tag_total or {}

    local hetu_level_one_v2 = hetu_level_one_v2 and hetu_level_one_v2 or {}
    local hetu_level_two_v2 = hetu_level_two_v2 and hetu_level_two_v2 or {}
    local hetu_level_three_v2 = hetu_level_three_v2 and hetu_level_three_v2 or {}
    local hetu_tag_v2 = hetu_tag_v2 and hetu_tag_v2 or {}
    local normalized_item_seq = 1.0
    if (item_seq_current ~= nil and item_seq_current >= 0) then
        normalized_item_seq = 1.0 / (item_seq_current + 10)
    end
    local score_current = normalized_item_seq

    if #last_page_hetu_tag > 0 and #hetu_tag_v2 > 0  and Intersection(last_page_hetu_tag, hetu_tag_v2) then
        score_current = score_current * fountian_last_page_hetu_tag_boost
    end
    if #last_page_hetu_three > 0 and #hetu_level_three_v2 > 0  and Intersection(last_page_hetu_three, hetu_level_three_v2) then
        score_current = score_current * fountian_last_page_hetu_three_boost
        return score_current
    end
    if #last_page_hetu_two > 0 and #hetu_level_two_v2 > 0  and Intersection(last_page_hetu_two, hetu_level_two_v2) then
        score_current = score_current * fountian_last_page_hetu_two_boost
        return score_current
    end
    if #last_page_hetu_one > 0 and #hetu_level_one_v2 > 0  and Intersection(last_page_hetu_one, hetu_level_one_v2) then
        score_current = score_current * fountian_last_page_hetu_one_boost
        return score_current
    end
    return score_current
end


