from ranking import CommonModule

class LaLtrModule(CommonModule):
  def __init__(self, name: str) -> None:
    super().__init__(name)

  def user_feature(self):
    features = [
      "uId",
      "dId",
      "uTrueNewUser",
      "uLogin",
      "uFollowCount",
      "uFansCount",
      "uUploadCount",
      "uUploadRate",
      "uRiskLevel",
      "uNebula",
      "uClientId",
      "uVisitMod",
      "uVisitNet",
      "uVisitChannel",
      "uClickPids",
      "uLikePids",
      "uFollowAids",
      "uCityId",
      "uProvinceId",
      "uGender",
      "uInferGender",
      "uTrueGender",
      "uBasicGender",
      "uPromGender",
      "uInferYear",
      "uTrueYear",
      "uBasicAge",
      "hourOfDay",
      "dayOfWeek",
      "uAppList",
      "uCityLevelNew",
      "uIsDouyin",
      "uIsLowActiveUser",
      "uFindUserActiveDegree",
      "uExploreActiveDays",
      "uIsExploreLaUser",
      "uClickPidsV1",
      "uClickPidsV1Hetu1",
      "uClickPidsV1Hetu2",
      "uLikePidsV1Hetu1",
      "uLikePidsV1Hetu2",
      "ufollowAidsV1Hetu1",
      "ufollowAidsV1Hetu2",
      "uViewPidListV1_LEN",
      "uViewPidListV1",
      "uViewAidListV1",
      "uEffectiveViewLabelListV1",
      "uLongViewLabelListV1",
      "uShortViewLabelListV1",
      "uViewHetu1ListV1",
      "uViewHetu2ListV1",
      "uNetwork",
      "uLongTermV4Hetu1",
      "uLongTermV4Hetu2",
      "uLongTermV4Hetu3",
      "uRealShowNoActionPids",
      "uRealShowNoActionPids_LEN",
      "uRealShowNoActionAids",
      "uRealshowNoActionHetu1",
      "uRealshowNoActionHetu2",
      "uRealshowNoActionHetu3",
      "uRealshowNoActionHetuTag"
    ]
    for key in ["uHotShow", "uHotClick", "uHotLike", "uHotFollow", "uHotHate"]:
      for suffix in ["5m", "1h", "1d", "100n", "1000n"]:
        features.append(key + suffix)
    for key in ["1", "2", "3"]:
      features.append("uLongTermHetuLevel" + key + "topN")
      features.append("uLongTermHetuLevel" + key + "Legal")
    return features

  def photo_features(self):
    features = [
      {"name": "photo_id", "as": "pId"},
      {"name": "author__id", "as": "aId"},
      "pPctr",
      "pPltr",
      "pPwtr",
      "pPftr",
      "pPhtr",
      "pPlvtr",
      "pPsvtr",
      "pPvtr",
      "pPptr",
      "pPcmtr",
      "pPdctr",
      "pPcmef",
      "pPfvtr",
      "pPdtr",
      "pPfrScore1",
      "pPfrScore2",
      "pPfrScore1_v1",
      "pPfrScore2_v1",
      "pPevtr",
      "pPfetr",
      "pPfountainEff",
      "pMcPctr",
      "pMcPltr",
      "pMcPwtr",
      "pMcPlvtr",
      "pMcPsvtr",
      "pEmpCtr",
      "pEmpLtr",
      "pEmpWtr",
      "pEmpFtr",
      "pEmpPtr",
      "pEmpCmtr",
      "pEmpHtr",
      "pEmpWatchTime",
      "pPctrFractile",
      "pPctrFractileOri",
      "pPltrFractile",
      "pPlvtrFractile",
      "pPsvrFractile",
      "pPwtrFractile",
      "pPftrFractile",
      "pPptrFractile",
      "pPhtrFractile",
      "pPepstrFractile",
      "pPcmtrFractile",
      "pPcmefFractile",
      "pPFrScore1Fractile",
      "pPFrScore2Fractile",
      "pPfetrFractile",
      "pPFountainEffFractile",
      {"name": "author__fans_count", "as": "aFansCount"},
      "pAgeHour",
      {"name": "duration_ms", "as": "pDurationMs"},
      "pUploadType",
      {"name": "explore_stat__show_count", "as": "pHotShow"},
      {"name": "explore_stat__click_count", "as": "pHotClick"},
      {"name": "explore_stat__like_count", "as": "pHotLike"},
      {"name": "explore_stat__follow_count", "as": "pHotFollow"},
      {"name": "explore_stat__negative_count", "as": "pHotHate"},
      {"name": "explore_stat__report_detail__total_report_count", "as": "pHotReport"},
      "pHotExptag",
      {"name": "click_upload_rate", "as": "pUploadRate"},
      "pCityId",
      "pProvinceId",
      {"name": "infer_gender", "as": "pInferGender"},
      {"name": "infer_gender_iter1", "as": "pInferGender1"},
      {"name": "infer_year", "as": "pInferYear"},
      {"name": "infer_year_iter1", "as": "pInferYear1"},
      {"name": "photo_high_end_status_bits", "as": "pHighEndBits"},
      "pPhotoPoi",
      {"name": "location__community_type", "as": "pPhotoCommunityType"},
      {"name": "photo_dnn_cluster_id", "as": "pDnnClusterId"},
      "pMusic",
      {"name": "explore_stat__external_download", "as": "pHotDownload"},
      "pHetuTagLevel1",
      "pHetuTagLevel2",
      "pHetuTagLevel3",
      "pHetuClusterId",
      {"name": "hetu_tag_level_info__hetu_level_four", "as": "pHetuTagLevel4"},
      "pHetuTagLevel5",
      "pHetuTagLevelTag",
      "pHetuTagFaceId",
      {"name": "author_high_score_v2", "as": "pAuthorHighScoreV2"},
      {"name": "content_safety_level_with_namespace__level_hot_online", "as": "pLevelHotOnline"},
      "pAuditHotHighTagLevel",
      {"name": "mmu_img_cluster_v1", "as": "pMmuImgClusterV1"},
      "pMmuImgClusterV3",
      "pMmuImgClusterV4",
      "pPhotoIndex",
      "pRealShowIndex",
      {"name": "user_hash_tag_id", "as": "pHashTagIdList"}
    ]
    for key in ["Hetu1", "Hetu2", "Hetu3", "Hetu4", "Hetu5", "HetuTag"]:
      for suffix in ["100n", "1000n"]:
        features.append("pShortStatShow" + key + suffix)
        features.append("pShortStatClick" + key + suffix)
        features.append("pShortStatClickRate" + key + suffix)    
    return features

  def process(self) -> None:
    self.flow \
      .if_("enable_explore_fullrank_multitask_ltr_predict == 1") \
        .explore_common_user_feature_enricher(
          user_info_attr = "user_info_ptr",
          user_uid_attr = "uId",
          user_did_attr = "dId",
          user_click_pids_attr = "uClickPidsV1",
          user_like_pids_attr = "uLikePids",
          user_follow_pids_attr = "uFollowAids",
          user_exp_follow_count_attr = "uFollowCount",
          user_upload_cnt_attr = "uUploadCount",
          user_view_aids_attr = "uViewAidListV1",
          user_fans_cnt_attr = "uFansCount",
          user_city_attr = "uCityId",
          user_province_attr = "uProvinceId",
          user_gender_attr = "uGender",
          user_infer_year_int_attr = "uInferYear",
          user_basic_age_attr = "uBasicAge",
          user_visit_net_attr = "uNetwork",
          user_city_level_attr = "uCityLevelNew",
          user_is_douyin_attr = "uIsDouyin",
          user_longterm_hetu_level1_attr = "uLongTermHetuLevel1topN",
          user_longterm_hetu_level2_attr = "uLongTermHetuLevel2topN",
          user_longterm_hetu_level3_attr = "uLongTermHetuLevel3topN",
          user_click_pids_hetu1_attr = "uClickPidsV1Hetu1",
          user_click_pids_hetu2_attr = "uClickPidsV1Hetu2",
          user_effective_view_label_attr = "uEffectiveViewLabelListV1",
          user_view_hetu1_attr = "uViewHetu1ListV1",
          user_view_hetu2_attr = "uViewHetu2ListV1",
          user_view_pids_attr = "uViewPidListV1",
          user_follow_pids_hetu1_attr = "ufollowAidsV1Hetu1",
          user_follow_pids_hetu2_attr = "ufollowAidsV1Hetu2",
          user_ture_gender_attr = "uTrueGender",
          user_short_view_label_attr = "uShortViewLabelListV1",
          user_no_action_hetu_tag_attr =  "uRealshowNoActionHetuTag",
          user_no_action_hetu1_attr = "uRealshowNoActionHetu1",
          user_no_action_hetu2_attr =  "uRealshowNoActionHetu2",
          user_no_action_hetu3_attr =  "uRealshowNoActionHetu3",
          user_no_action_pid_attr = "uRealShowNoActionPids",
          user_no_action_aid_attr =  "uRealShowNoActionAids",
          user_long_view_label_attr = "uLongViewLabelListV1",
          user_like_pids_hetu1_attr =  "uLikePidsV1Hetu1",
          user_like_pids_hetu2_attr = "uLikePidsV1Hetu2",
          user_low_active_attr = "uIsExploreLaUser",
          user_active_days_attr = "uExploreActiveDays"
        ) \
        .explore_consume_time_ltr_attr(
          user_info_attr = "user_info_ptr",
          item_attrs = [
            "upload_time",
            "explore_stat__report_detail__total_report_count",
            "explore_stat__show_count",
            "hetu_tag_level_info__hetu_level_one",
            "hetu_tag_level_info__hetu_level_two",
            "hetu_tag_level_info__hetu_level_three",
            "hetu_tag_level_info__hetu_level_four",
            "hetu_tag_level_info__hetu_level_five",
            "hetu_tag_level_info__hetu_tag",
            "hetu_tag_level_info__hetu_face_id",
            "pctr",
            "corr_pctr",
            "pltr",
            "plvtr",
            "psvr",
            "pwtr",
            "pftr",
            "pptr",
            "phtr",
            "pepstr",
            "pcmtr",
            "pcmef",
            "fr_score1",
            "fr_score2",
            "fetr",
            "fountain_eff"
          ],
          consume_time_ltr_need_long_action_list = "{{explore_multitask_ltr_need_long_action_list_new}}",
          long_action_list_click_length = "{{explore_multitask_ltr_long_action_list_click_length}}",
          long_action_list_action_length = "{{explore_multitask_ltr_long_action_list_action_length}}",
          consume_time_view_list_length = "{{explore_multitask_time_view_list_length}}",
          user_feature = self.user_feature()
        ) \
        .delegate_enrich(
          kess_service = "{{explore_multitask_ltr_predict_service}}",
          recv_item_attrs = [
            {"name":"pfstr", "as":"multitask_ltr_pfstr"},
            {"name":"pwtd", "as":"multitask_ltr_pwtd"},
            {"name":"pcvtr", "as":"multitask_ltr_pcvtr"},
            {"name":"pctr", "as":"multitask_ltr_pctr"}
          ],
          timeout_ms = 100,
          send_item_attrs = self.photo_features(),
          send_common_attrs = self.user_feature(),
          partition_size = "{{explore_multitask_ltr_predict_partition_size}}"
        ) \
      .end_()
