DEFAULT_COMMON_ATTRS = [
  "user_pic_interest_hetu_distr_str",  # 先知使用，之后会删掉
  "mc_s1_cluster_id", # 先知使用
  "mc_s1_cluster_cnt" # 先知使用
]

DEFAULT_ITEM_ATTRS = [
  "author__id",
  "upload_time",
  "click_count",
  "like_count",
  "follow_count",
  "forward_count",
  "comment_count",
  "width",
  "height",
  "color",
  "duration_ms",
  "mod",
  "chn",
  "filter",
  "music",
  "explore_stat",
  "hot_trend_generalized_info",
  "hetu_tag_level_info",
  "hetu_tag_level_info_v2",
  "nearby_feeling",
  "empirical_ctr",
  "empirical_ltr",
  "empirical_wtr",
  "empirical_ftr",
  "empirical_lvtr",
  "empirical_svtr",
  "empirical_ptr",
  "empirical_htr",
  "empirical_cmtr",
  "cascade_pctr",
  "cascade_pltr",
  "cascade_pwtr",
  "cascade_plvtr",
  "cascade_plvtr2",
  "cascade_psvtr",
  "cascade_ptr",
  "cascade_pwatch_time",
  "cascade_pepstr",
  "cascade_pcestr",
  "cascade_pcmtr",
  "cascade_plivingtr",
  "cascade_pcltr",
  "cascade_pdtr",
  "cascade_pcptr",
  "pctr",
  "pltr",
  "pwtr",
  "pcmtr",
  "pptr",
  "pcmef",
  "phtr",
  "pevtr",
  "fr_score1",
  "fr_score2",
  "pepstr",
  "pdtr",
  "pcltr",
  "fetr",
  "pftr",
  "psvr",
  "retr_rank",
  "awesome_wtd",
  "original_explore_fr_ensemble_score",
  "explore_fr_pxtr_absolute_score",
  "prerank_ctr",
  "prerank_ltr",
  "prerank_wtd",
  "pctr_index",
  "plvtr_index",
  "pvtr_index",
  "pltr_index",
  "pftr_index",
  "pwtr_index",
  "pesptr_index",
  "psvr_index"
]


BACKUP_COMMON_ATTRS = [
  "cascade_output_item_key_list",
  "cascade_input_item_key_list",
  "ranking_pos_sample_list",
  "rerank_cltr_adjust_ratio_attr",
  "rerank_cmef_adjust_ratio_attr",
  "rerank_cmtr_adjust_ratio_attr",
  "rerank_ctr_adjust_ratio_attr",
  "rerank_duration_adjust_ratio_attr",
  "rerank_ensemble_score_adjust_ratio_attr",
  "rerank_epstr_adjust_ratio_attr",
  "rerank_fetr_adjust_ratio_attr",
  "rerank_fountain_eff_adjust_ratio_attr",
  "rerank_fr_score1_adjust_ratio_attr",
  "rerank_fr_score2_adjust_ratio_attr",
  "rerank_ftr_adjust_ratio_attr",
  "rerank_l2r_score_adjust_ratio_attr",
  "rerank_ltr_adjust_ratio_attr",
  "rerank_ptr_adjust_ratio_attr",
  "rerank_wtr_adjust_ratio_attr",
  "user_pic_interest_hetu_distr_str",  # 先知使用，之后会删掉
  "mc_s1_cluster_id", # 先知使用
  "mc_s1_cluster_cnt" # 先知使用
]

BACKUP_ITEM_ATTRS = [
  "pliving_ctr",
  "pliving_wtr",
  "author",
  "author__gender",
  "author_age_info",
  "chn",
  "click_count",
  "color",
  "comment_count",
  "content_safety_level_with_namespace",
  "explore_stat",
  "filter",
  "forward_count",
  "height",
  "hetu_tag_level_info",
  "hetu_tag_level_info_v2",
  "hot_trend_generalized_info",
  "lda_topic",
  "like_count",
  "location",
  "mmu_cluster_music_id",
  "mmu_content_id",
  "mmu_face_age",
  "mmu_face_gender",
  "mod",
  "music_info__music_combo_id",
  "nearby_feeling",
  "ocr_cover_text_word_count",
  "report_count",
  "show_level_b",
  "tag",
  "view_length_sum",
  "width",
  "retr_rank",
  "original_explore_fr_ensemble_score",
  "explore_fr_pxtr_absolute_score",
  "pctr_index",
  "plvtr_index",
  "pvtr_index",
  "pltr_index",
  "pftr_index",
  "pwtr_index",
  "pesptr_index",
  "psvr_index"
]

TRACEBACK_ITEM_ATTRS = [
  "i2i_retr__trigger_pid"
]
