#!/usr/bin/env python3
# coding=utf-8


fullrank_ensemble_queues = [
  {
    "name": "fullrank_min_act_rank_reci",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_min_act_rank_reci",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_min_act_rank_reci",
    "raw_weight_attr": "fountain_fullrank_ensemble_min_act_rank_reci_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_min_act_rank_reci_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_sim_evtr_v2_multi_pfintr",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_evtr_v2_multi_pfintr",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_evtr_v2_multi_pfintr",
  },
  {
    "name": "fullrank_hate_similary_score",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_hate_similary_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_hate_similary_score",
  },
  {
    "name": "fullrank_sim_click_score",
    "weight": 0.5,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_click_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_click_score",
    "smooth_attr": "fountain_fullrank_ensemble_vv_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_click_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_click_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_click_raw_value_fusion_type",
    "raw_diff_threshold_attr": "fountain_fullrank_ensemble_click_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_click_raw_score_alpha",
    "fractile_value_attr": "fullrank_sim_click_score_fractile_score",
    "fractile_weight_attr": "fountain_fullrank_ensemble_click_fractile_weight",
    "fractile_pow_weight_attr": "fountain_fullrank_ensemble_click_fractile_pow_weight", 
    "queue_head_boost_coef": "fountain_fullrank_ensemble_click_head_boost_coef",
    "queue_tail_discount_coef": "fountain_fullrank_ensemble_click_tail_discount_coef",
    "enable_queue_head_boost": "fountain_fullrank_ensemble_click_enable_queue_head_boost",
    "enable_queue_tail_discount": "fountain_fullrank_ensemble_click_enable_queue_tail_discount"
  },
  {
    "name": "fullrank_sim_like_score",
    "weight": 0.5,
    "weight_attr": "xlife_fountain_ensemble_power_weight_fullrank_like_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "xlife_fountain_ensemble_power_weight_fullrank_like_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_like_raw_weight_attr",
    "raw_pow_weight_attr": "xlife_fountain_fullrank_ensemble_like_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_like_raw_value_fusion_type",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_like_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_like_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_like_que_cliff_ratio",
    "score_threshold": "fountain_fullrank_ensemble_like_que_cliff_score_threshold",
    "queue_head_boost_coef": "fountain_fullrank_ensemble_like_head_boost_coef",
    "queue_tail_discount_coef": "fountain_fullrank_ensemble_like_tail_discount_coef",
    "enable_queue_head_boost": "fountain_fullrank_ensemble_like_enable_queue_head_boost",
    "enable_queue_tail_discount": "fountain_fullrank_ensemble_like_enable_queue_tail_discount"
  },
  {
    "name": "fullrank_sim_follow_score",
    "weight": 0.7,
    "weight_attr": "xlife_fountain_ensemble_power_weight_fullrank_follow_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "xlife_fountain_ensemble_power_weight_fullrank_follow_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_follow_raw_weight_attr",
    "raw_pow_weight_attr": "xlife_fountain_fullrank_ensemble_follow_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_follow_raw_value_fusion_type",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_follow_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_follow_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_follow_que_cliff_ratio",
    "score_threshold": "fountain_fullrank_ensemble_follow_que_cliff_score_threshold",
    "use_min_rank": True,
    "queue_head_boost_coef": "fountain_fullrank_ensemble_follow_head_boost_coef",
    "queue_tail_discount_coef": "fountain_fullrank_ensemble_follow_tail_discount_coef",
    "enable_queue_head_boost": "fountain_fullrank_ensemble_follow_enable_queue_head_boost",
    "enable_queue_tail_discount": "fountain_fullrank_ensemble_follow_enable_queue_tail_discount"
  },
  {
    "name": "fullrank_sim_longview_score_no_bias",
    "weight": 0.55,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_longview_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_longview_score",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
  },
  {
    "name": "fullrank_sim_pwatchtime_no_bias",
    "weight":  1.2,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pvtr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pvtr_score",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pvtr_score_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pvtr_score_raw_pow_weight_attr",
    "fractile_value_attr": "fullrank_sim_pwatchtime_no_bias_fractile_score",
    "fractile_weight_attr": "fountain_fullrank_ensemble_pwatchtime_no_bias_fractile_weight",
    "fractile_pow_weight_attr": "fountain_fullrank_ensemble_pwatchtime_no_bias_fractile_pow_weight",
    "queue_head_boost_coef": "fountain_fullrank_ensemble_pwatchtime_head_boost_coef",
    "queue_tail_discount_coef": "fountain_fullrank_ensemble_pwatchtime_tail_discount_coef",
    "enable_queue_head_boost": "fountain_fullrank_ensemble_pwatchtime_enable_queue_head_boost",
    "enable_queue_tail_discount": "fountain_fullrank_ensemble_pwatchtime_enable_queue_tail_discount"
  },
  {
    "name": "fullrank_sim_phtr",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_weight_fullrank_phtr",
    "reverse_order": True,
    "temperature_attr": "fountain_fullrank_ensemble_trivial_temperature_attr",
  },
  {
    "name": "fullrank_sim_phtr",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_phtr_in_order_score",
    "temperature_attr": "fountain_fullrank_ensemble_trivial_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_phtr_in_order_score",
    "rank_cliff_attr": "fountain_fullrank_ensemble_hate_rank_cliff_attr",
    "rank_cliff_ratio_attr": "fountain_fullrank_ensemble_hate_rank_cliff_ratio_attr",
    "rank_height_attr": "fountain_fullrank_ensemble_hate_rank_height_attr",
    "cliff_score_bias_attr": "fountain_fullrank_ensemble_hate_cliff_score_bias_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_htr_raw_weight",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_htr_raw_pow_weight",
    "score_threshold": "fountain_fullrank_ensemble_htr_que_cliff_score_threshold"
  },
  {
    "name": "fullrank_sim_pcmtr",
    "weight":  0.42,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pcmtr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pcmtr_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_comment_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_comment_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_comment_raw_value_fusion_type",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_comment_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_comment_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_pcmtr_que_cliff_ratio",
    "score_threshold": "fountain_fullrank_ensemble_pcmtr_que_cliff_score_threshold",
    "use_min_rank": True
  },
  {
    "name": "fullrank_sim_pptr",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pptr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pptr_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pptr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pptr_raw_pow_weight_attr",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_pptr_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pptr_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_pptr_que_cliff_ratio",
    "score_threshold": "fountain_fullrank_ensemble_pptr_que_cliff_score_threshold"
  },
  {
    "name": "fullrank_sim_out_pctr",
    "weight":  0.64,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_out_ctr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_out_ctr_score",
    "raw_weight_attr": "fountain_fullrank_ensemble_out_ctr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_out_ctr_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_sim_pepstr",
    "weight":  0.42,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pepstr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pepstr_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pepstr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pepstr_raw_pow_weight_attr",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_pepstr_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pepstr_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_pepstr_que_cliff_ratio",
    "fractile_value_attr": "fullrank_sim_pepstr_fractile_score",
    "fractile_weight_attr": "fountain_fullrank_ensemble_pepstr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_fullrank_ensemble_pepstr_fractile_pow_weight",
    "use_min_rank": True
  },
  {
    "name": "fullrank_sim_pfintr",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pfintr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pfintr_score",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pfintr_raw_weight_attr",
    "raw_pow_weight_attr": "xlife_fountain_fullrank_ensemble_pfintr_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_pfintr_raw_value_fusion_type",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_pfintr_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pfintr_raw_score_alpha",
    "queue_head_boost_coef": "fountain_fullrank_ensemble_pfintr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_fullrank_ensemble_pfintr_tail_discount_coef",
    "enable_queue_head_boost": "fountain_fullrank_ensemble_pfintr_enable_queue_head_boost",
    "enable_queue_tail_discount": "fountain_fullrank_ensemble_pfintr_enable_queue_tail_discount"
  },
  {
    "name": "fullrank_sim_pcpr",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pcpr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pcpr_score",
    "raw_weight_attr": "fountain_fullrank_ensemble_pcpr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pcpr_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_pcpr_raw_value_fusion_type",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_pcpr_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pcpr_raw_score_alpha"
  },
  {
    "name": "fullrank_sim_playtime_finish",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_playtime_finish_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_playtime_finish_score",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_playtime_finish_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_playtime_finish_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_sim_ordinal_playtime",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_ordinal_playtime_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_ordinal_playtime_score",
    "raw_weight_attr": "fountain_fullrank_ordinal_playtime_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ordinal_playtime_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_sim_evtr_playtime",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_evtr_playtime_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_evtr_playtime_score",
    "raw_weight_attr": "fountain_fullrank_evtr_playtime_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_evtr_playtime_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_sim_evtr_duration",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_evtr_duration_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_evtr_duration_score",
    "raw_weight_attr": "fountain_fullrank_evtr_duration_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_evtr_duration_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_sim_wtd_duration",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_wtd_duration_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_wtd_duration_score",
    "raw_weight_attr": "fountain_fullrank_wtd_duration_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_wtd_duration_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_sim_pwtd_v2_playtime",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pwtd_v2_playtime_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pwtd_v2_playtime_score",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
  },
  {
    "name": "fullrank_sim_pcltr",
    "weight":  0.0,
    "weight_attr": "xlife_fountain_ensemble_power_weight_fullrank_pcltr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "xlife_fountain_ensemble_power_weight_fullrank_pcltr_score",
    "variant_weight": "fountain_ensemble_variant_weight_fullrank_pcltr_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "xlife_fountain_fullrank_ensemble_pcltr_raw_weight_attr",
    "raw_pow_weight_attr": "xlife_fountain_fullrank_ensemble_pcltr_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_pcltr_raw_value_fusion_type",
    "raw_diff_threshold_attr": "fountain_fullrank_ensemble_pcltr_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pcltr_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_pcltr_que_cliff_ratio",
    "score_threshold": "fountain_fullrank_ensemble_pcltr_que_cliff_score_threshold",
    "fractile_value_attr": "fullrank_sim_pcltr_fractile_score",
    "fractile_weight_attr": "fountain_fullrank_ensemble_pcltr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_fullrank_ensemble_pcltr_fractile_pow_weight",
  },
  # 左滑进个人页
  {
    "name": "fullrank_sim_lstr",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_lstr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_lstr_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_plstr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_plstr_raw_pow_weight_attr",
    "raw_diff_threshold_attr": "fountain_fullrank_ensemble_plstr_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_lstr_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_lstr_que_cliff_ratio",
    "score_threshold": "fountain_fullrank_ensemble_lstr_que_cliff_score_threshold",
    "use_min_rank": True
  },
  {
    "name": "fullrank_sim_psvr",
    "weight":  0.35,
    "weight_attr": "fountain_ensemble_weight_fullrank_pthanos_svr",
    "reverse_order": True,
    "temperature_attr": "fountain_fullrank_ensemble_trivial_temperature_attr",
    "power_weight_attr": "fountain_ensemble_weight_fullrank_pthanos_svr_reverse",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_psvr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_psvr_raw_pow_weight_attr",
    "fractile_value_attr": "fullrank_sim_psvr_fractile_score",
    "fractile_weight_attr": "fountain_fullrank_ensemble_psvr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_fullrank_ensemble_psvr_fractile_pow_weight",
  },
  {
    "name": "fullrank_sim_psvr",
    "weight": -0.35,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_svr_in_order_score",
    "temperature_attr": "fountain_fullrank_ensemble_trivial_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_svr_in_order_score",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
  },
  {
    "name": "fullrank_sim_pcmef",
    "weight":  0.54,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_cmef_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_cmef_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pcmef_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pcmef_raw_pow_weight_attr",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_pcmef_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pcmef_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_pcmef_que_cliff_ratio",
    "use_min_rank": True
  },
  {
    "name": "fullrank_ltr_score",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_ltr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_ltr_score",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_ltr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_ltr_raw_pow_weight_attr",
    "fractile_value_attr": "fullrank_sim_pl2r_fractile_score",
    "fractile_weight_attr": "fountain_fullrank_ensemble_pl2r_fractile_weight",
    "fractile_pow_weight_attr": "fountain_fullrank_ensemble_pl2r_fractile_pow_weight",
  },
  {
    "name": "fullrank_ltr_v4_fountain_finish_rate",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_ltr_v4_fountain_finish_rate",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_ltr_v4_fountain_finish_rate",
    "smooth_attr": "fountain_fullrank_ensemble_vv_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_finish_rate_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_finish_rate_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_ltr_v4_fountain_next",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_ltr_v4_next",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_ltr_v4_next",
    "smooth_attr": "fountain_fullrank_ensemble_vv_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_next_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_next_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_ltr_v4_fountain_reward",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_ltr_v4_reward",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_ltr_v4_reward",
  },
  {
    "name": "fullrank_detail_new_pevtr_v2",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_weight_fullrank_detail_new_pevtr_v2",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_weight_fullrank_detail_new_pevtr_v2",
    "smooth_attr": "fountain_fullrank_ensemble_vv_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pevtr_v2_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pevtr_v2_raw_pow_weight_attr",
    "raw_diff_threshold_attr": "fountain_fullrank_ensemble_pevtr_v2_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pevtr_v2_raw_score_alpha",
    "fractile_value_attr": "fullrank_sim_pevtr_fractile_score",
    "fractile_weight_attr": "fountain_fullrank_ensemble_pevtr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_fullrank_ensemble_pevtr_fractile_pow_weight",
  },
  {
    "name": "fullrank_ori_pswptr",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_weight_fullrank_ori_pswptr",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_weight_fullrank_ori_pswptr",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pswptr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pswptr_raw_pow_weight_attr",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_pswptr_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pswptr_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_pswptr_que_cliff_ratio"
  },
  {
    "name": "fullrank_sim_pvtr_multi_pwtr",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pvtr_multi_pwtr",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pvtr_multi_pwtr",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_follow_raw_diff_threshold_attr"
  },
  {
    "name": "fullrank_sim_pvtr_multi_pptr",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_pvtr_multi_pptr",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_pvtr_multi_pptr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pvtr_multi_pptr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pvtr_multi_pptr_raw_pow_weight_attr",
  },
  {
    "name": "comment_ltr",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_weight_comment_ltr",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_weight_comment_ltr",
  },
  {
    "name": "fountain_splash_slide",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_fountain_splash_slide",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fountain_splash_slide",
    "raw_weight_attr": "fountain_fullrank_ensemble_splash_slide_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_splash_slide_raw_pow_weight_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_splash_slide_raw_score_alpha"
  },
  {
    "name": "fullrank_cl_tran_score",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_cl_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_cl_score"
  },
  {
    "name": "fullrank_cl_score",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_cl_score_ori",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_cl_score_ori"
  },
  {
    "name": "fullrank_cl_play_time",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_cl_play_time",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_cl_play_time"
  },
  {
    "name": "fullrank_act_ctr",
    "power_weight_attr": "fountain_ensemble_weight_fullrank_act_ctr",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_weight_fullrank_act_ctr",
    "raw_weight_attr": "fountain_fullrank_ensemble_act_ctr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_act_ctr_raw_pow_weight_attr",
  },
  {
    "name": "fullrank_act_wtd",
    "power_weight_attr": "fountain_ensemble_weight_fullrank_act_wtd",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_weight_fullrank_act_wtd",
    "raw_weight_attr": "fountain_fullrank_ensemble_act_wtd_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_act_wtd_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_act_wtd_raw_value_fusion_type",
    "raw_diff_threshold_attr" : "fountain_fullrank_ensemble_act_wtd_raw_diff_threshold_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_act_wtd_raw_score_alpha"
  },
  {
    "name": "fullrank_sim_plvtr",
    "power_weight_attr": "fountain_ensemble_weight_fullrank_sim_plvtr",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_weight_fullrank_sim_plvtr",
    "smooth_attr": "fountain_fullrank_ensemble_vv_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_plvtr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_plvtr_raw_pow_weight_attr",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_plvtr_raw_score_alpha",
    "fractile_value_attr": "fullrank_sim_plvtr_fractile_score",
    "fractile_weight_attr": "fountain_fullrank_ensemble_plvtr_fractile_weight",
    "fractile_pow_weight_attr": "fountain_fullrank_ensemble_plvtr_fractile_pow_weight",
    "queue_head_boost_coef": "fountain_fullrank_ensemble_plvtr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_fullrank_ensemble_plvtr_tail_discount_coef",
    "enable_queue_head_boost": "fountain_fullrank_ensemble_plvtr_enable_queue_head_boost",
    "enable_queue_tail_discount": "fountain_fullrank_ensemble_plvtr_enable_queue_tail_discount"
  },
  {
    "name": "fullrank_trans_pvtr_score",
    "power_weight_attr": "fountain_ensemble_weight_fullrank_trans_pvtr_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_weight_fullrank_trans_pvtr_score",
  },
  {
    "name": "duration_ms",
    "power_weight_attr": "fountain_ensemble_weight_duration_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_weight_duration_score",
    "smooth_attr": "fountain_fullrank_ensemble_watchtime_smooth_attr",
  },
  {
    "name": "fullrank_sim_pftr",
    "power_weight_attr": "fountain_ensemble_weight_forward_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "weight": 0,
    "weight_attr": "fountain_ensemble_weight_forward_score",
    "smooth_attr": "fountain_fullrank_ensemble_interact_smooth_attr",
    "raw_weight_attr": "fountain_fullrank_ensemble_pftr_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_pftr_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_pftr_raw_value_fusion_type",
    "raw_score_alpha_attr": "fountain_fullrank_ensemble_pftr_raw_score_alpha",
    "que_cliff_ratio_attr": "fountain_fullrank_ensemble_pftr_que_cliff_ratio",
    "score_threshold": "fountain_fullrank_ensemble_pftr_que_cliff_score_threshold",
    "queue_head_boost_coef": "fountain_fullrank_ensemble_pftr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_fullrank_ensemble_pftr_tail_discount_coef",
    "enable_queue_head_boost": "fountain_fullrank_ensemble_pftr_enable_queue_head_boost",
    "enable_queue_tail_discount": "fountain_fullrank_ensemble_pftr_enable_queue_tail_discount"
  },
  {
    "name": "fullrank_sim_lsst",
    "weight":  0.0,
    "weight_attr": "fountain_ensemble_power_weight_fullrank_lsst_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_fullrank_lsst_score",
  },
  {
    "name": "fullrank_distill_rerank_score",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_distill_rerank_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_distill_rerank_score",
    "raw_weight_attr": "fountain_fullrank_ensemble_distill_rerank_score_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_distill_rerank_score_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_distill_rerank_score_raw_value_fusion_type",
  },
  {
    "name": "fullrank_evtr_distill_score",
    "weight": 0.0,
    "weight_attr": "fountain_ensemble_power_weight_evtr_distill_score",
    "temperature_attr": "fountain_fullrank_ensemble_temperature_attr",
    "power_weight_attr": "fountain_ensemble_power_weight_evtr_distill_score",
    "raw_weight_attr": "fountain_fullrank_ensemble_evtr_distill_score_raw_weight_attr",
    "raw_pow_weight_attr": "fountain_fullrank_ensemble_evtr_distill_score_raw_pow_weight_attr",
    "raw_value_fusion_type": "fountain_fullrank_ensemble_evtr_distill_score_raw_value_fusion_type",
  }
]

fullrank_ensemble_filter_queues = [
  {
    "name": "fullrank_sim_out_pctr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_out_pctr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_out_pctr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_out_pctr"
  },
  {
    "name": "fullrank_sim_pltr",
    "weight_attr": "xlife_fountain_ensemble_filter_weight_fullrank_pltr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pltr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pltr"
  },
  {
    "name": "fullrank_sim_pwtr",
    "weight_attr": "xlife_fountain_ensemble_filter_weight_fullrank_pwtr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pwtr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pwtr"
  },
  {
    "name": "fullrank_sim_pftr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pftr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pftr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pftr"
  },
  {
    "name": "fullrank_sim_psvr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_psvr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_psvr",
    "reverse_order": True,
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_psvr"
  },
  {
    "name": "fullrank_sim_plvtr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_plvtr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_plvtr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_plvtr"
  },
  {
    "name": "fullrank_sim_pcmtr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pcmtr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pcmtr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pcmtr"
  },
  {
    "name": "fullrank_sim_pptr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pptr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pptr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pptr"
  },
  {
    "name": "fullrank_sim_pcmef",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pcmef",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pcmef",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pcmef"
  },
  {
    "name": "fullrank_sim_phtr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_phtr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_phtr",
    "reverse_order": True,
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_phtr"
  },
  {
    "name": "fullrank_sim_pevtr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pevtr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pevtr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pevtr"
  },
  {
    "name": "fullrank_sim_pvtr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pvtr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pvtr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pvtr"
  },
  {
    "name": "fullrank_sim_pepstr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pepstr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pepstr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pepstr"
  },
  {
    "name": "fullrank_sim_pfintr",
    "weight_attr": "xlife_fountain_ensemble_filter_weight_fullrank_pfintr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pfintr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pfintr"
  },
  {
    "name": "fullrank_sim_pcltr",
    "weight_attr": "xlife_fountain_ensemble_filter_weight_fullrank_pcltr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pcltr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pcltr"
  },
  {
    "name": "fullrank_sim_pcpr",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pcpr",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pcpr",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pcpr"
  },
  {
    "name": "fullrank_detail_new_pevtr_v2",
    "weight_attr": "fountain_ensemble_filter_weight_fullrank_pevtr_v2",
    "tail_ratio_attr": "fountain_ensemble_filter_tail_ratio_fullrank_pevtr_v2",
    "global_quantile_value_attr": "fountain_ensemble_filter_global_quantile_value_fullrank_pevtr_v2"
  }
]

