#!/usr/bin/env python3
# coding=utf-8

#精排 ensemble_sort 队列

#图文队列
picture_queues = [
  {
    "name": "is_picture",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_picture_weight",
    "queue_pow_t": "explore_is_picture_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
]

#多样性队列
diversity_queues = [
  {
    "name": "diversity_fr",
    "weight": 0.0,
    "power_weight_attr": "xlife_diversity_fr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "use_new_pow_func": "xlife_diversity_fr_use_new_pow_func",
    "new_pow_func_coeff": "xlife_diversity_fr_new_pow_func_coeff",
    "new_pos_func_bias": "xlife_diversity_fr_new_pos_func_bias",
    "queue_pow_t": "explore_diversity_fr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_diversity_smooth",
  },
  {
    "name": "diversity_fr_ranking",
    "weight": 0.0,
    "power_weight_attr": "diversity_fr_ranking_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "use_new_pow_func": "explore_diversity_fr_ranking_use_new_pow_func",
    "new_pow_func_coeff": "explore_diversity_fr_ranking_new_pow_func_coeff",
    "new_pos_func_bias": "explore_diversity_fr_ranking_new_pos_func_bias",
    "queue_pow_t": "explore_diversity_fr_ranking_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_diversity_smooth",
  },
  {
    "name": "fr_mmu_embedding_score",
    "weight": 0.0,
    "power_weight_attr": "hot_user_expected_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fr_mmu_embedding_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_diversity_smooth",
  },
  {
    "name": "fr_mc_embedding_score",
    "weight": 0.0,
    "power_weight_attr": "hot_user_unexpected_score_weight_new",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fr_mc_embedding_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_diversity_smooth",
  },
  {
    "name": "hate_cover_similar_score",
    "weight": 0.0,
    "power_weight_attr": "hate_fr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_hate_fr_queue_pow_t",
    "raw_weight_attr": "explore_hate_fr_raw_weight",
    "raw_power_weight_attr": "explore_hate_fr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_diversity_smooth",
    "score_threshold": "explore_ensemble_hate_similar_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_hate_similar_rank_cliff_height",
  },
  {
    "name": "longterm_cluster_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_longterm_cluster_score_in_order_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fr_longterm_cluster_score_in_order_weight",
    "raw_weight_attr": "explore_fr_longterm_cluster_score_in_order_raw_weight",
    "raw_power_weight_attr": "explore_fr_longterm_cluster_score_in_order_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_htr_smooth",
  },
  {
    "name": "fr_first_page_adjust_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_first_page_adjust_score_in_order_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fr_first_page_adjust_score_in_order_weight",
    "raw_weight_attr": "explore_fr_first_page_adjust_score_in_order_raw_weight",
    "raw_power_weight_attr": "explore_fr_first_page_adjust_score_in_order_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_htr_smooth",
  },
  {
    "name": "interest_migration_photo_coef",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_interest_migration_coef_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fr_interest_migration_coef_weight",
    "raw_weight_attr": "explore_fr_interest_migration_coef_raw_weight",
    "raw_power_weight_attr": "explore_fr_interest_migration_coef_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_htr_smooth",
  },
  {
    "name": "long_term_nature_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_long_term_nature_score_power_weight",
    "weight_attr" : "explore_fr_long_term_nature_score_weight",
    "temperature_attr" : "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_long_term_nature_score_raw_weight",
    "raw_power_weight_attr": "explore_fr_long_term_nature_score_raw_power_weight",
  },
  {
    "name": "life_fr_hetu_one_reshaping_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_hetu1_reshaping_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fr_hetu1_reshaping_score_weight",
    "raw_weight_attr": "explore_fr_hetu1_reshaping_score_raw_weight",
    "raw_power_weight_attr": "explore_fr_hetu1_reshaping_score_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_htr_smooth",
  },
] 

#时长队列
time_queues = [
  {
    "name": "duration_ms",
    "value_type": "int",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_weight_duration_ms",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_duration_ms_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "score_psvr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_psvr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_score_psvr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_score_psvr_raw_weight",
    "raw_power_weight_attr": "life_fr_score_psvr_raw_power_weight",
    "raw_score_min_val_attr": "life_fr_score_psvr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_psvr_raw_score_max_val",
  },
  {
    "name": "ann_hetu_lvtr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_ann_hetu_lvtr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_ann_hetu_lvtr_score_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_ann_hetu_lvtr_score_raw_weight",
    "raw_power_weight_attr": "life_fr_ann_hetu_lvtr_score_raw_power_weight",
    "raw_score_min_val_attr": "life_fr_ann_hetu_lvtr_score_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_ann_hetu_lvtr_score_raw_score_max_val",
  },
  {
    "name": "xlife_vqvae_interest_score",
    "weight": 0.0,
    "power_weight_attr": "life_ensemble_power_weight_vqvae_interest_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_vqvae_interest_score_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_vqvae_interest_score_raw_weight",
    "raw_power_weight_attr": "life_fr_vqvae_interest_score_raw_power_weight",
    "raw_score_min_val_attr": "life_fr_vqvae_interest_score_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_vqvae_interest_score_raw_score_max_val",
  },
  {
    "name": "xlife_ctr_ltr_model_score",
    "weight": 0.0,
    "power_weight_attr": "life_ensemble_power_weight_ctr_ltr_model_pred",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_ctr_ltr_model_pred_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_ctr_ltr_model_pred_raw_weight",
    "raw_power_weight_attr": "life_fr_ctr_ltr_model_pred_raw_power_weight",
  },
  {
    "name": "xlife_mmoe_macr_pctr_model_score",
    "weight": 0.0,
    "power_weight_attr": "life_ensemble_power_weight_mmoe_macr_model_pctr_pred",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_mmoe_macr_model_pctr_pred_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_mmoe_macr_model_pctr_pred_raw_weight",
    "raw_power_weight_attr": "life_fr_mmoe_macr_model_pctr_pred_raw_power_weight",
  },
  {
    "name": "xlife_mmoe_macr_pltr_model_score",
    "weight": 0.0,
    "power_weight_attr": "life_ensemble_power_weight_mmoe_macr_model_pltr_pred",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_mmoe_macr_model_pltr_pred_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_mmoe_macr_model_pltr_pred_raw_weight",
    "raw_power_weight_attr": "life_fr_mmoe_macr_model_pltr_pred_raw_power_weight",
  },
  {
    "name": "xlife_mmoe_macr_pwtr_model_score",
    "weight": 0.0,
    "power_weight_attr": "life_ensemble_power_weight_mmoe_macr_model_pwtr_pred",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_mmoe_macr_model_pwtr_pred_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_mmoe_macr_model_pwtr_pred_raw_weight",
    "raw_power_weight_attr": "life_fr_mmoe_macr_model_pwtr_pred_raw_power_weight",
  },
  {
    "name": "xlife_pantheon_model_score",
    "weight": 0.0,
    "power_weight_attr": "life_ensemble_power_weight_pantheon_model_pred",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_pantheon_model_pred_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_pantheon_model_pred_raw_weight",
    "raw_power_weight_attr": "life_fr_pantheon_model_pred_raw_power_weight",
  },
  {
    "name": "corr_pctr_psvr",
    "weight": 0.0,
    "power_weight_attr": "life_ensemble_power_weight_fullrank_corr_pctr_psvr",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_fr_score_corr_pctr_psvr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_score_corr_pctr_psvr_raw_weight",
    "raw_power_weight_attr": "life_fr_score_corr_pctr_psvr_raw_power_weight",
  },
  {
    "name": "pevtr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pevtr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_pevtr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "raw_weight_attr": "life_fr_score_pevtr_raw_weight",
    "raw_power_weight_attr": "life_fr_score_pevtr_raw_power_weight",
  },
  {
    "name": "dis_fr_score1",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_dis_fr_score1_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_fr_score1_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_fr_score1_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_fr_score1_rank_cliff_min",
    "queue_pow_t": "explore_dis_fr_score1_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "dis_fr_score2",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_dis_fr_score2_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_fr_score2_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_fr_score2_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_fr_score2_rank_cliff_min",
    "queue_pow_t": "explore_dis_fr_score2_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "fr_score1",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_fr_score1_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_fr_score1_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_fr_score1_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_fr_score1_rank_cliff_min",
    "queue_pow_t": "explore_fr_score1_queue_pow_t",
    "raw_weight_attr": "explore_fr_score1_raw_weight",
    "raw_power_weight_attr": "explore_fr_score1_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score1_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "value_seq_fusion_status_attr": "explore_fr_score1_value_seq_fusion_status_attr",
    "fractile_name": "fr_ensemble_fr_score1_fractile",
    "fractile_weight_attr": "explore_fr_score1_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_score1_fractile_power_weight", 
    "queue_head_boost_coef": "explore_fr_score1_head_boost_coef",
    "queue_tail_discount_coef": "explore_fr_score1_tail_discount_coef",
    "raw_score_min_val_attr": "life_fr_score1_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score1_raw_score_max_val",
  },
  {
    "name": "fr_score2",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_fr_score2_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_fr_score2_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_fr_score2_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_fr_score2_rank_cliff_min",
    "queue_pow_t": "explore_fr_score2_queue_pow_t",
    "raw_weight_attr": "explore_fr_score2_raw_weight",
    "raw_power_weight_attr": "explore_fr_score2_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score2_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "value_seq_fusion_status_attr": "explore_fr_score2_value_seq_fusion_status_attr",
    "fractile_name": "fr_ensemble_fr_score2_fractile",
    "fractile_weight_attr": "explore_fr_score2_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_score2_fractile_power_weight",
    "queue_head_boost_coef": "explore_fr_score2_head_boost_coef",
    "queue_tail_discount_coef": "explore_fr_score2_tail_discount_coef",
    "raw_score_min_val_attr": "life_fr_score2_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score2_raw_score_max_val",
  },
  {
    "name": "score_pepstr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pepstr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_score_pepstr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pepstr_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pepstr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "value_seq_fusion_status_attr": "explore_fr_score_pepstr_value_seq_fusion_status_attr",
  },
  {
    "name": "corr_fetr",
    "weight": 0.0,
    "power_weight_attr": "hot_fountain_fetr_weight_push",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_pfetr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pfetr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pfetr_rank_cliff_min",
    "queue_pow_t": "explore_corr_fetr_queue_pow_t",
    "score_threshold": "explore_ensemble_corr_fetr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_corr_fetr_rank_height",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "fractile_name": "fr_ensemble_pfetr_fractile",
    "fractile_weight_attr": "explore_fr_pfetr_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_pfetr_fractile_power_weight",  
  },
  {
    "name": "corr_fountain_eff",
    "weight": 0.0,
    "power_weight_attr": "hot_fountain_fountain_eff_weight_push",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_fountain_eff_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_fountain_eff_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_fountain_eff_rank_cliff_min",
    "queue_pow_t": "explore_corr_fountain_eff_queue_pow_t",
    "score_threshold": "explore_ensemble_corr_fountain_eff_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_corr_fountain_eff_rank_height",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "fractile_name": "fr_ensemble_fountain_eff_fractile",
    "fractile_weight_attr": "explore_fr_fountain_eff_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_fountain_eff_fractile_power_weight",      
  },
  {
    "name": "awesome_wtd_score",
    "weight": 0.0,
    "power_weight_attr": "awesome_wtd_weight_push",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_awesome_wtd_score_queue_pow_t",
    "raw_weight_attr": "explore_fr_awesome_wtd_raw_weight",
    "raw_power_weight_attr": "explore_fr_awesome_wtd_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_awesome_wtd_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
    "use_min_rank": True,
    "value_seq_fusion_status_attr": "explore_fr_awesome_wtd_value_seq_fusion_status_attr",
    "queue_head_boost_coef": "explore_fr_awesome_wtd_head_boost_coef",
    "queue_tail_discount_coef": "explore_fr_awesome_wtd_tail_discount_coef",
    "fractile_name": "fr_ensemble_wtd_fractile",
    "fractile_weight_attr": "explore_fr_wtd_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_wtd_power_weight",
    "raw_score_min_val_attr": "life_fr_awesome_wtd_score_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_awesome_wtd_score_raw_score_max_val",
  },
  {
    "name": "score_consume_time_ltr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_l2r_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_score_consume_time_ltr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "consume_time_pf2r_score",
    "weight": 0.0,
    "power_weight_attr": "consume_time_pftr_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_consume_time_pf2r_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "adaptive_wtd_v2",
    "weight": 0.0,
    "power_weight_attr": "explore_adaptive_wtd_v2_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_adaptive_wtd_v2_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "watch_time_fusion_score",
    "weight": 0.0,
    "power_weight_attr": "watch_time_fusion_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_watch_time_fusion_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "corr_cpr",
    "weight": 0.0,
    "power_weight_attr": "explore_cpr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_corr_cpr_queue_pow_t",
    "raw_weight_attr": "explore_fr_corr_cpr_raw_weight",
    "raw_power_weight_attr": "explore_fr_corr_cpr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "corr_wtd_evtr",
    "weight": 0.0,
    "power_weight_attr": "explore_wtd_evtr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_corr_wtd_evtr_queue_pow_t",
    "raw_weight_attr": "explore_fr_corr_wtd_evtr_raw_weight",
    "raw_power_weight_attr": "explore_fr_corr_wtd_evtr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "corr_wtd_lvtr",
    "weight": 0.0,
    "power_weight_attr": "explore_wtd_lvtr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_corr_wtd_lvtr_queue_pow_t",
    "raw_weight_attr": "explore_fr_corr_wtd_lvtr_raw_weight",
    "raw_power_weight_attr": "explore_fr_corr_wtd_lvtr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "awesome_wtd_debias_score",
    "weight": 0.0,
    "power_weight_attr": "explore_awesome_wtd_debias_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_awesome_wtd_debias_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "debias_mix_score",
    "weight": 0.0,
    "power_weight_attr": "explore_debias_mix_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_debias_mix_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "lte_ltr",
    "weight": 0.0,
    "power_weight_attr": "explore_lte_ltr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_lte_ltr_que_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "fetr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_fetr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_fetr_queue_pow_t",
    "raw_weight_attr": "explore_fr_fetr_raw_weight",
    "raw_power_weight_attr": "explore_fr_fetr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_fetr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "fountain_eff",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_fountain_eff_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_fountain_eff_queue_pow_t",
    "raw_weight_attr": "explore_fr_fountain_eff_raw_weight",
    "raw_power_weight_attr": "explore_fr_fountain_eff_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_fountain_eff_normalize_alpha",
    "score_threshold": "explore_ensemble_fountain_eff_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_fountain_eff_rank_height",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "explore_fr_wtd_from_frac_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_wtd_from_frac_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_wtd_from_frac_score_raw_weight",
    "raw_power_weight_attr": "explore_fr_wtd_from_frac_score_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "explore_fr_wtd_frac_5_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_wtd_frac_5_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_wtd_frac_5_score_raw_weight",
    "raw_power_weight_attr": "explore_fr_wtd_frac_5_score_raw_power_weight",
    "value_seq_fusion_status_attr": "explore_fr_wtd_frac_5_score_seq_fusion_status",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "svtr_adapt_wtd_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_svtr_adapt_wtd_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_svtr_adapt_wtd_score_weight_raw_weight",
    "raw_power_weight_attr": "explore_fr_svtr_adapt_wtd_score_weight_raw_power_weight",
    "value_seq_fusion_status_attr": "explore_fr_svtr_adapt_wtd_score_seq_fusion_status",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "pairwise_rank_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_pairwise_rank_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_pairwise_rank_score_weight_raw_weight",
    "raw_power_weight_attr": "explore_fr_pairwise_rank_score_weight_raw_power_weight",
    "value_seq_fusion_status_attr": "explore_fr_pairwise_rank_score_seq_fusion_status",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "pairwise_rank_raw_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_pairwise_rank_raw_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_pairwise_rank_raw_score_weight_raw_weight",
    "raw_power_weight_attr": "explore_fr_pairwise_rank_raw_score_weight_raw_power_weight",
    "value_seq_fusion_status_attr": "explore_fr_pairwise_rank_raw_score_seq_fusion_status",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "ctr_multy_wtd_sharpe_ratio_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_ctr_multy_wtd_sharpe_ratio_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "value_seq_fusion_status_attr": "explore_fr_ctr_multy_wtd_sharpe_ratio_score_seq_fusion_status",
    "score_threshold": "explore_fr_ensemble_ctr_multy_wtd_sharpe_ratio_que_cliff_score_threshold",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "fr_score2_debias_duration",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fr_score2_debias_duration",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_score_fr_score2_debias_duration_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "hetu_gender_debias_avg_play_time_ms",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_hetu_gender_debias_avg_play_time_ms",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_score_queue_pow_t_hetu_gender_debias_avg_play_time_ms",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "mc_ensemble_pwatch_time",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_mc_pctr_x_pwatchtime_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_mc_pctr_x_pwatchtime_queue_pow_t",
    "raw_weight_attr": "explore_fr_mc_pctr_x_pwatchtime_raw_weight",
    "raw_power_weight_attr": "explore_fr_mc_pctr_x_pwatchtime_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_mc_pctr_x_pwatchtime_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "corr_pwtr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_ori_corr_pwtr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_ori_corr_pwtr_queue_pow_t",
    "raw_weight_attr": "explore_fr_ori_corr_pwtr_raw_weight",
    "raw_power_weight_attr": "explore_fr_ori_corr_pwtr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_ori_corr_pwtr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "cascade_prerank_pltr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_cascade_prerank_pltr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_cascade_prerank_pltr_queue_pow_t",
    "raw_weight_attr": "explore_fr_cascade_prerank_pltr_raw_weight",
    "raw_power_weight_attr": "explore_fr_cascade_prerank_pltr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_cascade_prerank_pltr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "score_pctr_x_fr_score2",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_score_pctr_x_fr_score2_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_score_pctr_x_fr_score2_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "score_pctr_x_awesome_wtd",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_score_pctr_x_awesome_wtd_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_score_pctr_x_awesome_wtd_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "gen_l2r_score",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_gen_l2r_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_gen_l2r_score_queue_pow_t",
    "raw_weight_attr": "explore_fr_gen_l2r_score_raw_weight",
    "raw_power_weight_attr": "explore_fr_gen_l2r_score_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_gen_l2r_score_normalize_alpha"
  },
  {
    "name": "ordinal_wtd_ltr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_ordinal_wtd_ltr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_ordinal_wtd_ltr_score_raw_weight",
    "raw_power_weight_attr": "explore_ordinal_wtd_ltr_score_raw_power_weight",
  },
  {
    "name": "gen_l2r_fusion_score",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_gen_l2r_fusion_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_gen_l2r_fusion_score_queue_pow_t",
    "raw_weight_attr": "explore_fr_gen_l2r_fusion_score_raw_weight",
    "raw_power_weight_attr": "explore_fr_gen_l2r_fusion_score_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_gen_l2r_fusion_score_normalize_alpha"
  },
  {
    "name": "consume_time_wtd",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_consume_time_wtd",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_consume_time_wtd_raw_weight",
    "raw_power_weight_attr": "explore_consume_time_wtd_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "cpr",
    "weight": 0.0,
    "power_weight_attr": "explore_origin_cpr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_cpr_queue_pow_t",
    "raw_weight_attr": "explore_fr_cpr_raw_weight",
    "raw_power_weight_attr": "explore_fr_cpr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "macr_svtr",
    "weight": 1.0,
    "power_weight_attr": "explore_ensemble_macr_svtr_power_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_macr_svtr_raw_weight",
    "raw_power_weight_attr": "explore_fr_macr_svtr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "life_dnn_lvtr",
    "weight": 1.0,
    "power_weight_attr": "explore_ensemble_life_dnn_lvtr_power_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_life_dnn_lvtr_raw_weight",
    "raw_power_weight_attr": "explore_fr_life_dnn_lvtr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  
]

#互动队列
interactive_queues = [
  {
    "name": "score_pctr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pctr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_pctr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pctr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pctr_rank_cliff_min",
    "queue_pow_t": "explore_score_pctr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pctr_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pctr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score_pctr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_interact_smooth", 
    "use_min_rank": True,
    "value_seq_fusion_status_attr": "explore_fr_score_pctr_value_seq_fusion_status_attr",
    "fractile_name": "fr_ensemble_pctr_fractile",
    "fractile_weight_attr": "explore_fr_pctr_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_pctr_fractile_power_weight",
    "queue_head_boost_coef": "explore_fr_score_pctr_head_boost_coef",
    "queue_tail_discount_coef": "explore_fr_score_pctr_tail_discount_coef",
    "raw_score_min_val_attr": "life_fr_score_pctr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pctr_raw_score_max_val",
  },
  {
    "name": "score_pltr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pltr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_pltr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pltr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pltr_rank_cliff_min",
    "score_threshold": "explore_ensemble_pltr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_pltr_rank_height",
    "queue_pow_t": "explore_score_pltr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pltr_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pltr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score_pltr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_interact_smooth", 
    "use_min_rank": True,
    "value_seq_fusion_status_attr": "explore_fr_score_pltr_value_seq_fusion_status_attr",
    "fractile_name": "fr_ensemble_pltr_fractile",
    "fractile_weight_attr": "explore_fr_pltr_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_pltr_fractile_power_weight",
    "queue_head_boost_coef": "explore_fr_score_pltr_head_boost_coef",
    "queue_tail_discount_coef": "explore_fr_score_pltr_tail_discount_coef",
    "raw_score_min_val_attr": "life_fr_score_pltr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pltr_raw_score_max_val",
  },
  {
    "name": "score_pwtr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pwtr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_pwtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pwtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pwtr_rank_cliff_min",
    "score_threshold": "explore_ensemble_pwtr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_pwtr_rank_height",
    "queue_pow_t": "explore_score_pwtr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pwtr_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pwtr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score_pwtr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "use_min_rank": True,
    "value_seq_fusion_status_attr": "explore_fr_score_pwtr_value_seq_fusion_status_attr",
    "fractile_name": "fr_ensemble_pwtr_fractile",
    "fractile_weight_attr": "explore_fr_pwtr_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_pwtr_fractile_power_weight",
    "queue_head_boost_coef": "explore_fr_score_pwtr_head_boost_coef",
    "queue_tail_discount_coef": "explore_fr_score_pwtr_tail_discount_coef",
    "raw_score_min_val_attr": "life_fr_score_pwtr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pwtr_raw_score_max_val",
  },
  {
    "name": "score_pftr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pftr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_pftr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pftr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pftr_rank_cliff_min",
    "score_threshold": "explore_ensemble_pftr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_pftr_rank_height",
    "queue_pow_t": "explore_score_pftr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pftr_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pftr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score_pftr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "use_min_rank": True,
    "value_seq_fusion_status_attr": "explore_fr_score_pftr_value_seq_fusion_status_attr",
    "fractile_name": "fr_ensemble_pftr_fractile",
    "fractile_weight_attr": "explore_fr_pftr_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_pftr_fractile_power_weight",
    "queue_head_boost_coef": "explore_fr_score_pftr_head_boost_coef",
    "queue_tail_discount_coef": "explore_fr_score_pftr_tail_discount_coef",
    "raw_score_min_val_attr": "life_fr_score_pftr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pftr_raw_score_max_val",
  },
  {
    "name": "score_pcmtr",
    "weight": 0.0,
    "power_weight_attr": "fr_pmctr_rank_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_pcmtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pcmtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pcmtr_rank_cliff_min",
    "score_threshold": "explore_ensemble_pcmtr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_pcmtr_rank_height",
    "queue_pow_t": "explore_score_pcmtr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pcmtr_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pcmtr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score_pcmtr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "use_min_rank": True,
    "value_seq_fusion_status_attr": "explore_fr_score_pcmtr_value_seq_fusion_status_attr",
    "fractile_name": "fr_ensemble_pcmtr_fractile",
    "fractile_weight_attr": "explore_fr_pcmtr_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_pcmtr_fractile_power_weight",
    "raw_score_min_val_attr": "life_fr_score_pcmtr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pcmtr_raw_score_max_val",
  },
  {
    "name": "score_pptr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pptr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_pptr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pptr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pptr_rank_cliff_min",
    "score_threshold": "explore_ensemble_pptr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_pptr_rank_height",
    "queue_pow_t": "explore_score_pptr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pptr_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pptr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "fractile_name": "fr_ensemble_pptr_fractile",
    "fractile_weight_attr": "explore_fr_pptr_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_pptr_fractile_power_weight",
    "raw_score_min_val_attr": "life_fr_score_pptr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pptr_raw_score_max_val",
  },
  {
    "name": "score_pcmef",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pcmef_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_score_pcmef_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pcmef_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pcmef_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score_pcmef_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "value_seq_fusion_status_attr": "explore_fr_score_pcmef_value_seq_fusion_status_attr",
    "raw_score_min_val_attr": "life_fr_score_pcmef_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pcmef_raw_score_max_val",
  },
  {
    "name": "score_pdtr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pdtr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_pdtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pdtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pdtr_rank_cliff_min",
    "score_threshold": "explore_ensemble_pdtr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_pdtr_rank_height",
    "queue_pow_t": "explore_score_pdtr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pdtr_raw_weight",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_score_min_val_attr": "life_fr_score_pdtr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pdtr_raw_score_max_val",
  },
  {
    "name": "score_pcltr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_fullrank_pcltr_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "variant_weight": "fr_cltr_score_variant_weight",
    "avg_xtr" : "avg_cltr",
    "min_ratio" : "explore_fr_ensemble_pcltr_min_ratio",
    "max_ratio" : "explore_fr_ensemble_pcltr_max_ratio",
    "dynamic_weight" : "explore_fr_ensemble_pcltr_dynamic_weight",
    "user_xtr": "realtime_cltr",
    "rank_cliff_attr": "explore_ensemble_pcltr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_pcltr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_pcltr_rank_cliff_min",
    "score_threshold": "explore_ensemble_pcltr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_pcltr_rank_height",
    "queue_pow_t": "explore_score_pcltr_queue_pow_t",
    "raw_weight_attr": "explore_fr_score_pcltr_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_pcltr_raw_power_weight",
    "raw_score_normalize_alpha_attr": "explore_fr_score_pcltr_normalize_alpha",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "use_min_rank": True,
    "value_seq_fusion_status_attr": "explore_fr_score_pcltr_value_seq_fusion_status_attr",
    "fractile_name": "fr_ensemble_pcltr_fractile",
    "fractile_weight_attr": "explore_fr_pcltr_fractile_weight",
    "fractile_power_weight_attr": "explore_fr_pcltr_fractile_power_weight",
    "raw_score_min_val_attr": "life_fr_score_pcltr_raw_score_min_val",
    "raw_score_max_val_attr": "life_fr_score_pcltr_raw_score_max_val",    
  },
  {
    "name": "score_phtr",
    "weight": 0.0,
    "reverse_order": True,
    "power_weight_attr": "htr_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_score_phtr_queue_pow_t",
    "rank_cliff_attr": "explore_ensemble_phtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_phtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_phtr_rank_cliff_min",
    "score_threshold": "explore_ensemble_phtr_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_phtr_rank_height",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "score_phtr",
    "weight": 0.0,
    "power_weight_attr": "life_htr_score_in_order_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_htr_score_in_order_weight",
    "raw_weight_attr": "life_fr_score_phtr_in_order_raw_weight",
    "raw_power_weight_attr": "life_fr_score_phtr_in_order_raw_power_weight",
    "score_threshold": "life_ensemble_phtr_in_order_rank_cliff_threshold",
    "rank_height_attr": "life_ensemble_phtr_in_order_rank_height",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "svr_act_score",
    "weight": 0.0,
    "power_weight_attr": "fr_psvr_plvtr_rank_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_svr_act_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "act_combo_vtr_score",
    "weight": 0.0,
    "power_weight_attr": "act_combo_vtr_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_act_combo_vtr_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "deep_ltr_score",
    "weight": 0.0,
    "power_weight_attr": "deep_ltr_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_deep_ltr_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "watchtime_interact_score",
    "weight": 0.0,
    "power_weight_attr": "user_interact_watchtime_cost_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_watchtime_interact_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "ewatch_score",
    "weight": 0.0,
    "power_weight_attr": "hot_fr_ewatch_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_ewatch_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pcmef_debias_score",
    "weight": 0.0,
    "power_weight_attr": "pcmef_gender_debias_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_pcmef_debias_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "interact_fusion_score",
    "weight": 0.0,
    "power_weight_attr": "interact_fusion_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_interact_fusion_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "corr_future_xtr",
    "weight": 0.0,
    "power_weight_attr": "explore_future_xtr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_corr_future_xtr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "ada_xtr_score",
    "weight": 0.0,
    "power_weight_attr": "user_interact_fetr_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_ada_xtr_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "cascade_linear_score",
    "weight": 0.0,
    "power_weight_attr": "user_interact_feff_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_cascade_linear_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "click_cost_score",
    "weight": 0.0,
    "power_weight_attr": "explore_click_cost_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_click_cost_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "highorder_interact_score",
    "weight": 0.0,
    "power_weight_attr": "explore_highorder_interact_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_highorder_interact_score_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "absolute_xtr_score_que",
    "weight": 0.0,
    "power_weight_attr": "explore_absolute_xtr_score_que_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "rank_cliff_attr": "explore_ensemble_absolute_xtr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_absolute_xtr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_absolute_xtr_rank_cliff_min",
    "queue_pow_t": "explore_absolute_xtr_score_que_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fractile_raw_weight",
    "raw_power_weight_attr": "explore_fractile_raw_power_weight",
  },
  {
    "name": "xhs_meta_ltr",
    "weight": 0.0,
    "power_weight_attr": "explore_meta_ltr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_xhs_meta_ltr_que_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pctr_pfr2r",
    "weight": 0.0,
    "power_weight_attr": "explore_rank_pctr_pfr2r_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_pctr_pfr2r_que_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pcltr_pfr2r",
    "weight": 0.0,
    "power_weight_attr": "explore_rank_pcltr_pfr2r_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_pcltr_pfr2r_que_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "lte_ctr",
    "weight": 0.0,
    "power_weight_attr": "explore_lte_ctr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_lte_ctr_que_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pctr_debias_hetu",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_pctr_debias_hetu",
    "queue_pow_t": "explore_score_pctr_debias_hetu_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pltr_debias_hetu",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_pltr_debias_hetu",
    "queue_pow_t": "explore_score_pltr_debias_hetu_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pwtr_debias_hetu",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_pwtr_debias_hetu",
    "queue_pow_t": "explore_score_pwtr_debias_hetu_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pftr_debias_hetu",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_pftr_debias_hetu",
    "queue_pow_t": "explore_score_pftr_debias_hetu_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pcmtr_debias_hetu",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_pcmtr_debias_hetu",
    "queue_pow_t": "explore_score_pcmtr_debias_hetu_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "pptr_debias_hetu",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_pptr_debias_hetu",
    "queue_pow_t": "explore_score_pptr_debias_hetu_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "awesome_wtd_debias_v2",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_awesome_wtd_debias_v2",
    "queue_pow_t": "explore_score_awesome_wtd_debias_v2_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "corr_pltr_formula",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_corr_ltr_formula_weight",
    "queue_pow_t": "explore_fullrank_es_corr_ltr_formula_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "corr_fr_score2_formula",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_corr_fr_score2_formula_weight",
    "queue_pow_t": "explore_fullrank_es_corr_fr_score2_formula_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "corr_pfvtr_formula",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_corr_fvtr_formula_weight",
    "queue_pow_t": "explore_fullrank_es_corr_fvtr_formula_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "plstr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_plstr_formula_weight",
    "queue_pow_t": "explore_fullrank_es_plstr_formula_queue_pow_t",
    "rank_cliff_attr": "explore_ensemble_plstr_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_plstr_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_plstr_rank_cliff_min",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "plsst",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_plsst_formula_weight",
    "queue_pow_t": "explore_fullrank_es_plsst_formula_queue_pow_t",
    "rank_cliff_attr": "explore_ensemble_plsst_rank_cliff",
    "rank_cliff_ratio_attr": "explore_ensemble_plsst_rank_cliff_ratio",
    "rank_cliff_min_attr": "explore_ensemble_plsst_rank_cliff_min",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "min_act_rank_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_min_act_rank_score_formula_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_min_act_rank_score_formula_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "fr_ctcvr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_ctcvr_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_ctcvr_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "fr_ctcvr_gmv_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_ctcvr_gmv_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_ctcvr_gmv_score_formula_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "fr_elive_ctcvr_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_elive_ctcvr_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_elive_ctcvr_score_formula_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "fr_elive_ctcvr_gmv_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_elive_ctcvr_gmv_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_elive_ctcvr_gmv_score_formula_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "produce_mtctr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_mtctr_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_mtctr_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_mtctr_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_mtctr_raw_power_weight",
  },
  {
    "name": "produce_twhtr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_twhtr_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_twhtr_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_twhtr_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_twhtr_raw_power_weight",
  },
  {
    "name": "produce_mfctr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_mfctr_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_mfctr_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_mfctr_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_mfctr_raw_power_weight",
  },
  {
    "name": "produce_mtcotr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_mtcotr_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_mtcotr_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_mtcotr_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_mtcotr_raw_power_weight",
  },
  {
    "name": "produce_mtjtr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_mtjtr_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_mtjtr_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_mtjtr_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_mtjtr_raw_power_weight",
  },
  {
    "name": "produce_mtm1",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_mtm1_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_mtm1_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_mtm1_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_mtm1_raw_power_weight",
  },
  {
    "name": "produce_upload_sum_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_upload_sum_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_upload_sum_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_upload_sum_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_upload_sum_raw_power_weight",
  },
  {
    "name": "produce_uploads",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_uploads_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_uploads_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_uploads_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_uploads_raw_power_weight",
  },
  {
    "name": "produce_consuv_sum_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_produce_consuv_sum_score_formula_weight",
    "queue_pow_t": "explore_fullrank_es_produce_consuv_sum_score_formula_weight_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
    "raw_weight_attr": "explore_fullrank_es_produce_consuv_sum_raw_weight",
    "raw_power_weight_attr": "explore_fullrank_es_produce_consuv_sum_raw_power_weight",
  },
  {
    "name": "score_pctr_x_pcltr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_score_pctr_x_pcltr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_score_pctr_x_pcltr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "score_pctr_x_pepstr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_score_pctr_x_pepstr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_score_pctr_x_pepstr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "score_pctr_x_pptr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_score_pctr_x_pptr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_score_pctr_x_pptr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "score_pctr_x_pdtr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_score_pctr_x_pdtr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_score_pctr_x_pdtr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "score_pctr_x_pftr",
    "weight": 0.0,
    "power_weight_attr": "explore_fullrank_es_score_pctr_x_pftr_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "explore_fullrank_es_score_pctr_x_pftr_queue_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "life_ltr_pctr",
    "weight": 0.0,
    "power_weight_attr": "el_fr_es_life_ltr_pctr_weight",
    "raw_weight_attr": "el_fr_es_life_ltr_pctr_raw_weight",
    "raw_power_weight_attr": "el_fr_es_life_ltr_pctr_raw_power_weight",
    "queue_pow_t": "el_fr_es_life_ltr_pctr_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "life_pctr",
    "weight": 0.0,
    "power_weight_attr": "life_fullrank_es_score_life_pctr_weight",
    "raw_weight_attr": "life_fullrank_es_score_life_pctr_raw_weight",
    "raw_power_weight_attr": "life_fullrank_es_score_life_pctr_raw_power_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "life_psvtr",
    "weight": 0.0,
    "power_weight_attr": "life_fullrank_es_score_life_psvtr_weight",
    "raw_weight_attr": "life_fullrank_es_score_life_psvtr_raw_weight",
    "raw_power_weight_attr": "life_fullrank_es_score_life_psvtr_raw_power_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "life_truth_pctr",
    "weight": 0.0,
    "power_weight_attr": "life_fullrank_es_score_life_truth_pctr_weight",
    "raw_weight_attr": "life_fullrank_es_score_life_truth_pctr_raw_weight",
    "raw_power_weight_attr": "life_fullrank_es_score_life_truth_pctr_raw_power_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "global_emphtr_score",
    "weight": 0.0,
    "power_weight_attr": "emp_htr_score_in_order_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "emp_htr_score_in_order_weight",
    "raw_weight_attr": "explore_fr_score_emp_phtr_in_order_raw_weight",
    "raw_power_weight_attr": "explore_fr_score_emp_phtr_in_order_raw_power_weight",
    "score_threshold": "explore_ensemble_emp_phtr_in_order_rank_cliff_threshold",
    "rank_height_attr": "explore_ensemble_emp_phtr_in_order_rank_height",
    "smooth_attr": "explore_fr_ensemble_htr_smooth",
  },
  {
    "name": "global_empwtr_score",
    "weight": 0.0,
    "power_weight_attr": "life_emp_wtr_score_pow_t",
    "queue_pow_t": "life_emp_wtr_score_pow_t",
    "raw_weight_attr": "life_fr_score_emp_pwtr_raw_weight",
    "raw_power_weight_attr": "life_fr_score_emp_pwtr_raw_power_weight",
    "smooth_attr": "life_fr_ensemble_wtr_smooth",
  },
  {
    "name": "hetu_gender_debias_ctr",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_es_weight_hetu_gender_debias_ctr",
    "queue_pow_t": "explore_fr_es_pow_t_weight_hetu_gender_debias_ctr",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "hetu_gender_debias_ltr",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_es_weight_hetu_gender_debias_ltr",
    "queue_pow_t": "explore_fr_es_pow_t_weight_hetu_gender_debias_ltr",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "hetu_gender_debias_ftr",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_es_weight_hetu_gender_debias_ftr",
    "queue_pow_t": "explore_fr_es_pow_t_weight_hetu_gender_debias_ftr",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "hetu_gender_debias_cltr",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_es_weight_hetu_gender_debias_cltr",
    "queue_pow_t": "explore_fr_es_pow_t_weight_hetu_gender_debias_cltr",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "hetu_gender_debias_cmtr",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_es_weight_hetu_gender_debias_cmtr",
    "queue_pow_t": "explore_fr_es_pow_t_weight_hetu_gender_debias_cmtr",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "hetu_gender_debias_wtr",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_es_weight_hetu_gender_debias_wtr",
    "queue_pow_t": "explore_fr_es_pow_t_weight_hetu_gender_debias_wtr",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "action_diff_score",
    "weight": 0.0,
    "power_weight_attr": "follow_long_term_value_action_diff_weight",
    "queue_pow_t": "follow_long_term_value_action_diff_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "post_follow_score",
    "weight": 0.0,
    "power_weight_attr": "follow_long_term_value_post_follow_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "follow_long_term_value_post_follow_pow_t",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "rank_distill_ltr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_rank_distill_ltr",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_rank_distill_ltr_raw_weight",
    "raw_power_weight_attr": "explore_rank_distill_ltr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "rank_distill_ctr",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_rank_distill_ctr",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_rank_distill_ctr_raw_weight",
    "raw_power_weight_attr": "explore_rank_distill_ctr_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "coordinated_watchtime_score",
    "weight": 0.0,
    "power_weight_attr": "explore_ensemble_power_weight_coordinated_watchtime_score",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_coordinated_watchtime_score_raw_weight",
    "raw_power_weight_attr": "explore_coordinated_watchtime_score_raw_power_weight",
    "smooth_attr": "explore_fr_ensemble_time_smooth",
  },
  {
    "name": "ctr_pairwise_rank_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_ctr_pairwise_rank_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_ctr_pairwise_rank_score_weight_raw_weight",
    "raw_power_weight_attr": "explore_fr_ctr_pairwise_rank_score_weight_raw_power_weight",
    "value_seq_fusion_status_attr": "explore_fr_ctr_pairwise_rank_score_seq_fusion_status",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "ctr_pairwise_rank_raw_score",
    "weight": 0.0,
    "power_weight_attr": "explore_fr_ctr_pairwise_rank_raw_score_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "raw_weight_attr": "explore_fr_ctr_pairwise_rank_raw_score_weight_raw_weight",
    "raw_power_weight_attr": "explore_fr_ctr_pairwise_rank_raw_score_weight_raw_power_weight",
    "value_seq_fusion_status_attr": "explore_fr_ctr_pairwise_rank_raw_score_seq_fusion_status",
    "smooth_attr": "explore_fr_ensemble_interact_smooth",
  },
  {
    "name": "nonneg_intere_score",
    "weight": 0.5,
    "power_weight_attr": "explore_fr_intere_score_power_weight",
    "weight_attr": "explore_fr_intere_score_weight",
    "raw_weight_attr": "explore_fr_intere_score_raw_weight",
    "raw_power_weight_attr": "explore_fr_intere_score_raw_power_weight",
    "smooth_attr": "explore_fr_intere_score_interact_smooth",
  },
  {
    "name": "danlie_depress_score",
    "weight": 0.5,
    "power_weight_attr": "xlife_fr_danlie_depress_score_power_weight",
    "weight_attr": "xlife_fr_danlie_depress_score_weight",
    "raw_weight_attr": "xlife_fr_danlie_depress_score_raw_weight",
    "raw_power_weight_attr": "xlife_fr_danlie_depress_score_raw_power_weight",
    "smooth_attr": "xlife_fr_danlie_depress_score_interact_smooth",
  },
  {
    "name": "sensitive_related_score",
    "weight": 0.0,
    "power_weight_attr": "life_fr_sensitive_related_score_power_weight",
    "temperature_attr": "explore_fr_ensemble_temperature",
    "queue_pow_t": "life_fr_sensitive_related_score_power_weight",
    "raw_weight_attr": "life_fr_sensitive_related_score_raw_weight",
    "raw_power_weight_attr": "life_fr_sensitive_related_score_raw_power_weight",
    "smooth_attr": "life_fr_sensitive_related_score_smooth",
  },
  {
    "name" : "empirical_svtr",
    "weight" : 0.5,
    "weight_attr" : "life_fr_empirical_svtr_weight",
    "power_weight_attr" : "life_fr_empirical_svtr_power_weight",
    "temperature_attr" : "explore_fr_ensemble_temperature",
    "raw_weight_attr": "life_fr_empirical_svtr_raw_weight",
    "raw_power_weight_attr": "life_fr_empirical_svtr_raw_power_weight",
  }, 
]

zero_play_queues = [
  "explore_ensemble_power_weight_fullrank_pltr_score",
  "explore_ensemble_power_weight_fullrank_pwtr_score",
  "explore_ensemble_power_weight_fullrank_pftr_score",
  "fr_pmctr_rank_weight",
  "explore_ensemble_power_weight_fullrank_pptr_score",
  "explore_ensemble_power_weight_fullrank_pcmef_score",
  "explore_ensemble_power_weight_fullrank_pdtr_score",
  "explore_ensemble_power_weight_fullrank_pcltr_score",
  "explore_ensemble_weight_duration_ms",
  "explore_ensemble_power_weight_fullrank_l2r_score"
]

zero_play_ctr_queues = [
  "explore_ensemble_power_weight_fullrank_pctr_score",
]

all_ensemble_queues = picture_queues + diversity_queues + time_queues + interactive_queues
