#!/usr/bin/env python3
# coding=utf-8

def get_splash_rerank_abtest():
  return [
        ("fountain_splash_rerank_predict_use_kai", False),
        ("fountain_splash_rerank_enable_skip_diversity", True),
        ("fountain_splash_rerank_limit_size", 30),
        ("fountain_splash_rerank_enable_control_diversity_quota", 0),
        ("fountain_splash_rerank_enable_duration_control_diversity", False),
        ("fountain_splash_rerank_duration_control_diversity_start", 0),
        ("fountain_splash_rerank_control_duration_0_7s_max_size", 30),
        ("fountain_splash_rerank_control_duration_7_9s_max_size", 30),
        ("fountain_splash_rerank_control_duration_9_12s_max_size", 30),
        ("fountain_splash_rerank_control_duration_12_17s_max_size", 30),
        ("fountain_splash_rerank_control_duration_17_20s_max_size", 30),
        ("fountain_splash_rerank_control_duration_20_58s_max_size", 30),
        ("skip_fountain_splash_rerank_limit", 0),
        ("enable_fountain_splash_rerank_gen_original_list", 1),  # 精排原始序列开关
        ("enable_fountain_splash_rerank_gen_ensemble_list", 1),  # es 序列开关
        ("fountain_splash_rerank_gen_seed_ensemble_max_sequence_num", 30),
        ("fountain_splash_rerank_gen_seed_ensemble_origin_seq_range", 20),
        ("fountain_splash_rerank_gen_seed_ensemble_use_proportion", 0),
        ("fountain_splash_rerank_gen_seed_ensemble_use_pow_rank", 1),
        ("fountain_splash_rerank_max_retrieval_num", 15),
        ("fountain_splash_skip_rerank_predict", 0),
        ("fountain_splash_rerank_evaluator_model_version", 0),
        ("fountain_splash_rerank_kess_service", "grpc_krpTfHotRerankModelPredictServerV3Infer"),
        ("fountain_splash_rerank_predict_timeout_ms", 100),
        ("fountain_splash_rerank_predict_layer_name", "slide_detail_scores_n"),
        ("fountain_splash_rerank_predict_loss_name", "pos0;pos1"),
        ("fountain_splash_rerank_enable_gen_ensemble_use_order_13", False),
        ("fountain_splash_rerank_enable_gen_ensemble_use_order_23", False),
        ("enable_fountain_splash_rerank_use_beamsearch", False),
        ("fountain_rerank_splash_beamsearch_size", 10),
        ("fountain_rerank_splash_beamsearch_rate_type", 1),
        ("fountain_rerank_splash_beamsearch_max_len", 2),
        ("fountain_rerank_enable_use_fountain_ui", True),
        ("only_rerank_request_num_is_2", 0),
        ("fountain_rerank_expected_value_enable_power_calc_v2_splash", 1),
        ("fountain_rerank_expected_value_use_rank_with_absolute_score_splash", 1),
        ("fountain_splash_rerank_bs_search_num_ab_str", "3,4,2,1,1,1"), # beam search 选取数量配置
        ("fountain_splash_rerank_bs_fix_top1_method", 0), # beam search 第一条选取排序方式
        ("fountain_splash_rerank_use_seed_seq", 0), # 是否使用 seed sequence 作为最终排序的结果集，保证 top2 条以后的顺序。
        ("fountain_splash_rerank_gen_final_seq_max_size", 2), # 送入评估前的最终 seq 最大截断数量，与 generator 阶段序列长度拆开。
        ("fountain_splash_rerank_gen_seed_ensemble_seq_max_size", 2),
        ("fountain_splash_rerank_list_next_weight_new", 1.0),
        ("fountain_splash_rerank_enable_use_list_score", 0),
        ("fountain_splash_rerank_item_next_score_attr", "fountain_splash_slide"),
        ("fountain_rerank_splash_enable_pos_context", False),
        ("fountain_rerank_splash_last_coeff2", 2.0),
        ("fountain_rerank_splash_use_odd2", True),
        ("fountain_rerank_splash_enable_pos_next2", False),
        ("fountain_splash_rerank_duration_adjust_param", 1.0),
        ("fountain_splash_rerank_duration_adjust_level", 58),
        ("score_factor_coffe", 0.0),
        # 首屏 bs 队列参数
        ("fountain_splash_beamsearch_click_score_weight", 1.0),
        ("fountain_splash_beamsearch_click_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_shortview_score_weight", 0.3),
        ("fountain_splash_beamsearch_shortview_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_finish_rate_weight", 0.0),
        ("fountain_splash_beamsearch_finish_rate_power_weight", 1.0),
        ("fountain_splash_beamsearch_watchtime_ori_score_weight", 0.5),

        ("fountain_splash_beamsearch_watchtime_ori_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_watchtime_weight", 1.0),
        ("fountain_splash_beamsearch_watchtime_power_weight", 1.0),
        ("fountain_splash_beamsearch_like_score_weight", 0.5),
        ("fountain_splash_beamsearch_like_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_profile_score_weight", 0.1),
        ("fountain_splash_beamsearch_profile_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_comment_score_weight", 0.0),
        ("fountain_splash_beamsearch_comment_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_forward_score_weight", 0.0),
        ("fountain_splash_beamsearch_forward_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_follow_score_weight", 0.0),
        ("fountain_splash_beamsearch_follow_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_action_once_interact_score_weight", 0.0),
        ("fountain_splash_beamsearch_action_once_interact_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_neg_feedback_discount_score_weight", 0.2),
        ("fountain_splash_beamsearch_neg_feedback_discount_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_source_related_score_weight", 0.0),
        ("fountain_splash_beamsearch_source_related_score_power_weight", 1.0),
        ("fountain_splash_beamsearch_pevtr_v2_weight", 0.0),
        ("fountain_splash_beamsearch_pevtr_v2_power_weight", 1.0),
        ("fountain_splash_beamsearch_pevtr_v2_raw_weight_attr", 0.0),
        ("fountain_splash_beamsearch_pevtr_v2_raw_pow_weight_attr", 1.0),
        ("fountain_splash_beamsearch_sim_lstr_weight", 0.0),
        ("fountain_splash_beamsearch_sim_lstr_power_weight", 1.0),
        ("fountain_splash_beamsearch_sim_lstr_raw_weight_attr", 0.0),
        ("fountain_splash_beamsearch_sim_lstr_raw_pow_weight_attr", 1.0),
        ("fountain_splash_beamsearch_sim_evtr_playtime_weight", 0.0),
        ("fountain_splash_beamsearch_sim_evtr_playtime_power_weight", 1.0),
        ("fountain_splash_beamsearch_sim_evtr_playtime_raw_weight_attr", 0.0),
        ("fountain_splash_beamsearch_sim_evtr_playtime_raw_pow_weight_attr", 1.0),
        # 首屏 mdp 参数
        ("enable_fountain_splash_model_mdp_gen_list", False),
        ("fountain_splash_mdp_gen_list_pnext_alpha", 1.0),
        ("fountain_splash_mdp_gen_list_pnext_beta", 0.0),
        ("fountain_splash_mdp_gen_list_candidate_size", 30),
        ("fountain_splash_mdp_gen_list_output_len", 2),
        ("fountain_splash_mdp_gen_list_beam_size", 3),
        ("fountain_splash_mdp_gen_list_value_mean", 1.0),
        # 首屏是否写 rerank top result 到 redis
        ("fountain_splash_enable_write_rerank_top_result_to_redis", False),
        ("fountain_splash_rerank_top_photo_start_index", 0),
        ("fountain_splash_rerank_top_photo_end_index", 6),
        ("fountain_splash_rerank_top_photo_size", 10),
        ("fountain_splash_rerank_top_photo_redis_expire_seconds", 600),
        ("fountain_splash_rerank_top_photo_key_prefix", "f_s_rerank_top_"),
        ("fountain_splash_rerank_top_result_enable_reason_select", False),
        ("fountain_splash_rerank_top_result_select_reasons", "10409,13020,10417"),
        ("fountain_splash_rerank_top_result_enable_relate_select", False),
        ("fountain_splash_rerank_top_result_relate_select_threshold", 0.0),
        ("fountain_splash_rerank_top_result_enable_ctr_select", False),
        ("fountain_splash_rerank_top_result_ctr_select_threshold", 0.0),
        ("fountain_splash_rerank_top_result_enable_watchtime_select", False),
        ("fountain_splash_rerank_top_result_watchtime_select_threshold", 0.0),
        # 首屏全链路采样 rerank
        ("fountain_enable_rerank_full_link_sample_splash", 0),
        # rerank_predict
        ("fountain_splash_rerank_enable_gen_ar_model", False),
        ("fountain_rerank_gen_model_beam_size_splash", 10, "fountain_rerank_gen_model_beam_size"),
        ("fountain_splash_rerank_gen_ar_model_kess_service", "grpc_splash_rerank_model_gen_ar_server"),
        ("fountain_splash_rerank_gen_ar_model_partition_size", 30),
        ("fountain_splash_rerank_gen_ar_model_request_type", "kai_predict"),
        # rerank eval predict
        ("fountain_splash_rerank_eval_mtl_model_kess_service", "grpc_splash_rerank_eval_mtl_v2_server"),
        ("fountain_splash_rerank_eval_mtl_model_request_type", "kai_predict"),
        ("fountain_splash_rerank_eval_mtl_model_partition_size", 30),
        # 首屏pxtr人群个性化参数
        ("enable_rerank_splash_cal_user_group_emp_xtr", 0),
        ("enable_rerank_splash_ten_user_group_adjust_wtachtime", 0),
        ("enable_rerank_splash_ten_user_group_adjust_pfintr", 0),
        ("fountain_rerank_ensemble_power_weight_adjust_ratio_min", 0.5),
        ("fountain_rerank_ensemble_power_weight_adjust_ratio_max", 2.0),
        ("fountain_rerank_ensemble_power_weight_adjust_request_ratio", 0.0),
        ("fountain_rerank_ensemble_power_weight_fullrank_ltr_emp", 0.03),
        ("fountain_rerank_ensemble_power_weight_fullrank_wtr_emp", 0.001),
        ("fountain_rerank_ensemble_power_weight_fullrank_cmtr_emp", 0.03),
        ("fountain_rerank_ensemble_power_weight_fullrank_ptr_emp", 0.03),
        ("fountain_rerank_ensemble_power_weight_fullrank_ftr_emp", 0.03),
        ("fountain_rerank_ensemble_power_weight_fullrank_epstr_emp", 0.03),
        ("fountain_rerank_ensemble_power_weight_fullrank_evtr_emp", 0.0),
        ("fountain_rerank_ensemble_power_weight_fullrank_lvtr_emp", 0.0),
        ("fountain_rerank_ensemble_power_weight_fullrank_fintr_emp", 0.0),
  ]

def get_rerank_v3_ab_params():
  return [
    ("enable_use_fountain_rerank", 0),

    # rerank_predict
    ("fountain_rerank_enable_gen_model_beam", False),
    ("fountain_rerank_gen_model_beam_kess_service", ""),
    ("fountain_rerank_gen_model_partition_size", 60),
    ("fountain_rerank_gen_model_request_type", "kai_predict"),
    ("fountain_rerank_enable_gen_model_nar_beam", False),
    ("fountain_rerank_gen_model_beam_nar_kess_service", ""),
    ("fountain_rerank_gen_model_nar_partition_size", 60),
    ("fountain_rerank_gen_model_nar_request_type", "kai_predict"),
    ("fountain_rerank_enable_gen_model_ar_beam", False),
    ("fountain_rerank_gen_model_beam_ar_kess_service", ""),
    ("fountain_rerank_gen_model_ar_partition_size", 60),
    ("fountain_rerank_gen_model_ar_request_type", "kai_predict"),
    ("fountain_rerank_enable_gen_model_rankmixer", False),
    ("fountain_rerank_gen_model_beam_rankmixer_kess_service", ""),
    ("fountain_rerank_gen_model_rankmixer_partition_size", 60),
    ("fountain_rerank_gen_model_rankmixer_request_type", "kai_predict"),
    ("fountain_rerank_enable_gen_model_ar_pinrec", False),
    ("fountain_rerank_gen_model_beam_ar_pinrec_kess_service", ""),
    ("fountain_rerank_gen_model_ar_pinrec_partition_size", 60),
    ("fountain_rerank_gen_model_ar_pinrec_request_type", "kai_predict"),

    # rerank_gen_candidate_list
    ("fountain_enable_dpp_gen_model", False),
    ("fountain_rerank_gen_model_beam_size", 0),
    ("fountain_enable_dpp_gen_ar_model", False),
    ("fountain_rerank_gen_ar_model_size", 1),
    ("fountain_enable_dpp_gen_nar_model", False),
    ("fountain_rerank_gen_nar_model_size", 1),
    ("fountain_enable_dpp_gen_rankmixer_model", False),
    ("fountain_rerank_gen_rankmixer_model_size", 1),
    ("fountain_enable_dpp_gen_ar_pinrec_model", False),
    ("fountain_rerank_gen_ar_pinrec_model_size", 1),
    ("fountain_enable_rerank_source_related_score_weight_user_custom", 0),
    ("enable_rerank_source_related_score_weight_adjust_by_page", 0),
    ("fountain_enable_rerank_trend_weight_user_custom_pvtr", 0),
    ("fountain_enable_rerank_trend_weight_user_custom_plvtr", 0),
    ("fountain_enable_rerank_ten_group_weight_user_custom_pfintr", 0),
    ("fountain_enable_rerank_ten_group_weight_user_custom_pvtr", 0),
    ("fountain_enable_rerank_ten_group_weight_user_custom_plvtr", 0),

     # 内流分时段个性化权重
    ("fountain_enable_rerank_duration_longview_adjust_weight_user_custom_pfintr", 0),
    ("fountain_enable_rerank_duration_longview_adjust_weight_user_custom_pvtr", 0),
    ("fountain_enable_rerank_duration_longview_adjust_weight_user_custom_plvtr", 0),
    ("fountain_enable_rerank_duration_longview_adjust_weight_user_custom_pcpr", 0),

    # 根据最近和历史单次vv播放时长比值对时长调权
    ("fountain_enable_rerank_playtime_trend_adjust_weight_user_custom_pfintr", 0),
    ("fountain_enable_rerank_playtime_trend_adjust_weight_user_custom_pvtr", 0),
    ("fountain_enable_rerank_playtime_trend_adjust_weight_user_custom_plvtr", 0),
    ("fountain_enable_rerank_playtime_trend_adjust_weight_user_custom_pcpr", 0),

    # 内流用户分时段长短播偏好对互动调权
    ("fountain_enable_rerank_duration_longview_adjust_weight_like_score", 0),
    ("fountain_enable_rerank_duration_longview_adjust_weight_follow_score", 0),
    ("fountain_enable_rerank_duration_longview_adjust_weight_comment_score", 0),
    ("fountain_enable_rerank_duration_longview_adjust_weight_forward_score", 0),
    ("fountain_enable_rerank_duration_longview_adjust_weight_collect_score", 0),

    ("fountain_rerank_ensemble_power_weight_adjust_ratio_min", 0.5),
    ("fountain_rerank_ensemble_power_weight_adjust_ratio_max", 2.0),
    ("fountain_rerank_ensemble_power_weight_adjust_request_ratio", 0.0),
    ("fountain_rerank_ensemble_power_weight_fullrank_ltr_emp", 0.03),
    ("fountain_rerank_ensemble_power_weight_fullrank_wtr_emp", 0.001),
    ("fountain_rerank_ensemble_power_weight_fullrank_cmtr_emp", 0.03),
    ("fountain_rerank_ensemble_power_weight_fullrank_ptr_emp", 0.03),
    ("fountain_rerank_ensemble_power_weight_fullrank_ftr_emp", 0.03),
    ("fountain_rerank_ensemble_power_weight_fullrank_epstr_emp", 0.03),
    ("fountain_rerank_ensemble_power_weight_fullrank_evtr_emp", 0.0),
    ("fountain_rerank_ensemble_power_weight_fullrank_lvtr_emp", 0.0),
    ("fountain_rerank_ensemble_power_weight_fullrank_fintr_emp", 0.0),

    # rerank_gen_candidate_list - es_add
    ("fountain_rerank_dpp_diversity_max_sequence_num", 30, "rerank_dpp_diversity_max_sequence_num"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_click_score", 0.0, "rerank_es_fullrank_click_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_click_range", 0.0, "rerank_es_fullrank_click_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_click_raw_weight", 0.0, "rerank_es_fullrank_click_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_click_raw_pow_weight", 1.0, "rerank_es_fullrank_click_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_like_score", 0.0, "rerank_es_fullrank_like_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_like_range", 0.0, "rerank_es_fullrank_like_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_like_raw_weight", 0.0, "rerank_es_fullrank_like_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_like_raw_pow_weight", 1.0, "rerank_es_fullrank_like_raw_pow_weight"),
    ("fountain_rerank_es_fullrank_like_boost_topk_threshold", 0, "rerank_es_fullrank_like_boost_topk_threshold"),
    ("fountain_rerank_es_fullrank_like_boost_topk_coef", 0.0, "rerank_es_fullrank_like_boost_topk_coef"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_follow_score", 0.0, "rerank_es_fullrank_follow_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_follow_range", 0.0, "rerank_es_fullrank_follow_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_follow_raw_weight", 0.0, "rerank_es_fullrank_follow_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_follow_raw_pow_weight", 1.0, "rerank_es_fullrank_follow_raw_pow_weight"),
    ("fountain_rerank_es_fullrank_follow_boost_topk_threshold", 0, "rerank_es_fullrank_follow_boost_topk_threshold"),
    ("fountain_rerank_es_fullrank_follow_boost_topk_coef", 0.0, "rerank_es_fullrank_follow_boost_topk_coef"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_forward_score", 0.0, "rerank_es_fullrank_forward_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_forward_range", 0.0, "rerank_es_fullrank_forward_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_forward_raw_weight", 0.0, "rerank_es_fullrank_forward_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_forward_raw_pow_weight", 1.0, "rerank_es_fullrank_forward_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_score", 0.0, "rerank_es_fullrank_comment_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_range", 0.0, "rerank_es_fullrank_comment_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_raw_weight", 0.0, "rerank_es_fullrank_comment_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_raw_pow_weight", 1.0, "rerank_es_fullrank_comment_raw_pow_weight"),
    ("rerank_es_fullrank_comment_boost_topk_threshold", 0),
    ("rerank_es_fullrank_comment_boost_topk_coef", 0.0),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_score", 0.0, "rerank_es_fullrank_watchtime_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_range", 0.0, "rerank_es_fullrank_watchtime_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_raw_weight", 0.0, "rerank_es_fullrank_watchtime_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_raw_pow_weight", 1.0, "rerank_es_fullrank_watchtime_raw_pow_weight"),
    ("fountain_rerank_es_fullrank_watchtime_boost_topk_threshold", 0, "rerank_es_fullrank_watchtime_boost_topk_threshold"),
    ("fountain_rerank_es_fullrank_watchtime_boost_topk_coef", 0.0, "rerank_es_fullrank_watchtime_boost_topk_coef"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_profile_score", 0.0, "rerank_es_fullrank_profile_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_profile_range", 0.0, "rerank_es_fullrank_profile_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_profile_raw_weight", 0.0, "rerank_es_fullrank_profile_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_profile_raw_pow_weight", 1.0, "rerank_es_fullrank_profile_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_shortview_score", 0.0, "rerank_es_fullrank_shortview_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_shortview_range", 0.0, "rerank_es_fullrank_shortview_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_shortview_raw_weight", 0.0, "rerank_es_fullrank_shortview_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_shortview_raw_pow_weight", 1.0, "rerank_es_fullrank_shortview_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_l2r_score", 0.0, "rerank_es_fullrank_l2r_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_l2r_range", 0.0, "rerank_es_fullrank_l2r_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_l2r_raw_weight", 0.0, "rerank_es_fullrank_l2r_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_l2r_raw_pow_weight", 1.0, "rerank_es_fullrank_l2r_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pepstr_score", 0.0, "rerank_es_fullrank_pepstr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pepstr_range", 0.0, "rerank_es_fullrank_pepstr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pepstr_raw_weight", 0.0, "rerank_es_fullrank_pepstr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pepstr_raw_pow_weight", 1.0, "rerank_es_fullrank_pepstr_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_outctr_score", 0.0, "rerank_es_fullrank_outctr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_outctr_range", 0.0, "rerank_es_fullrank_outctr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_outctr_raw_weight", 0.0, "rerank_es_fullrank_outctr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_outctr_raw_pow_weight", 1.0, "rerank_es_fullrank_outctr_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_ori_score", 0.0, "rerank_es_fullrank_watchtime_ori_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_ori_range", 0.0, "rerank_es_fullrank_watchtime_ori_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_ori_raw_weight", 0.0, "rerank_es_fullrank_watchtime_ori_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_ori_raw_pow_weight", 1.0, "rerank_es_fullrank_watchtime_ori_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_evtr_v2_score", 0.0, "rerank_es_fullrank_evtr_v2_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_evtr_v2_range", 0.0, "rerank_es_fullrank_evtr_v2_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_evtr_v2_raw_weight", 0.0, "rerank_es_fullrank_evtr_v2_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_evtr_v2_raw_pow_weight", 1.0, "rerank_es_fullrank_evtr_v2_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lstr_score", 0.0, "rerank_es_fullrank_lstr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lstr_range", 0.0, "rerank_es_fullrank_lstr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lstr_raw_weight", 0.0, "rerank_es_fullrank_lstr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lstr_raw_pow_weight", 1.0, "rerank_es_fullrank_lstr_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_collect_score", 0.0, "rerank_es_fullrank_collect_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_collect_range", 0.0, "rerank_es_fullrank_collect_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_collect_raw_weight", 0.0, "rerank_es_fullrank_collect_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_collect_raw_pow_weight", 1.0, "rerank_es_fullrank_collect_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cmef_score", 0.0, "rerank_es_fullrank_cmef_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cmef_range", 0.0, "rerank_es_fullrank_cmef_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cmef_raw_weight", 0.0, "rerank_es_fullrank_cmef_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cmef_raw_pow_weight", 1.0, "rerank_es_fullrank_cmef_raw_pow_weight"),
    ("rerank_es_fullrank_cmef_boost_topk_threshold", 0),
    ("rerank_es_fullrank_cmef_boost_topk_coef", 0.0),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lvtr_ori_score", 0.0, "rerank_es_fullrank_lvtr_ori_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lvtr_ori_range", 0.0, "rerank_es_fullrank_lvtr_ori_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lvtr_ori_raw_weight", 0.0, "rerank_es_fullrank_lvtr_ori_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lvtr_ori_raw_pow_weight", 1.0, "rerank_es_fullrank_lvtr_ori_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pfintr_score", 0.0, "rerank_es_fullrank_pfintr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_printr_range", 0.0, "rerank_es_fullrank_printr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_printr_raw_weight", 0.0, "rerank_es_fullrank_printr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_printr_raw_pow_weight", 1.0, "rerank_es_fullrank_printr_raw_pow_weight"),
    ("fountain_rerank_es_fullrank_pfintr_boost_topk_threshold", 0, "rerank_es_fullrank_pfintr_boost_topk_threshold"),
    ("fountain_rerank_es_fullrank_pfintr_boost_topk_coef", 0.0, "rerank_es_fullrank_pfintr_boost_topk_coef"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_finish_score", 0.0, "rerank_es_fullrank_finish_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_finish_range", 0.0, "rerank_es_fullrank_finish_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_finish_raw_weight", 0.0, "rerank_es_fullrank_finish_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_finish_raw_pow_weight", 1.0, "rerank_es_fullrank_finish_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_next_score", 0.0, "rerank_es_fullrank_next_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_next_range", 0.0, "rerank_es_fullrank_next_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_next_raw_weight", 0.0, "rerank_es_fullrank_next_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_next_raw_pow_weight", 1.0, "rerank_es_fullrank_next_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_opportunity_cost_score", 0.0, "rerank_es_fullrank_opportunity_cost_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_opportunity_cost_range", 0.0, "rerank_es_fullrank_opportunity_cost_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_opportunity_cost_raw_weight", 0.0, "rerank_es_fullrank_opportunity_cost_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_opportunity_cost_raw_pow_weight", 1.0, "rerank_es_fullrank_opportunity_cost_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_trans_pvtr_score", 0.0, "rerank_es_fullrank_trans_pvtr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_trans_pvtr_range", 0.0, "rerank_es_fullrank_trans_pvtr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_trans_pvtr_raw_weight", 0.0, "rerank_es_fullrank_trans_pvtr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_trans_pvtr_raw_pow_weight", 1.0, "rerank_es_fullrank_trans_pvtr_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_ctr_score", 0.0, "rerank_es_fullrank_act_ctr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_ctr_range", 0.0, "rerank_es_fullrank_act_ctr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_ctr_raw_weight", 0.0, "rerank_es_fullrank_act_ctr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_ctr_raw_pow_weight", 1.0, "rerank_es_fullrank_act_ctr_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_topk_mgs_expected_score", 0.0, "rerank_es_fullrank_topk_mgs_expected_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_topk_mgs_expected_range", 0.0, "rerank_es_fullrank_topk_mgs_expected_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_topk_mgs_expected_raw_weight", 0.0, "rerank_es_fullrank_topk_mgs_expected_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_topk_mgs_expected_raw_pow_weight", 1.0, "rerank_es_fullrank_topk_mgs_expected_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_interact_score", 0.0, "rerank_es_fullrank_action_once_interact_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_interact_range", 0.0, "rerank_es_fullrank_action_once_interact_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_interact_raw_weight", 0.0, "rerank_es_fullrank_action_once_interact_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_interact_raw_pow_weight", 1.0, "rerank_es_fullrank_action_once_interact_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_watchtime_score", 0.0, "rerank_es_fullrank_action_once_watchtime_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_watchtime_range", 0.0, "rerank_es_fullrank_action_once_watchtime_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_watchtime_raw_weight", 0.0, "rerank_es_fullrank_action_once_watchtime_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_watchtime_raw_pow_weight", 1.0, "rerank_es_fullrank_action_once_watchtime_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pcpr_score", 0.0, "rerank_es_fullrank_pcpr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pcpr_range", 0.0, "rerank_es_fullrank_pcpr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pcpr_raw_weight", 0.0, "rerank_es_fullrank_pcpr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pcpr_raw_pow_weight", 1.0, "rerank_es_fullrank_pcpr_raw_pow_weight"),
    ("fountain_rerank_es_fullrank_pcpr_boost_topk_threshold", 0, "rerank_es_fullrank_pcpr_boost_topk_threshold"),
    ("fountain_rerank_es_fullrank_pcpr_boost_topk_coef", 0.0, "rerank_es_fullrank_pcpr_boost_topk_coef"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_wtd_score", 0.0, "rerank_es_fullrank_act_wtd_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_wtd_range", 0.0, "rerank_es_fullrank_act_wtd_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_wtd_raw_weight", 0.0, "rerank_es_fullrank_act_wtd_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_wtd_raw_pow_weight", 1.0, "rerank_es_fullrank_act_wtd_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pure_value_score", 0.0, "rerank_es_fullrank_pure_value_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pure_value_range", 0.0, "rerank_es_fullrank_pure_value_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pure_value_raw_weight", 0.0, "rerank_es_fullrank_pure_value_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pure_value_raw_pow_weight", 1.0, "rerank_es_fullrank_pure_value_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_distill_rerank_score", 0.0, "rerank_es_fullrank_distill_rerank_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_distill_rerank_range", 0.0, "rerank_es_fullrank_distill_rerank_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_distill_rerank_raw_weight", 0.0, "rerank_es_fullrank_distill_rerank_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_distill_rerank_raw_pow_weight", 1.0, "rerank_es_fullrank_distill_rerank_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_ltr_score", 0.0, "rerank_es_fullrank_comment_ltr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_ltr_range", 0.0, "rerank_es_fullrank_comment_ltr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_ltr_raw_weight", 0.0, "rerank_es_fullrank_comment_ltr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_ltr_raw_pow_weight", 1.0, "rerank_es_fullrank_comment_ltr_raw_pow_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_xgb_ltr_score", 0.0, "rerank_es_fullrank_xgb_ltr_score"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_xgb_ltr_range", 0.0, "rerank_es_fullrank_xgb_ltr_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_xgb_ltr_raw_weight", 0.0, "rerank_es_fullrank_xgb_ltr_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_xgb_ltr_raw_pow_weight", 1.0, "rerank_es_fullrank_xgb_ltr_raw_pow_weight"),
    ("fountain_rerank_enable_es_effective_follow_rate_add", False),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_effective_follow_rate_score", 0.0, "rerank_es_fullrank_effective_follow_rate_score_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_effective_follow_rate_raw_weight", 0.0, "rerank_es_fullrank_effective_follow_rate_raw_weight"),
    ("fountain_rerank_enable_es_fr_living_mix_add", False),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fr_living_mix_score_score", 0.0, "rerank_es_fullrank_fr_living_mix_score_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fr_living_mix_score_range", 0.0, "rerank_es_fullrank_fr_living_mix_score_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fr_living_mix_score_raw_weight", 0.0, "rerank_es_fullrank_fr_living_mix_score_raw_weight"),
    ("fountain_rerank_enable_es_good_item_similary_add", False),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_good_item_similary_score", 0.0, "rerank_es_good_item_similary_score_weight"),
    ("fountain_rerank_enable_es_ordinal_wtd_add", False),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fullrank_ltr_v4_fountain_ordinal_wtd_score", 0.0, "rerank_es_fullrank_ltr_ordinal_wtd_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fullrank_ltr_v4_fountain_ordinal_wtd_range", 0.0, "rerank_es_fullrank_ltr_ordinal_wtd_range"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fullrank_ltr_v4_fountain_ordinal_wtd_raw_weight", 0.0, "rerank_es_fullrank_ltr_ordinal_wtd_raw_weight"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fullrank_ltr_v4_fountain_ordinal_wtd_raw_pow_weight", 1.0, "rerank_es_fullrank_ltr_ordinal_wtd_raw_pow_weight"),
    ("fountain_rerank_enable_source_related_score_add", False),
    ("dpp_fountain_rerank_rerank_es_source_related_score_weight", 0.0, "rerank_es_source_related_score_weight"),
    ("dpp_fountain_rerank_rerank_es_source_related_score_range", 0.0, "rerank_es_source_related_score_range"),
    ("dpp_fountain_rerank_rerank_es_source_related_score_raw_weight", 0.0, "rerank_es_source_related_score_raw_weight"),
    ("dpp_fountain_rerank_rerank_es_source_related_score_raw_pow_weight", 1.0, "rerank_es_source_related_score_raw_pow_weight"),
    ("fountain_rerank_enable_fullrank_ltr_comment_staytime_add", False),
    ("rerank_es_fullrank_ltr_comment_staytime_weight", 0.0),
    ("rerank_es_fullrank_ltr_comment_staytime_range", 0.0),
    ("rerank_es_fullrank_ltr_comment_staytime_raw_weight", 0.0),
    ("rerank_es_fullrank_ltr_comment_staytime_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_fullrank_ltr_d2co_playtime_add", False),
    ("rerank_es_fullrank_ltr_d2co_playtime_weight", 0.0),
    ("rerank_es_fullrank_ltr_d2co_playtime_range", 0.0),
    ("rerank_es_fullrank_ltr_d2co_playtime_raw_weight", 0.0),
    ("rerank_es_fullrank_ltr_d2co_playtime_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_rerank_gen_score_list_add", False),
    ("rerank_es_rerank_gen_score_list_weight", 0.0),
    ("rerank_es_rerank_gen_score_list_range", 0.0),
    ("rerank_es_rerank_gen_score_list_raw_weight", 0.0),
    ("rerank_es_rerank_gen_score_list_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_fullrank_ltr_ord2q_add", False),
    ("fountain_rerank_es_fullrank_ltr_ord2q_weight", 0.0),
    ("fountain_rerank_es_fullrank_ltr_ord2q_range", 0.0),
    ("fountain_rerank_es_fullrank_ltr_ord2q_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_ltr_ord2q_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_fullrank_ltr_dfvr_add", False),
    ("fountain_rerank_es_fullrank_ltr_dfvr_weight", 0.0),
    ("fountain_rerank_es_fullrank_ltr_dfvr_range", 0.0),
    ("fountain_rerank_es_fullrank_ltr_dfvr_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_ltr_dfvr_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_fullrank_ltr_lph_add", False),
    ("fountain_rerank_es_fullrank_ltr_lph_weight", 0.0),
    ("fountain_rerank_es_fullrank_ltr_lph_range", 0.0),
    ("fountain_rerank_es_fullrank_ltr_lph_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_ltr_lph_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_fullrank_pdfvr_add", False),
    ("fountain_rerank_es_fullrank_pdfvr_weight", 0.0),
    ("fountain_rerank_es_fullrank_pdfvr_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_pdfvr_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_fullrank_pwtd_v2_playtime_add", False),
    ("fountain_rerank_es_fullrank_pwtd_v2_playtime_weight", 0.0),
    ("fountain_rerank_es_fullrank_pwtd_v2_playtime_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_pwtd_v2_playtime_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_fullrank_esnn_ltr_add", False),
    ("fountain_rerank_es_fullrank_esnn_ltr_weight", 0.0),
    ("fountain_rerank_es_fullrank_esnn_ltr_range", 0.0),
    ("fountain_rerank_es_fullrank_esnn_ltr_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_esnn_ltr_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_es_i2i_dynamic_score_add", False),
    ("fountain_rerank_es_i2i_dynamic_score_weight", 0.0),
    ("fountain_rerank_es_i2i_dynamic_score_raw_weight", 0.0),
    ("fountain_rerank_es_i2i_dynamic_score_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_es_final_fr_consecutive_nonclick_score_add", False),
    ("fountain_rerank_es_final_fr_consecutive_nonclick_score_weight", 0.0),
    ("fountain_rerank_es_final_fr_consecutive_nonclick_score_raw_weight", 0.0),
    ("fountain_rerank_es_final_fr_consecutive_nonclick_score_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_es_fullrank_min_wt_rank_reci_add", False),
    ("fountain_rerank_es_fullrank_min_wt_rank_reci_weight", 0.0),
    ("fountain_rerank_es_fullrank_min_wt_rank_reci_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_min_wt_rank_reci_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_es_fullrank_reco_base_model_gen_time_wt", False),
    ("fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_weight", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_range", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_es_fullrank_reco_base_model_evtr", False),
    ("fountain_rerank_es_fullrank_reco_base_model_evtr_weight", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_evtr_range", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_evtr_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_evtr_raw_pow_weight", 1.0),
    ("fountain_rerank_enable_es_fullrank_reco_base_model_lvtr", False),
    ("fountain_rerank_es_fullrank_reco_base_model_lvtr_weight", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_lvtr_range", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_lvtr_raw_weight", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_lvtr_raw_pow_weight", 1.0),

    # rerank_gen_candidate_list - es_mul
    ("fountain_rerank_dpp_sequence_num_multiple", 1, "rerank_dpp_sequence_num_multiple"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_click_score_addAndMul", 0.0, "rerank_es_fullrank_click_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_click_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_click_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_click_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_click_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_like_score_addAndMul", 0.0, "rerank_es_fullrank_like_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_like_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_like_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_like_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_like_raw_pow_weight_addAndMul"),
    ("fountain_rerank_es_fullrank_like_boost_topk_threshold_addAndMul", 0, "rerank_es_fullrank_like_boost_topk_threshold_addAndMul"),
    ("fountain_rerank_es_fullrank_like_boost_topk_coef_addAndMul", 0.0, "rerank_es_fullrank_like_boost_topk_coef_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_follow_score_addAndMul", 0.0, "rerank_es_fullrank_follow_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_follow_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_follow_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_follow_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_follow_raw_pow_weight_addAndMul"),
    ("fountain_rerank_es_fullrank_follow_boost_topk_threshold_addAndMul", 0, "rerank_es_fullrank_follow_boost_topk_threshold_addAndMul"),
    ("fountain_rerank_es_fullrank_follow_boost_topk_coef_addAndMul", 0.0, "rerank_es_fullrank_follow_boost_topk_coef_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_score_addAndMul", 0.0, "rerank_es_fullrank_comment_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_comment_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_comment_raw_pow_weight_addAndMul"),
    ("rerank_es_fullrank_comment_boost_topk_threshold_addAndMull", 0),
    ("rerank_es_fullrank_comment_boost_topk_coef_addAndMul", 0.0),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_score_addAndMul", 0.0, "rerank_es_fullrank_watchtime_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_watchtime_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_watchtime_raw_pow_weight_addAndMul"),
    ("fountain_rerank_es_fullrank_watchtime_boost_topk_threshold_addAndMul", 0, "rerank_es_fullrank_watchtime_boost_topk_threshold_addAndMul"),
    ("fountain_rerank_es_fullrank_watchtime_boost_topk_coef_addAndMul", 0.0, "rerank_es_fullrank_watchtime_boost_topk_coef_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_profile_score_addAndMul", 0.0, "rerank_es_fullrank_profile_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_profile_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_profile_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_profile_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_profile_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_shortview_score_addAndMul", 0.0, "rerank_es_fullrank_shortview_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_shortview_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_shortview_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_shortview_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_shortview_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_l2r_score_addAndMul", 0.0, "rerank_es_fullrank_l2r_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_l2r_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_l2r_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_l2r_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_l2r_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pepstr_score_addAndMul", 0.0, "rerank_es_fullrank_pepstr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pepstr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_pepstr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pepstr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_pepstr_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_outctr_score_addAndMul", 0.0, "rerank_es_fullrank_outctr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_outctr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_outctr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_outctr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_outctr_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_ori_score_addAndMul", 0.0, "rerank_es_fullrank_watchtime_ori_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_ori_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_watchtime_ori_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_watchtime_ori_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_watchtime_ori_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_evtr_v2_score_addAndMul", 0.0, "rerank_es_fullrank_evtr_v2_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_evtr_v2_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_evtr_v2_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_evtr_v2_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_evtr_v2_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lstr_score_addAndMul", 0.0, "rerank_es_fullrank_lstr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lstr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_lstr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lstr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_lstr_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_collect_score_addAndMul", 0.0, "rerank_es_fullrank_collect_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_collect_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_collect_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_collect_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_collect_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cmef_score_addAndMul", 0.0, "rerank_es_fullrank_cmef_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cmef_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_cmef_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cmef_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_cmef_raw_pow_weight_addAndMul"),
    ("rerank_es_fullrank_cmef_boost_topk_threshold_addAndMul", 0),
    ("rerank_es_fullrank_cmef_boost_topk_coef_addAndMul", 0.0),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lvtr_ori_score_addAndMul", 0.0, "rerank_es_fullrank_lvtr_ori_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lvtr_ori_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_lvtr_ori_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_lvtr_ori_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_lvtr_ori_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pfintr_score_addAndMul", 0.0, "rerank_es_fullrank_pfintr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pfintr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_pfintr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pfintr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_pfintr_raw_pow_weight_addAndMul"),
    ("fountain_rerank_es_fullrank_pfintr_boost_topk_threshold_addAndMul", 0, "rerank_es_fullrank_pfintr_boost_topk_threshold_addAndMul"),
    ("fountain_rerank_es_fullrank_pfintr_boost_topk_coef_addAndMul", 0.0, "rerank_es_fullrank_pfintr_boost_topk_coef_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_finish_score_addAndMul", 0.0, "rerank_es_fullrank_finish_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_finish_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_finish_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_finish_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_finish_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_next_score_addAndMul", 0.0, "rerank_es_fullrank_next_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_next_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_next_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_next_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_next_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_opportunity_cost_score_addAndMul", 0.0, "rerank_es_fullrank_opportunity_cost_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_opportunity_cost_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_opportunity_cost_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_opportunity_cost_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_opportunity_cost_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cl_tran_score_addAndMul", 0.0, "rerank_es_fullrank_cl_tran_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cl_tran_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_cl_tran_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_cl_tran_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_cl_tran_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_trans_pvtr_score_addAndMul", 0.0, "rerank_es_fullrank_trans_pvtr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_trans_pvtr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_trans_pvtr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_trans_pvtr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_trans_pvtr_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_ctr_score_addAndMul", 0.0, "rerank_es_fullrank_act_ctr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_ctr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_act_ctr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_ctr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_act_ctr_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_topk_mgs_expected_score_addAndMul", 0.0, "rerank_es_fullrank_topk_mgs_expected_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_topk_mgs_expected_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_topk_mgs_expected_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_topk_mgs_expected_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_topk_mgs_expected_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_interact_score_addAndMul", 0.0, "rerank_es_fullrank_action_once_interact_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_interact_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_action_once_interact_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_interact_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_action_once_interact_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_watchtime_score_addAndMul", 0.0, "rerank_es_fullrank_action_once_watchtime_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_watchtime_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_action_once_watchtime_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_action_once_watchtime_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_action_once_watchtime_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pcpr_score_addAndMul", 0.0, "rerank_es_fullrank_pcpr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pcpr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_pcpr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pcpr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_pcpr_raw_pow_weight_addAndMul"),
    ("fountain_rerank_es_fullrank_pcpr_boost_topk_threshold_addAndMul", 0, "rerank_es_fullrank_pcpr_boost_topk_threshold_addAndMul"),
    ("fountain_rerank_es_fullrank_pcpr_boost_topk_coef_addAndMul", 0.0, "rerank_es_fullrank_pcpr_boost_topk_coef_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_wtd_score_addAndMul", 0.0, "rerank_es_fullrank_act_wtd_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_wtd_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_act_wtd_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_act_wtd_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_act_wtd_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pure_value_score_addAndMul", 0.0, "rerank_es_fullrank_pure_value_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pure_value_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_pure_value_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_pure_value_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_pure_value_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_distill_rerank_score_addAndMul", 0.0, "rerank_es_fullrank_distill_rerank_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_distill_rerank_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_distill_rerank_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_distill_rerank_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_distill_rerank_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_ltr_score_addAndMul", 0.0, "rerank_es_fullrank_comment_ltr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_ltr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_comment_ltr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_comment_ltr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_comment_ltr_raw_pow_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_xgb_ltr_score_addAndMul", 0.0, "rerank_es_fullrank_xgb_ltr_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_xgb_ltr_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_xgb_ltr_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_xgb_ltr_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_xgb_ltr_raw_pow_weight_addAndMul"),
    ("fountain_rerank_enable_es_fr_living_mix_mul", False),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fr_living_mix_score_score_addAndMul", 0.0, "rerank_es_fullrank_fr_living_mix_score_score_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fr_living_mix_score_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_fr_living_mix_score_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fr_living_mix_score_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_fr_living_mix_score_raw_pow_weight_addAndMul"),
    ("fountain_rerank_enable_es_ordinal_wtd_mul", False),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fullrank_ltr_v4_fountain_ordinal_wtd_score_addAndMul", 0.0, "rerank_es_fullrank_ltr_ordinal_wtd_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fullrank_ltr_v4_fountain_ordinal_wtd_raw_weight_addAndMul", 0.0, "rerank_es_fullrank_ltr_ordinal_wtd_raw_weight_addAndMul"),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_fullrank_ltr_v4_fountain_ordinal_wtd_raw_pow_weight_addAndMul", 1.0, "rerank_es_fullrank_ltr_ordinal_wtd_raw_pow_weight_addAndMul"),
    ("fountain_rerank_enable_source_related_score_mul", False),
    ("dpp_fountain_rerank_es_source_related_score_weight_mul", 0.0, "rerank_es_source_related_score_weight_mul"),
    ("dpp_fountain_rerank_es_source_related_score_raw_weight_mul", 0.0, "rerank_es_source_related_score_raw_weight_mul"),
    ("dpp_fountain_rerank_rerank_es_source_related_score_raw_pow_weight_mul", 1.0, "rerank_es_source_related_score_raw_pow_weight_mul"),
    ("fountain_rerank_enable_fullrank_ltr_comment_staytime_mul", False),
    ("rerank_es_fullrank_ltr_comment_staytime_weight_mul", 0.0),
    ("rerank_es_fullrank_ltr_comment_staytime_range", 0.0),
    ("rerank_es_fullrank_ltr_comment_staytime_raw_weight_mul", 0.0),
    ("rerank_es_fullrank_ltr_comment_staytime_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_fullrank_ltr_d2co_playtime_mul", False),
    ("rerank_es_fullrank_ltr_d2co_playtime_weight_mul", 0.0),
    ("rerank_es_fullrank_ltr_d2co_playtime_range", 0.0),
    ("rerank_es_fullrank_ltr_d2co_playtime_raw_weight_mul", 0.0),
    ("rerank_es_fullrank_ltr_d2co_playtime_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_rerank_gen_score_list_mul", False),
    ("rerank_es_rerank_gen_score_list_weight_mul", 0.0),
    ("rerank_es_rerank_gen_score_list_range_mul", 0.0),
    ("rerank_es_rerank_gen_score_list_raw_weight_mul", 0.0),
    ("rerank_es_rerank_gen_score_list_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_fullrank_forward_mul", False),
    ("fountain_rerank_es_fullrank_forward_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_forward_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_forward_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_fullrank_ltr_ord2q_mul", False),
    ("fountain_rerank_es_fullrank_ltr_ord2q_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_ltr_ord2q_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_ltr_ord2q_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_fullrank_ltr_dfvr_mul", False),
    ("fountain_rerank_es_fullrank_ltr_dfvr_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_ltr_dfvr_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_ltr_dfvr_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_fullrank_ltr_lph_mul", False),
    ("fountain_rerank_es_fullrank_ltr_lph_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_ltr_lph_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_ltr_lph_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_fullrank_pdfvr_mul", False),
    ("fountain_rerank_es_fullrank_pdfvr_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_pdfvr_range", 0.0),
    ("fountain_rerank_es_fullrank_pdfvr_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_pdfvr_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_fullrank_pwtd_v2_playtime_mul", False),
    ("fountain_rerank_es_fullrank_pwtd_v2_playtime_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_pwtd_v2_playtime_range", 0.0),
    ("fountain_rerank_es_fullrank_pwtd_v2_playtime_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_pwtd_v2_playtime_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_fullrank_esnn_ltr_mul", False),
    ("fountain_rerank_es_fullrank_esnn_ltr_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_esnn_ltr_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_esnn_ltr_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_i2i_dynamic_score_mul", False),
    ("fountain_rerank_es_i2i_dynamic_score_addAndMul", 0.0),
    ("rerank_es_i2i_dynamic_score_range", 0.0),
    ("fountain_rerank_es_i2i_dynamic_score_rerank_raw_weight_addAndMul", 0.0),
    ("fountain_rerank_es_i2i_dynamic_score_rerank_raw_pow_weight_addAndMul", 1.0),
    ("fountain_rerank_enable_final_fr_consecutive_nonclick_score_mul", False),
    ("fountain_rerank_es_final_fr_consecutive_nonclick_score_addAndMul", 0.0),
    ("rerank_es_final_fr_consecutive_nonclick_score_range", 0.0),
    ("fountain_rerank_es_final_fr_consecutive_nonclick_score_rerank_raw_weight_addAndMul", 0.0),
    ("fountain_rerank_es_final_fr_consecutive_nonclick_score_rerank_raw_pow_weight_addAndMul", 1.0),
    ("fountain_rerank_enable_es_fullrank_min_wt_rank_reci_mul", False),
    ("fountain_rerank_es_fullrank_min_wt_rank_reci_range", 0.0),
    ("fountain_rerank_es_fullrank_min_wt_rank_reci_weight_addAndMul", 0.0),
    ("fountain_rerank_es_fullrank_min_wt_rank_reci_raw_weight_addAndMul", 0.0),
    ("fountain_rerank_es_fullrank_min_wt_rank_reci_raw_pow_weight_addAndMul", 1.0),
    ("fountain_rerank_enable_es_fullrank_reco_base_model_gen_time_wt_mul", False),
    ("fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_range_addAndMul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_weight_addAndMul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_raw_weight_addAndMul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_raw_pow_weight_addAndMul", 1.0),
    ("fountain_rerank_enable_es_fullrank_reco_base_model_evtr_mul", False),
    ("fountain_rerank_es_fullrank_reco_base_model_evtr_range_mul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_evtr_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_evtr_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_evtr_raw_pow_weight_mul", 1.0),
    ("fountain_rerank_enable_es_fullrank_reco_base_model_lvtr_mul", False),
    ("fountain_rerank_es_fullrank_reco_base_model_lvtr_range_mul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_lvtr_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_lvtr_raw_weight_mul", 0.0),
    ("fountain_rerank_es_fullrank_reco_base_model_lvtr_raw_pow_weight_mul", 1.0),

    # rerank hetu single list
    ("fountain_enable_ensemble_hetu_fusion_score", False), # 河图 fusion 单队列总开关
    ("fountain_rerank_hetu_fusion_beam_size", 6),
    ("fountain_enable_ensemble_fullrank_original_list", False), # 精排原序 单队列总开关
    ("fountain_ensemble_fullrank_original_list_beam_size", 1),
    ("fountain_enable_rerank_hetu_fusion_padding_hetu", False),
    ("fountain_rerank_hetu_fusion_calc_score_mode", 0),
    ("fountain_rerank_hetu_fusion_calc_score_hetu_weight", 0.5),
    ("fountain_rerank_hetu_fusion_calc_score_original_weight", 0.1),
    ("fountain_rerank_hetu_fusion_user_degree_bucket_weights_str", "0:1.0;1:1.5;2:1.5;3:1.2;4:0.5;5:1.5;6:0.1;7:1.0"),
    ("fountain_rerank_hetu_fusion_enable_personalized_adjust", False),
    ("fountain_rerank_hetu_fusion_photo_cnt_bucket_weights_str", "0:2.0;10000:1.8;50000:1.5;100000:1.0;200000:1.0;500000:0.1;1000000:0.0"),
    ("fountain_rerank_hetu_fusion_shuffle_topk", 6),
    ("fountain_enable_rerank_hetu_fusion_score_use_power_calc_v2", False),
    ("fountain_enable_rerank_hetu_fusion_score_user_new_proportion", True),
    ("fountain_fullrank_hetu_fusion_head_boost_index", 6),
    ("fountain_fullrank_hetu_fusion_tail_discount_index", 6),
    ("fountain_rerank_hetu_fusion_sim_pevtr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_pevtr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pevtr_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pfintr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_pfintr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pfintr_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pvtr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_pvtr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pvtr_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pltr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_pltr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pltr_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pcmtr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_pcmtr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pcmtr_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pwtr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_pwtr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pwtr_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_act_ctr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_act_ctr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_act_ctr_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_action_once_interact_weight", 0.0),
    ("fountain_rerank_hetu_fusion_action_once_interact_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_action_once_interact_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pevtr_v2_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_pevtr_v2_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_pevtr_v2_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_psvr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_psvr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_psvr_tail_discount_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_plvtr_weight", 0.0),
    ("fountain_rerank_hetu_fusion_sim_plvtr_head_boost_coef", 1.0),
    ("fountain_rerank_hetu_fusion_sim_plvtr_tail_discount_coef", 1.0),

    # rerank_gen_list
    ("fountain_enable_dpp_gen_list", True),
    ("fountain_enable_user_need_break_cocoon_rerank", False),
    ("fountain_rerank_dpp_relevance_score_theta_user_need_break_cocoon_adjust_coef", 1.0),
    ("fountain_rerank_dpp_diversity_list_size", 6),
    ("fountain_dpp_beam_size", 1),
    ("fountain_rerank_dpp_sim_matrix_norm_type", 0),
    ("fountain_rerank_dpp_sim_matrix_alpha", 1.0),
    ("fountain_rerank_dpp_relevance_score_theta", 0.7),
    ("fountain_rerank_dpp_max_hetu1_regular_num", 2),
    ("fountain_rerank_ssd_max_hetu1_regular_num", 2),
    ("fountain_enable_ssd_gen_list", False),
    ("fountain_ssd_rank_score_weight", 1.0),
    ("fountain_dpp_use_set_filter", False),
    ("fountain_dpp_set_max_filter_cnt", 0),
    ("fountain_ssd_filter_final_cnt", 40),

    # rerank_list_predict
    ("fountain_rerank_kess_service_v2_produce_v4", "grpc_krpFountainRerankPredServerV2"),
    ("fountain_rr_play_watch_table_kconf", "reco.author.play_buck_duration"),
    # rerank flash eval predict
    ("enable_fountain_rerank_flash_eval_model_predict", False),
    ("fountain_rerank_flash_eval_model_kess_service", "grpc_fountain_rerank_model_flash_evaluator_server"),
    ("fountain_rerank_flash_eval_model_request_type", "kai_predict"),
    ("fountain_rerank_flash_eval_model_partition_size", 60),

    # 社交分享
    ("fountain_rerank_enable_adjust_forward_social_params", 0),
    ("dpp_fountain_rerank_gen_seed_ensemble_fullrank_forward_score_social_coeff", 1.0),

    # 多样性随着刷次增加逐渐变得更加多样
    ("fountain_rerank_dpp_enable_diversity_increase_by_page", False),
    ("fountain_rerank_dpp_diversity_increase_by_page_weight", 1.0),
    ("fountain_rerank_ssd_enable_diversity_increase_by_page", False),
    ("fountain_rerank_ssd_diversity_increase_by_page_weight", 1.0),

    # 引入hetu_v4 emb, 默认不打开
    ("fountain_rerank_enable_import_hetu_emb_v4", False),
    ("fountain_rerank_enable_select_list_hetu_emb_v4", False),
    ("fountain_rerank_dpp_diversity_enable_hetu_emb_v4", False),
    ("fountain_rerank_hetu_emb_switch", 1),

    # es topk shuffle/resort
    ("enable_fountain_rerank_es_topk_shuffle", False),
    ("enable_fountain_rerank_es_topk_resort", False),
    ("fountain_rerank_es_topk_shuffle_window_size", 10),
    ("fountain_rerank_es_topk_resort_window_size", 10),
    ("fountain_rerank_es_topk_shuffle_target_candidate_num", 1),
    ("fountain_rerank_es_topk_resort_target_candidate_num", 1),
    ("enable_fountain_rerank_es_topk_shuffle_mul", False),
    ("enable_fountain_rerank_es_topk_resort_mul", False),
    ("fountain_rerank_es_topk_shuffle_window_size_mul", 10),
    ("fountain_rerank_es_topk_resort_window_size_mul", 10),
    ("fountain_rerank_es_topk_shuffle_target_candidate_num_mul", 1),
    ("fountain_rerank_es_topk_resort_target_candidate_num_mul", 1),
    ("fountain_rerank_es_topk_resort_pevtr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_pcpr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_pfintr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_pvtr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_plvtr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_pltr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_pltr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_pcmtr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_pwtr_weight", 0.0),
    ("fountain_rerank_es_topk_resort_psvr_weight", 0.0),

    # 低互动人群提权时长队列
    ("enable_fountain_rerank_es_playtime_adjust", False),
    ("fountain_rerank_es_fullrank_pfintr_score_coeff", 1.0),
    ("fountain_rerank_es_fullrank_watchtime_score_coeff", 1.0),
    ("fountain_rerank_es_fullrank_watchtime_ori_score_coeff", 1.0),
    ("fountain_rerank_es_fullrank_evtr_v2_score_coeff", 1.0),
    ("fountain_rerank_es_fullrank_pfintr_score_addAndMul_coeff", 1.0),
    ("fountain_rerank_es_fullrank_watchtime_score_addAndMul_coeff", 1.0),
    ("fountain_rerank_es_fullrank_watchtime_ori_score_addAndMul_coeff", 1.0),
    ("fountain_rerank_es_fullrank_evtr_v2_score_addAndMul_coeff", 1.0),
    ("fountain_rerank_es_fullrank_click_score_coeff", 1.0),
    ("fountain_rerank_es_fullrank_click_score_addAndMul_coeff", 1.0),
    ("fountain_rerank_es_fullrank_shortview_score_coeff", 1.0),
    ("fountain_rerank_es_fullrank_shortview_score_addAndMul_coeff", 1.0),
  ]

def gen_beamsearch_filter_abtest():
    res = []
    queues = ["click", "like", "follow", "forward", "comment", "profile", "longview",
             "watchtime", "shortview", "l2r", "pepstr", "outctr", "shortviewinorder", "neg_feedback_discount",
             "watchtime_ori", "fusion_pctr", "fusion_pcltr"]
    weights = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    prefix = "fountain_rerank_beamsearch_filter_"
    for i, q in enumerate(queues) :
      res.append((prefix + q + "_score", weights[i]))
    return res

abtest_is_or_not_rerank = [
    {
      "param_name": "enable_use_fountain_rerank",
      "param_type": "int",
      "attr_name": "enable_use_fountain_rerank",
      "default_value": 0
    }
]

def splash_rerank_gen_ensemble_abtest():
    res = [
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_click_score", 1.7),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_click_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_click_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_click_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_like_score", 0.8),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_like_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_like_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_like_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_follow_score", 0.5),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_follow_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_follow_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_follow_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_forward_score", 0.1),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_forward_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_forward_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_forward_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_comment_score", 0.5),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_comment_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_comment_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_comment_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_profile_score", 0.3),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_profile_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_profile_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_profile_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_longview_score", 0.6),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_longview_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_longview_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_longview_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_watchtime_score", 1.4),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_watchtime_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_watchtime_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_watchtime_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_shortview_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_shortview_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_shortview_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_shortview_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_l2r_score", 0.5),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_l2r_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_l2r_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_l2r_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pepstr_score", 0.3),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pepstr_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pepstr_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pepstr_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_outctr_score", 0.6),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_outctr_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_outctr_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_outctr_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_shortviewinorder_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_shortviewinorder_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_shortviewinorder_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_shortviewinorder_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_neg_feedback_discount_score", 0.5),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_neg_feedback_discount_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_neg_feedback_discount_range", 0.2),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_neg_feedback_discount_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_watchtime_ori_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_watchtime_ori_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_watchtime_ori_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_watchtime_ori_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_evtr_v2_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_evtr_v2_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_evtr_v2_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_evtr_v2_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_lstr_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_lstr_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_lstr_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_lstr_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_collect_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_collect_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_collect_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_collect_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cmef_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cmef_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cmef_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cmef_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_lvtr_ori_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_lvtr_ori_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_lvtr_ori_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_lvtr_ori_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pfintr_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pfintr_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pfintr_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pfintr_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_finish_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_finish_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_finish_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_finish_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_next_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_next_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_next_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_next_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_slide_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_slide_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_slide_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_slide_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cl_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cl_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cl_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cl_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_act_ctr_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_act_ctr_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_act_ctr_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_act_ctr_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_fusion_pctr_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_fusion_pctr_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_fusion_pctr_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_fusion_pctr_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_fusion_pcltr_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_fusion_pcltr_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_fusion_pcltr_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_fusion_pcltr_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cl_play_time_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cl_play_time_lower_bound", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cl_play_time_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_cl_play_time_use_proportion", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pcpr_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_pcpr_range", 0.0),

      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_sim_pcmef_weight", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_fullrank_sim_pcmef_range", 0.0),

      # duration 队列参数
      ("fountain_splash_rerank_gen_seed_ensemble_duration_0_7s_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_0_7s_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_0_7s_reverse_order", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_7_9s_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_7_9s_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_7_9s_reverse_order", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_9_12s_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_9_12s_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_9_12s_reverse_order", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_12_17s_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_12_17s_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_12_17s_reverse_order", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_17_20s_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_17_20s_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_17_20s_reverse_order", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_20_58s_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_20_58s_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_20_58s_reverse_order", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_gt_58s_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_gt_58s_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_gt_58s_reverse_order", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_gt_120s_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_gt_120s_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_duration_gt_120s_reverse_order", 0),

      # 相关分队列
      ("fountain_splash_rerank_gen_seed_ensemble_source_related_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_source_related_score_range", 0.0),

      # relate ltr 队列参数
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_fusion_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_fusion_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_act_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_act_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_act_v2_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_act_v2_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_wtd_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_wtd_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_lvtr_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_lvtr_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_svtr_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_svtr_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_svtr_score_reverse_order", 0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_like_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_like_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_follow_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_follow_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_comment_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_comment_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_next_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_next_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_relate_evtr_score_score", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_splash_fullrank_ltr_relate_evtr_score_range", 0.0),
      # 审核队列
      ("fountain_splash_rerank_gen_seed_ensemble_bad_item_similary_score_weight", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_bad_item_similary_score_range", 0.0),
      ("fountain_splash_rerank_gen_seed_ensemble_bad_item_similary_score_reverse_order", True),
    ]
    return res

def gen_splash_rerank_abtest():
    return get_splash_rerank_abtest() + splash_rerank_gen_ensemble_abtest() + gen_beamsearch_filter_abtest()

abtest_is_or_not_splash_rerank = [
    {
      "param_name": "enable_use_fountain_splash_rerank",
      "param_type": "int",
      "attr_name": "enable_use_fountain_splash_rerank",
      "default_value": 0
    }
]
