es_add_queues = [
  {
    "score_attr": "fullrank_sim_pevtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_click_score}}",
    "disturbance_range": "{{rerank_es_fullrank_click_range}}",
    "pow_alpha": "{{rerank_es_fullrank_click_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_click_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pltr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_like_score}}",
    "disturbance_range": "{{rerank_es_fullrank_like_range}}",
    "pow_alpha": "{{rerank_es_fullrank_like_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_like_raw_pow_weight}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_like_boost_topk_threshold}}",
    "boost_topk_coef": "{{rerank_es_fullrank_like_boost_topk_coef}}",
  },
  {
    "score_attr": "fullrank_sim_pwtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_follow_score}}",
    "disturbance_range": "{{rerank_es_fullrank_follow_range}}",
    "pow_alpha": "{{rerank_es_fullrank_follow_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_follow_raw_pow_weight}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_follow_boost_topk_threshold}}",
    "boost_topk_coef": "{{rerank_es_fullrank_follow_boost_topk_coef}}",
  },
  {
    "score_attr": "fullrank_sim_pftr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_forward_score}}",
    "disturbance_range": "{{rerank_es_fullrank_forward_range}}",
    "pow_alpha": "{{rerank_es_fullrank_forward_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_forward_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pcmtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_comment_score}}",
    "disturbance_range": "{{rerank_es_fullrank_comment_range}}",
    "pow_alpha": "{{rerank_es_fullrank_comment_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_comment_raw_pow_weight}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_comment_boost_topk_threshold}}",
    "boost_topk_coef": "{{rerank_es_fullrank_comment_boost_topk_coef}}",
  },
  {
    "score_attr": "fullrank_sim_pptr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_profile_score}}",
    "disturbance_range": "{{rerank_es_fullrank_profile_range}}",
    "pow_alpha": "{{rerank_es_fullrank_profile_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_profile_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pwatchtime_no_bias",
    "enable": True,
    "weight": "{{rerank_es_fullrank_watchtime_score}}",
    "disturbance_range": "{{rerank_es_fullrank_watchtime_range}}",
    "pow_alpha": "{{rerank_es_fullrank_watchtime_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_watchtime_raw_pow_weight}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_watchtime_boost_topk_threshold}}",
    "boost_topk_coef": "{{rerank_es_fullrank_watchtime_boost_topk_coef}}",
  },
  {
    "score_attr": "fullrank_sim_psvr",
    "enable": True,
    "reverse_order": True,
    "weight": "{{rerank_es_fullrank_shortview_score}}",
    "disturbance_range": "{{rerank_es_fullrank_shortview_range}}",
    "pow_alpha": "{{rerank_es_fullrank_shortview_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_shortview_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_ltr_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_l2r_score}}",
    "disturbance_range": "{{rerank_es_fullrank_l2r_range}}",
    "pow_alpha": "{{rerank_es_fullrank_l2r_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_l2r_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pepstr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_pepstr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_pepstr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_pepstr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_pepstr_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_out_pctr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_outctr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_outctr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_outctr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_outctr_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pvtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_watchtime_ori_score}}",
    "disturbance_range": "{{rerank_es_fullrank_watchtime_ori_range}}",
    "pow_alpha": "{{rerank_es_fullrank_watchtime_ori_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_watchtime_ori_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_detail_new_pevtr_v2",
    "enable": True,
    "weight": "{{rerank_es_fullrank_evtr_v2_score}}",
    "disturbance_range": "{{rerank_es_fullrank_evtr_v2_range}}",
    "pow_alpha": "{{rerank_es_fullrank_evtr_v2_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_evtr_v2_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_lstr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_lstr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_lstr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_lstr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_lstr_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pcltr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_collect_score}}",
    "disturbance_range": "{{rerank_es_fullrank_collect_range}}",
    "pow_alpha": "{{rerank_es_fullrank_collect_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_collect_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pcmef",
    "enable": True,
    "weight": "{{rerank_es_fullrank_cmef_score}}",
    "disturbance_range": "{{rerank_es_fullrank_cmef_range}}",
    "pow_alpha": "{{rerank_es_fullrank_cmef_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_cmef_raw_pow_weight}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_cmef_boost_topk_threshold}}",
    "boost_topk_coef": "{{rerank_es_fullrank_cmef_boost_topk_coef}}",
  },
  {
    "score_attr": "fullrank_sim_plvtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_lvtr_ori_score}}",
    "disturbance_range": "{{rerank_es_fullrank_lvtr_ori_range}}",
    "pow_alpha": "{{rerank_es_fullrank_lvtr_ori_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_lvtr_ori_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pfintr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_pfintr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_printr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_printr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_printr_raw_pow_weight}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_pfintr_boost_topk_threshold}}",
    "boost_topk_coef": "{{rerank_es_fullrank_pfintr_boost_topk_coef}}",
  },
  {
    "score_attr": "fullrank_ltr_v4_fountain_finish_rate",
    "enable": True,
    "weight": "{{rerank_es_fullrank_finish_score}}",
    "disturbance_range": "{{rerank_es_fullrank_finish_range}}",
    "pow_alpha": "{{rerank_es_fullrank_finish_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_finish_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_ltr_v4_fountain_next",
    "enable": True,
    "weight": "{{rerank_es_fullrank_next_score}}",
    "disturbance_range": "{{rerank_es_fullrank_next_range}}",
    "pow_alpha": "{{rerank_es_fullrank_next_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_next_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_opportunity_cost_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_opportunity_cost_score}}",
    "disturbance_range": "{{rerank_es_fullrank_opportunity_cost_range}}",
    "pow_alpha": "{{rerank_es_fullrank_opportunity_cost_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_opportunity_cost_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_trans_pvtr_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_trans_pvtr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_trans_pvtr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_trans_pvtr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_trans_pvtr_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_act_ctr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_act_ctr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_act_ctr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_act_ctr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_act_ctr_raw_pow_weight}}",
  },
  {
    "score_attr": "topk_mgs_expected_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_topk_mgs_expected_score}}",
    "disturbance_range": "{{rerank_es_fullrank_topk_mgs_expected_range}}",
    "pow_alpha": "{{rerank_es_fullrank_topk_mgs_expected_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_topk_mgs_expected_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_action_once_interact_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_action_once_interact_score}}",
    "disturbance_range": "{{rerank_es_fullrank_action_once_interact_range}}",
    "pow_alpha": "{{rerank_es_fullrank_action_once_interact_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_action_once_interact_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_action_once_watchtime_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_action_once_watchtime_score}}",
    "disturbance_range": "{{rerank_es_fullrank_action_once_watchtime_range}}",
    "pow_alpha": "{{rerank_es_fullrank_action_once_watchtime_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_action_once_watchtime_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pcpr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_pcpr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_pcpr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_pcpr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_pcpr_raw_pow_weight}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_pcpr_boost_topk_threshold}}",
    "boost_topk_coef": "{{rerank_es_fullrank_pcpr_boost_topk_coef}}",
  },
  {
    "score_attr": "fullrank_act_wtd",
    "enable": True,
    "weight": "{{rerank_es_fullrank_act_wtd_score}}",
    "disturbance_range": "{{rerank_es_fullrank_act_wtd_range}}",
    "pow_alpha": "{{rerank_es_fullrank_act_wtd_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_act_wtd_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_pure_value_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_pure_value_score}}",
    "disturbance_range": "{{rerank_es_fullrank_pure_value_range}}",
    "pow_alpha": "{{rerank_es_fullrank_pure_value_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_pure_value_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_distill_rerank_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_distill_rerank_score}}",
    "disturbance_range": "{{rerank_es_fullrank_distill_rerank_range}}",
    "pow_alpha": "{{rerank_es_fullrank_distill_rerank_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_distill_rerank_raw_pow_weight}}",
  },
  {
    "score_attr": "comment_ltr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_comment_ltr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_comment_ltr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_comment_ltr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_comment_ltr_raw_pow_weight}}",
  },
  {
    "score_attr": "xgb_ltr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_xgb_ltr_score}}",
    "disturbance_range": "{{rerank_es_fullrank_xgb_ltr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_xgb_ltr_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_xgb_ltr_raw_pow_weight}}",
  },
  {
    "score_attr": "effective_follow_rate_score",
    "enable": "{{fountain_rerank_enable_es_effective_follow_rate_add}}",
    "weight": "{{rerank_es_fullrank_effective_follow_rate_score_weight}}",
    "pow_alpha": "{{rerank_es_fullrank_effective_follow_rate_raw_weight}}",
  },
  {
    "score_attr": "fr_living_mix_score",
    "enable": "{{fountain_rerank_enable_es_fr_living_mix_add}}",
    "weight": "{{rerank_es_fullrank_fr_living_mix_score_weight}}",
    "disturbance_range": "{{rerank_es_fullrank_fr_living_mix_score_range}}",
    "pow_alpha": "{{rerank_es_fullrank_fr_living_mix_score_raw_weight}}",
  },
  {
    "score_attr": "rerank_good_item_similary_score",
    "enable": "{{fountain_rerank_enable_es_good_item_similary_add}}",
    "weight": "{{rerank_es_good_item_similary_score_weight}}",
  },
  {
    "score_attr": "fullrank_ltr_v4_fountain_ordinal_wtd",
    "enable": "{{fountain_rerank_enable_es_ordinal_wtd_add}}",
    "weight": "{{rerank_es_fullrank_ltr_ordinal_wtd_weight}}",
    "disturbance_range": "{{rerank_es_fullrank_ltr_ordinal_wtd_range}}",
    "pow_alpha": "{{rerank_es_fullrank_ltr_ordinal_wtd_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_ltr_ordinal_wtd_raw_pow_weight}}",
  },
  {
    "score_attr": "source_related_score",
    "enable": "{{fountain_rerank_enable_source_related_score_add}}",
    "weight": "{{rerank_es_source_related_score_weight}}",
    "disturbance_range": "{{rerank_es_source_related_score_range}}",
    "pow_alpha": "{{rerank_es_source_related_score_raw_weight}}",
    "pow_beta": "{{rerank_es_source_related_score_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_ltr_comment_staytime",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_comment_staytime_add}}",
    "weight": "{{rerank_es_fullrank_ltr_comment_staytime_weight}}",
    "disturbance_range": "{{rerank_es_fullrank_ltr_comment_staytime_range}}",
    "pow_alpha": "{{rerank_es_fullrank_ltr_comment_staytime_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_ltr_comment_staytime_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_ltr_d2co_playtime",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_d2co_playtime_add}}",
    "weight": "{{rerank_es_fullrank_ltr_d2co_playtime_weight}}",
    "disturbance_range": "{{rerank_es_fullrank_ltr_d2co_playtime_range}}",
    "pow_alpha": "{{rerank_es_fullrank_ltr_d2co_playtime_raw_weight}}",
    "pow_beta": "{{rerank_es_fullrank_ltr_d2co_playtime_raw_pow_weight}}",
  },
  {
    "score_attr": "rerank_gen_score_list",
    "enable": "{{fountain_rerank_enable_rerank_gen_score_list_add}}",
    "weight": "{{rerank_es_rerank_gen_score_list_weight}}",
    "disturbance_range": "{{rerank_es_rerank_gen_score_list_range}}",
    "pow_alpha": "{{rerank_es_rerank_gen_score_list_raw_weight}}",
    "pow_beta": "{{rerank_es_rerank_gen_score_list_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_ltr_lph",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_lph_add}}",
    "weight": "{{fountain_rerank_es_fullrank_ltr_lph_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_ltr_lph_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_ltr_lph_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_ltr_lph_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_ltr_dfvr",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_dfvr_add}}",
    "weight": "{{fountain_rerank_es_fullrank_ltr_dfvr_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_ltr_dfvr_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_ltr_dfvr_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_ltr_dfvr_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_ltr_ord2q",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_ord2q_add}}",
    "weight": "{{fountain_rerank_es_fullrank_ltr_ord2q_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_ltr_ord2q_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_ltr_ord2q_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_ltr_ord2q_raw_pow_weight}}",
  },
  {
    "score_attr": "fullrank_sim_pdfvr",
    "enable": "{{fountain_rerank_enable_fullrank_pdfvr_add}}",
    "weight": "{{fountain_rerank_es_fullrank_pdfvr_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_pdfvr_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_pdfvr_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_pdfvr_raw_pow_weight}}"
  },
  {
    "score_attr": "fullrank_sim_pwtd_v2_playtime",
    "enable": "{{fountain_rerank_enable_fullrank_pwtd_v2_playtime_add}}",
    "weight": "{{fountain_rerank_es_fullrank_pwtd_v2_playtime_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_pwtd_v2_playtime_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_pwtd_v2_playtime_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_pwtd_v2_playtime_raw_pow_weight}}"
  },
  {
    "score_attr": "fullrank_esnn_ltr_score",
    "enable": "{{fountain_rerank_enable_fullrank_esnn_ltr_add}}",
    "weight": "{{fountain_rerank_es_fullrank_esnn_ltr_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_esnn_ltr_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_esnn_ltr_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_esnn_ltr_raw_pow_weight}}"
  },
  {
    "score_attr": "i2i_dynamic_score",
    "enable": "{{fountain_rerank_enable_es_i2i_dynamic_score_add}}",
    "weight": "{{fountain_rerank_es_i2i_dynamic_score_weight}}",
    "disturbance_range": "{{rerank_es_i2i_dynamic_score_range}}",
    "pow_alpha": "{{fountain_rerank_es_i2i_dynamic_score_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_i2i_dynamic_score_raw_pow_weight}}"
  },
  {
    "score_attr": "final_fr_consecutive_nonclick_score",
    "enable": "{{fountain_rerank_enable_es_final_fr_consecutive_nonclick_score_add}}",
    "weight": "{{fountain_rerank_es_final_fr_consecutive_nonclick_score_weight}}",
    "disturbance_range": "{{rerank_es_final_fr_consecutive_nonclick_score_range}}",
    "pow_alpha": "{{fountain_rerank_es_final_fr_consecutive_nonclick_score_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_final_fr_consecutive_nonclick_score_raw_pow_weight}}"
  },
  {
    "score_attr": "fullrank_min_wt_rank_reci",
    "enable": "{{fountain_rerank_enable_es_fullrank_min_wt_rank_reci_add}}",
    "weight": "{{fountain_rerank_es_fullrank_min_wt_rank_reci_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_min_wt_rank_reci_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_min_wt_rank_reci_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_min_wt_rank_reci_raw_pow_weight}}"
  },
  {
    "score_attr": "fullrank_reco_base_model_gen_time_wt",
    "enable": "{{fountain_rerank_enable_es_fullrank_reco_base_model_gen_time_wt}}",
    "weight": "{{fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_raw_pow_weight}}"
  },
  {
    "score_attr": "fullrank_reco_base_model_evtr",   # 2026-05-26 by dengyingjie03
    "enable": "{{fountain_rerank_enable_es_fullrank_reco_base_model_evtr}}",
    "weight": "{{fountain_rerank_es_fullrank_reco_base_model_evtr_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_reco_base_model_evtr_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_reco_base_model_evtr_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_reco_base_model_evtr_raw_pow_weight}}"
  },
  {
    "score_attr": "fullrank_reco_base_model_lvtr",   # 2026-05-26 by dengyingjie03
    "enable": "{{fountain_rerank_enable_es_fullrank_reco_base_model_lvtr}}",
    "weight": "{{fountain_rerank_es_fullrank_reco_base_model_lvtr_weight}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_reco_base_model_lvtr_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_reco_base_model_lvtr_raw_weight}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_reco_base_model_lvtr_raw_pow_weight}}"
  },
]

es_mul_queues = [
  {
    "score_attr": "fullrank_sim_pevtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_click_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_click_range}}",
    "pow_alpha": "{{rerank_es_fullrank_click_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_click_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pltr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_like_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_like_range}}",
    "pow_alpha": "{{rerank_es_fullrank_like_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_like_raw_pow_weight_addAndMul}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_like_boost_topk_threshold_addAndMul}}",
    "boost_topk_coef": "{{rerank_es_fullrank_like_boost_topk_coef_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pwtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_follow_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_follow_range}}",
    "pow_alpha": "{{rerank_es_fullrank_follow_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_follow_raw_pow_weight_addAndMul}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_follow_boost_topk_threshold_addAndMul}}",
    "boost_topk_coef": "{{rerank_es_fullrank_follow_boost_topk_coef_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pcmtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_comment_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_comment_range}}",
    "pow_alpha": "{{rerank_es_fullrank_comment_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_comment_raw_pow_weight_addAndMul}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_comment_boost_topk_threshold_addAndMull}}",
    "boost_topk_coef": "{{rerank_es_fullrank_comment_boost_topk_coef_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pptr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_profile_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_profile_range}}",
    "pow_alpha": "{{rerank_es_fullrank_profile_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_profile_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pwatchtime_no_bias",
    "enable": True,
    "weight": "{{rerank_es_fullrank_watchtime_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_watchtime_range}}",
    "pow_alpha": "{{rerank_es_fullrank_watchtime_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_watchtime_raw_pow_weight_addAndMul}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_watchtime_boost_topk_threshold_addAndMul}}",
    "boost_topk_coef": "{{rerank_es_fullrank_watchtime_boost_topk_coef_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_psvr",
    "enable": True,
    "reverse_order": True,
    "weight": "{{rerank_es_fullrank_shortview_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_shortview_range}}",
    "pow_alpha": "{{rerank_es_fullrank_shortview_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_shortview_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_ltr_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_l2r_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_l2r_range}}",
    "pow_alpha": "{{rerank_es_fullrank_l2r_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_l2r_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pepstr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_pepstr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_pepstr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_pepstr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_pepstr_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_out_pctr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_outctr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_outctr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_outctr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_outctr_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pvtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_watchtime_ori_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_watchtime_ori_range}}",
    "pow_alpha": "{{rerank_es_fullrank_watchtime_ori_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_watchtime_ori_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_detail_new_pevtr_v2",
    "enable": True,
    "weight": "{{rerank_es_fullrank_evtr_v2_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_evtr_v2_range}}",
    "pow_alpha": "{{rerank_es_fullrank_evtr_v2_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_evtr_v2_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_lstr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_lstr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_lstr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_lstr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_lstr_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pcltr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_collect_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_collect_range}}",
    "pow_alpha": "{{rerank_es_fullrank_collect_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_collect_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pcmef",
    "enable": True,
    "weight": "{{rerank_es_fullrank_cmef_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_cmef_range}}",
    "pow_alpha": "{{rerank_es_fullrank_cmef_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_cmef_raw_pow_weight_addAndMul}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_cmef_boost_topk_threshold_addAndMul}}",
    "boost_topk_coef": "{{rerank_es_fullrank_cmef_boost_topk_coef_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_plvtr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_lvtr_ori_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_lvtr_ori_range}}",
    "pow_alpha": "{{rerank_es_fullrank_lvtr_ori_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_lvtr_ori_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pfintr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_pfintr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_printr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_pfintr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_pfintr_raw_pow_weight_addAndMul}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_pfintr_boost_topk_threshold_addAndMul}}",
    "boost_topk_coef": "{{rerank_es_fullrank_pfintr_boost_topk_coef_addAndMul}}",
  },
  {
    "score_attr": "fullrank_ltr_v4_fountain_finish_rate",
    "enable": True,
    "weight": "{{rerank_es_fullrank_finish_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_finish_range}}",
    "pow_alpha": "{{rerank_es_fullrank_finish_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_finish_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_ltr_v4_fountain_next",
    "enable": True,
    "weight": "{{rerank_es_fullrank_next_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_next_range}}",
    "pow_alpha": "{{rerank_es_fullrank_next_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_next_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_opportunity_cost_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_opportunity_cost_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_opportunity_cost_range}}",
    "pow_alpha": "{{rerank_es_fullrank_opportunity_cost_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_opportunity_cost_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_cl_tran_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_cl_tran_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_cl_tran_range}}",
    "pow_alpha": "{{rerank_es_fullrank_cl_tran_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_cl_tran_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_trans_pvtr_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_trans_pvtr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_trans_pvtr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_trans_pvtr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_trans_pvtr_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_act_ctr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_act_ctr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_act_ctr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_act_ctr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_act_ctr_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "topk_mgs_expected_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_topk_mgs_expected_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_topk_mgs_expected_range}}",
    "pow_alpha": "{{rerank_es_fullrank_topk_mgs_expected_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_topk_mgs_expected_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_action_once_interact_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_action_once_interact_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_action_once_interact_range}}",
    "pow_alpha": "{{rerank_es_fullrank_action_once_interact_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_action_once_interact_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_action_once_watchtime_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_action_once_watchtime_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_action_once_watchtime_range}}",
    "pow_alpha": "{{rerank_es_fullrank_action_once_watchtime_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_action_once_watchtime_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_sim_pcpr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_pcpr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_pcpr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_pcpr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_pcpr_raw_pow_weight_addAndMul}}",
    "boost_topk_threshold": "{{rerank_es_fullrank_pcpr_boost_topk_threshold_addAndMul}}",
    "boost_topk_coef": "{{rerank_es_fullrank_pcpr_boost_topk_coef_addAndMul}}",
  },
  {
    "score_attr": "fullrank_act_wtd",
    "enable": True,
    "weight": "{{rerank_es_fullrank_act_wtd_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_act_wtd_range}}",
    "pow_alpha": "{{rerank_es_fullrank_act_wtd_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_act_wtd_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_pure_value_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_pure_value_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_pure_value_range}}",
    "pow_alpha": "{{rerank_es_fullrank_pure_value_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_pure_value_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_distill_rerank_score",
    "enable": True,
    "weight": "{{rerank_es_fullrank_distill_rerank_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_distill_rerank_range}}",
    "pow_alpha": "{{rerank_es_fullrank_distill_rerank_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_distill_rerank_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "comment_ltr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_comment_ltr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_comment_ltr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_comment_ltr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_comment_ltr_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "xgb_ltr",
    "enable": True,
    "weight": "{{rerank_es_fullrank_xgb_ltr_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_xgb_ltr_range}}",
    "pow_alpha": "{{rerank_es_fullrank_xgb_ltr_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_xgb_ltr_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fr_living_mix_score",
    "enable": "{{fountain_rerank_enable_es_fr_living_mix_mul}}",
    "weight": "{{rerank_es_fullrank_fr_living_mix_score_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_fr_living_mix_score_range}}",
    "pow_alpha": "{{rerank_es_fullrank_fr_living_mix_score_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_fr_living_mix_score_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_ltr_v4_fountain_ordinal_wtd",
    "enable": "{{fountain_rerank_enable_es_ordinal_wtd_mul}}",
    "weight": "{{rerank_es_fullrank_ltr_ordinal_wtd_weight_addAndMul}}",
    "disturbance_range": "{{rerank_es_fullrank_ltr_ordinal_wtd_range}}",
    "pow_alpha": "{{rerank_es_fullrank_ltr_ordinal_wtd_raw_weight_addAndMul}}",
    "pow_beta": "{{rerank_es_fullrank_ltr_ordinal_wtd_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "source_related_score",
    "enable": "{{fountain_rerank_enable_source_related_score_mul}}",
    "weight": "{{rerank_es_source_related_score_weight_mul}}",
    "disturbance_range": "{{rerank_es_source_related_score_range}}",
    "pow_alpha": "{{rerank_es_source_related_score_raw_weight_mul}}",
    "pow_beta": "{{rerank_es_source_related_score_raw_pow_weight_mul}}",
  },
  {
    "score_attr": "fullrank_ltr_comment_staytime",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_comment_staytime_mul}}",
    "weight": "{{rerank_es_fullrank_ltr_comment_staytime_weight_mul}}",
    "disturbance_range": "{{rerank_es_fullrank_ltr_comment_staytime_range}}",
    "pow_alpha": "{{rerank_es_fullrank_ltr_comment_staytime_raw_weight_mul}}",
    "pow_beta": "{{rerank_es_fullrank_ltr_comment_staytime_raw_pow_weight_mul}}",
  },
  {
    "score_attr": "fullrank_ltr_d2co_playtime",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_d2co_playtime_mul}}",
    "weight": "{{rerank_es_fullrank_ltr_d2co_playtime_weight_mul}}",
    "disturbance_range": "{{rerank_es_fullrank_ltr_d2co_playtime_range}}",
    "pow_alpha": "{{rerank_es_fullrank_ltr_d2co_playtime_raw_weight_mul}}",
    "pow_beta": "{{rerank_es_fullrank_ltr_d2co_playtime_raw_pow_weight_mul}}",
  },
  {
    "score_attr": "rerank_gen_score_list",
    "enable": "{{fountain_rerank_enable_rerank_gen_score_list_mul}}",
    "weight": "{{rerank_es_rerank_gen_score_list_weight_mul}}",
    "disturbance_range": "{{rerank_es_rerank_gen_score_list_range_mul}}",
    "pow_alpha": "{{rerank_es_rerank_gen_score_list_raw_weight_mul}}",
    "pow_beta": "{{rerank_es_rerank_gen_score_list_raw_pow_weight_mul}}",
  },
  {
    "score_attr": "fullrank_sim_pftr",
    "enable": "{{fountain_rerank_enable_fullrank_forward_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_forward_weight_mul}}",
    "disturbance_range": "{{rerank_es_fullrank_forward_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_forward_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_forward_raw_pow_weight_mul}}",
  },
  {
    "score_attr": "fullrank_ltr_dfvr",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_dfvr_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_ltr_dfvr_weight_mul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_ltr_dfvr_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_ltr_dfvr_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_ltr_dfvr_raw_pow_weight_mul}}",
  },{
    "score_attr": "fullrank_ltr_lph",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_lph_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_ltr_lph_weight_mul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_ltr_lph_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_ltr_lph_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_ltr_lph_raw_pow_weight_mul}}",
  },
  {
    "score_attr": "fullrank_ltr_ord2q",
    "enable": "{{fountain_rerank_enable_fullrank_ltr_ord2q_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_ltr_ord2q_weight_mul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_ltr_ord2q_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_ltr_ord2q_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_ltr_ord2q_raw_pow_weight_mul}}",
  },
  {
    "score_attr": "fullrank_sim_pdfvr",
    "enable": "{{fountain_rerank_enable_fullrank_pdfvr_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_pdfvr_weight_mul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_pdfvr_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_pdfvr_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_pdfvr_raw_pow_weight_mul}}"
  },
  {
    "score_attr": "fullrank_sim_pwtd_v2_playtime",
    "enable": "{{fountain_rerank_enable_fullrank_pwtd_v2_playtime_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_pwtd_v2_playtime_weight_mul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_pwtd_v2_playtime_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_pwtd_v2_playtime_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_pwtd_v2_playtime_raw_pow_weight_mul}}"
  },
  {
    "score_attr": "fullrank_esnn_ltr_score",
    "enable": "{{fountain_rerank_enable_fullrank_esnn_ltr_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_esnn_ltr_weight_mul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_esnn_ltr_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_esnn_ltr_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_esnn_ltr_raw_pow_weight_mul}}"
  },
  {
    "score_attr": "i2i_dynamic_score",
    "enable":"{{fountain_rerank_enable_i2i_dynamic_score_mul}}",
    "weight": "{{fountain_rerank_es_i2i_dynamic_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_i2i_dynamic_score_range}}",
    "pow_alpha": "{{fountain_rerank_es_i2i_dynamic_score_rerank_raw_weight_addAndMul}}",
    "pow_beta": "{{fountain_rerank_es_i2i_dynamic_score_rerank_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "final_fr_consecutive_nonclick_score",
    "enable":"{{fountain_rerank_enable_final_fr_consecutive_nonclick_score_mul}}",
    "weight": "{{fountain_rerank_es_final_fr_consecutive_nonclick_score_addAndMul}}",
    "disturbance_range": "{{rerank_es_final_fr_consecutive_nonclick_score_range}}",
    "pow_alpha": "{{fountain_rerank_es_final_fr_consecutive_nonclick_score_rerank_raw_weight_addAndMul}}",
    "pow_beta": "{{fountain_rerank_es_final_fr_consecutive_nonclick_score_rerank_raw_pow_weight_addAndMul}}",
  },
  {
    "score_attr": "fullrank_min_wt_rank_reci",
    "enable": "{{fountain_rerank_enable_es_fullrank_min_wt_rank_reci_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_min_wt_rank_reci_weight_addAndMul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_min_wt_rank_reci_range}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_min_wt_rank_reci_raw_weight_addAndMul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_min_wt_rank_reci_raw_pow_weight_addAndMul}}"
  },
  {
    "score_attr": "fullrank_reco_base_model_gen_time_wt",
    "enable": "{{fountain_rerank_enable_es_fullrank_reco_base_model_gen_time_wt_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_weight_addAndMul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_range_addAndMul}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_raw_weight_addAndMul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_reco_base_model_gen_time_wt_raw_pow_weight_addAndMul}}"
  },
  {
    "score_attr": "fullrank_reco_base_model_evtr",   # 2026-05-26 by dengyingjie03
    "enable": "{{fountain_rerank_enable_es_fullrank_reco_base_model_evtr_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_reco_base_model_evtr_weight_mul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_reco_base_model_evtr_range_mul}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_reco_base_model_evtr_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_reco_base_model_evtr_raw_pow_weight_mul}}"
  },
  {
    "score_attr": "fullrank_reco_base_model_lvtr",   # 2026-05-26 by dengyingjie03
    "enable": "{{fountain_rerank_enable_es_fullrank_reco_base_model_lvtr_mul}}",
    "weight": "{{fountain_rerank_es_fullrank_reco_base_model_lvtr_weight_mul}}",
    "disturbance_range": "{{fountain_rerank_es_fullrank_reco_base_model_lvtr_range_mul}}",
    "pow_alpha": "{{fountain_rerank_es_fullrank_reco_base_model_lvtr_raw_weight_mul}}",
    "pow_beta": "{{fountain_rerank_es_fullrank_reco_base_model_lvtr_raw_pow_weight_mul}}"
  },
]

# only for hetu single list
rerank_hetu_fusion_queues = [
  {
    "name": "fullrank_sim_pevtr",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_pevtr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_pevtr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_pevtr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_pevtr_tail_discount_coef",
  },
  {
    "name": "fullrank_sim_pfintr",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_pfintr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_pfintr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_pfintr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_pfintr_tail_discount_coef",
  },
  {
    "name": "fullrank_sim_pvtr",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_pvtr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_pvtr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_pvtr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_pvtr_tail_discount_coef",
  },
  {
    "name": "fullrank_sim_pltr",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_pltr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_pltr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_pltr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_pltr_tail_discount_coef",
  },
  {
    "name": "fullrank_sim_pcmtr",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_pcmtr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_pcmtr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_pcmtr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_pcmtr_tail_discount_coef",
  },
  {
    "name": "fullrank_sim_pwtr",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_pwtr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_pwtr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_pwtr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_pwtr_tail_discount_coef",
  },
  {
    "name": "fullrank_act_ctr",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_act_ctr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_act_ctr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_act_ctr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_act_ctr_tail_discount_coef",
  },
  {
    "name": "fullrank_action_once_interact_score",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_action_once_interact_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_action_once_interact_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_action_once_interact_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_action_once_interact_tail_discount_coef",
  },
  {
    "name": "fullrank_detail_new_pevtr_v2",
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_pevtr_v2_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_pevtr_v2_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_pevtr_v2_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_pevtr_v2_tail_discount_coef",
  },
  {
    "name": "fullrank_sim_psvr",  # 2026-1-8 by dengyingjie03
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_psvr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_psvr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_psvr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_psvr_tail_discount_coef",
  },
  {
    "name": "fullrank_sim_plvtr",  # 2026-1-21 by dengyingjie03
    "weight":  0.0,
    "weight_attr": "fountain_rerank_hetu_fusion_sim_plvtr_weight",
    "power_weight_attr": "fountain_rerank_hetu_fusion_sim_plvtr_weight",
    "queue_head_boost_coef": "fountain_rerank_hetu_fusion_sim_plvtr_head_boost_coef",
    "queue_tail_discount_coef": "fountain_rerank_hetu_fusion_sim_plvtr_tail_discount_coef",
  },
]