#!/usr/bin/env python3
# coding=utf-8

post_process_common_params = [
]

post_process_splash_params = [
]

post_process_fast_params = [
  # multi page variant
  ("fountain_skip_enable_fountain_browse", True),
  ("fountain_skip_enable_hot_browse", True),
  ("fountain_skip_variant_merge_v2", 1),
  ("fountain_variant_merge_max_satisfied_v2", 80),
  ("realtime_fountain_browse_set_size", 10),
  ("realtime_hot_browse_set_size", 10),
  ("fountain_profile_time_threshold", 600.0),
  ("enabled_fountain_variant_hetu_tag_v2", True),
  ("fountain_variant_hetu_tag_v2_win_size", 6),
  ("fountain_variant_hetu_tag_v2_decay_times", 1),
  ("enabled_fountain_variant_hetu_level_three_new_v2", False),
  ("fountain_variant_hetu_level_three_win_size_new", 6),
  ("fountain_variant_hetu_level_three_decay_times_new", 1),
  ("enabled_fountain_variant_hetu_level_five_new_v2", True),
  ("enabled_fountain_variant_hetu_face_id_v2", True),
  ("enabled_fountain_variant_hetu_cluster_id_v2", True),

  ("fountain_variant_hetu_tag_v2_normal_win_size", 6),
  ("fountain_variant_hetu_tag_v2_normal_decay_times", 1),
  ("fountain_variant_hetu_tag_v2_normal_priority", 6),
  ("fountain_variant_pic_win_size", 6),
  ("fountain_variant_hetu_pic_decay_times", 1),
  ("fountain_variant_pic_priority", 4),
  ("fountain_skip_gen_hetu_tag_type", 1),
  ("fountain_variant_hetu_face_level_five_win_size_new", 6),
  ("fountain_variant_hetu_face_level_five_decay_times_new", 1),
  ("fountain_variant_hetu_face_level_five_priority_new", 5),
  ("fountain_variant_hetu_tag_v2_theme_win_size", 6),
  ("fountain_variant_hetu_tag_v2_theme_decay_times", 1),
  ("fountain_variant_hetu_tag_v2_theme_priority", 6),
  ("fountain_variant_hetu_tag_v2_style_win_size", 6),
  ("fountain_variant_hetu_tag_v2_style_decay_times", 1),
  ("fountain_variant_hetu_tag_v2_style_priority", 6),
  ("fountain_variant_short_duration_decay_window_size", 6),
  ("fountain_variant_short_duration_decay_occurrent_times", 3),
  ("enabled_fountain_variant_similar_event_id", False),
  ("fountain_variant_similar_event_id_win_size", 6),
  ("fountain_variant_similar_event_id_decay_times", 2),
  ("enabled_fountain_variant_hetu_face_id", False),
  ("fountain_variant_hetu_face_id_win_size", 6),
  ("fountain_variant_hetu_face_id_decay_times", 2),
  ("enabled_fountain_variant_hetu_tag", False),
  ("fountain_variant_hetu_tag_win_size", 6),
  ("fountain_variant_hetu_tag_decay_times", 2),
  ("fountain_variant_hetu_level_five_win_size_new", 6),
  ("fountain_variant_hetu_level_five_decay_times_new", 3),
  ("enabled_fountain_variant_hetu_level_one", True),
  ("enabled_fountain_variant_hetu_level_two", True),
  ("fountain_variant_is_overdue_photo_decay_times", 2),
  ("fountain_variant_upload_days_threshold", 60),
  ("enable_fountain_variant_is_overdue_photo", False),
  ("fountain_variant_is_overdue_photo_win_size", 5),
  ("enabled_fountain_variant_olympic_photo", False),
  ("fountain_variant_olympic_photo_win_size", 6),
  ("enabled_fountain_variant_follow_author_id", False),
  ("fountain_variant_follow_author_id_win_size", 3),
  ("fountain_variant_follow_author_id_decay_occurrent_times", 2),
  ("skip_variant_v9_gr_pr", 1),
  ("fountain_variant_short_duration_decay_window_size", 6),
  ("fountain_variant_short_duration_decay_occurrent_times", 3),
  ("enable_fountain_variant_short_duration", True),
  ("fountain_enable_mmr_photo_embedding", False),
  ("fountain_variant_mmr_need_diversity_num", 5),
  ("fountain_variant_mmr_cal_candidate_num", 50),
  ("fountain_variant_mmr_item_ensemble_score_attr", "fullrank_neg_feedback_discount_score"),
  ("fountain_variant_mmr_lambda", 0.6),
  ("fountain_variant_mmr_gamma", 0.6),
  ("fountain_mmr_no_max_weight_use", True),
  ("fountain_enable_mmr_his_feedback_diversity", True),
  ("fountain_mmr_no_his_max_weight_use", False),
  ("fountain_variant_mmr_diversity_dim_weight", "0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1:0.1"),
  ("fountain_variant_mmr_history_diversity_dim_weight", "0.1:0.1:0.1:0.1:0.1:0.1:0.1"),
  ("fountain_variant_mmr_cal_noclick_num", 20),
  ("fountain_variant_mmr_real_show_expired_gap", 1800),
  ("fountain_variant_mmr_page_num_limit", 10),
  ("fountain_variant_mmr_time_weight_param", 0.25),
  ("fountain_variant_mmr_time_interval_param", 1500.0),
  ("skip_fountain_variant_multi_page", 1),
  ("variant_multi_page_candidate_size", 30),
  ("variant_multi_page_window_size", 10),
  ("variant_multi_page_hetu_one_times", 5),
  ("variant_multi_page_hetu_one_decay_rate", 0.98),
  ("variant_multi_page_hetu_two_times", 4),
  ("variant_multi_page_hetu_two_decay_rate", 0.96),
  ("variant_multi_page_hetu_three_times", 3),
  ("variant_multi_page_hetu_three_decay_rate", 0.9),
  ("variant_multi_page_hetu_face_id_times", 3),
  ("variant_multi_page_hetu_face_id_decay_rate", 0.9),
  ("fountain_variant_is_pgc_hetu_level_two_occurrent_times", 2),
  ("fountain_variant_is_pgc_hetu_level_two_window_size", 6),
  ("enabled_fountain_variant_is_pgc_hetu_level_three", False),
  ("fountain_variant_is_pgc_hetu_level_three_occurrent_times", 2),
  ("fountain_variant_is_pgc_hetu_level_three_window_size", 6),
  ("fountain_variant_multi_page_score_attr", "fullrank_neg_feedback_discount_score"),
  ("skip_variant_v8_author", 1),
  ("skip_variant_v9_hetu", 1),
  ("fountain_variant_author_id_decay_window_size", 20),
  ("fountain_variant_author_id_decay_occurrent_times", 2),
  ("enable_fountain_variant_author_id", True),
  ("fountain_variant_author_fourth_level_decay_window_size", 6),
  ("fountain_variant_author_fourth_level_decay_occurrent_times", 3),
  ("enable_fountain_variant_author_fourth_level", True),
  ("fountain_variant_author_second_level_decay_window_size", 6),
  ("fountain_variant_author_second_level_decay_occurrent_times", 3),
  ("enable_fountain_variant_author_second_level", True),
  ("skip_fountain_variant", 0),
  ("fountain_skip_save_item_seq_current", 1),
  ("enabled_fountain_variant_author_level_two", True),
  ("fountain_skip_last_page_hetu_boost", 1),
  ("fountian_last_page_hetu_tag_boost", 1.0),
  ("fountian_last_page_hetu_three_boost", 1.0),
  ("fountian_last_page_hetu_two_boost", 1.0),
  ("fountian_last_page_hetu_one_boost", 1.0),
]

post_process_fast_params_ab_hit = [
  {
    "param_name": "enabled_fountain_variant_is_pgc_hetu_level_two",
    "param_type": "bool",
    "attr_name": "enabled_fountain_variant_is_pgc_hetu_level_two",
    "default_value": False
  },
  {
    "param_name": "enabled_fountain_variant_pic",
    "param_type": "bool",
    "attr_name": "enabled_fountain_variant_pic",
    "default_value": False
  },
  {
    "param_name": "enable_fountain_variant_short_duration",
    "param_type": "bool",
    "attr_name": "enable_fountain_variant_short_duration",
    "default_value": False
  },
  {
    "param_name": "enabled_fountain_variant_hetu_level_one_new_v2",
    "param_type": "bool",
    "attr_name": "enabled_fountain_variant_hetu_level_one_new_v2",
    "default_value": True
  },
  {
    "param_name": "fountain_variant_hetu_level_one_win_size_new",
    "param_type": "int",
    "attr_name": "fountain_variant_hetu_level_one_win_size_new",
    "default_value": 6
  },
  {
    "param_name": "fountain_variant_hetu_level_one_decay_times_new",
    "param_type": "int",
    "attr_name": "fountain_variant_hetu_level_one_decay_times_new",
    "default_value": 3
  },
  {
    "param_name": "enabled_fountain_variant_hetu_level_two_new_v2",
    "param_type": "bool",
    "attr_name": "enabled_fountain_variant_hetu_level_two_new_v2",
    "default_value": True
  },
  {
    "param_name": "fountain_variant_hetu_level_two_win_size_new",
    "param_type": "int",
    "attr_name": "fountain_variant_hetu_level_two_win_size_new",
    "default_value": 6
  },
  {
    "param_name": "fountain_variant_hetu_level_two_decay_times_new",
    "param_type": "int",
    "attr_name": "fountain_variant_hetu_level_two_decay_times_new",
    "default_value": 2
  },
  {
    "param_name": "fountain_skip_variant_merge",
    "param_type": "int",
    "attr_name": "fountain_skip_variant_merge",
    "default_value": 1
  },
  {
    "param_name": "skip_fountain_variant_mmr",
    "param_type": "int",
    "attr_name": "skip_fountain_variant_mmr",
    "default_value": 1
  },
] + [
  {
    "attr_name": param[0],
    "default_value": param[1],
    "param_name": param[0],
    "param_type": param[2]
  } for param in [
    ("fountain_variant_merge_limit", 100, "int"),
    ("fountain_variant_merge_max_satisfied", 6, "int"),
    ("enabled_fountain_variant_hetu_cluster_id", False, "bool"),
    ("fountain_variant_hetu_cluster_id_win_size", 6, "int"),
    ("fountain_variant_hetu_cluster_id_decay_times", 2, "int"),
    ("enabled_fountain_variant_hetu_level_one_v1", False, "bool"),
    ("fountain_variant_hetu_level_one_v1_win_size", 6, "int"),
    ("fountain_variant_hetu_level_one_v1_decay_times", 2, "int"),
    ("enabled_fountain_variant_hetu_level_two_v1", False, "bool"),
    ("fountain_variant_hetu_level_two_v1_win_size", 6, "int"),
    ("fountain_variant_hetu_level_two_v1_decay_times", 2, "int"),
    ("enabled_fountain_variant_hetu_level_five_v1", False, "bool"),
    ("fountain_variant_hetu_level_five_v1_win_size", 6, "int"),
    ("fountain_variant_hetu_level_five_v1_decay_times", 2, "int"),
    ("enabled_fountain_variant_hetu_level_five_new", False, "bool"),
    ("enabled_fountain_variant_hetu_tag_v2_theme", False, "bool"),
    ("enabled_fountain_variant_hetu_tag_v2_style", False, "bool"),
    ("enabled_fountain_variant_hetu_tag_v2_normal", False, "bool"),
    ("enabled_fountain_variant_hetu_level_one_new", True, "bool"),
    ("enabled_fountain_variant_hetu_level_two_new", False, "bool"),
    ("fountain_variant_hetu_level_one_v2_priority", 2, "int"),
    ("fountain_variant_hetu_level_two_v2_priority", 3, "int"),
    ("fountain_variant_hetu_level_one_v1_priority", 3, "int"),
    ("fountain_variant_hetu_level_two_v1_priority", 3, "int"),
    ("fountain_variant_hetu_level_five_v1_priority", 6, "int"),
  ]
]
