#!/usr/bin/env python3
# coding=utf-8

from dragonfly.common_leaf_dsl import LeafFlow
from dragonfly.ext.subdivision.subdivision_api_mixin import subdivisionApiMixin
from post_process.ab_params import post_process_common_params, post_process_splash_params
from util import enrich_ab_param

class PostProcessSplashExp3Flow(LeafFlow, subdivisionApiMixin):
  def __init__(self):
    LeafFlow.__init__(self, "post_process_splash_exp3")
    self \
      .namespace_(ns = "post_process_splash_exp3", nest = True) \
      ._process() \
      .namespace_()

  def _process(self):
    self \
    .get_abtest_params(
      biz_name = "RECO_RPC",
      ab_params = enrich_ab_param(post_process_common_params + post_process_splash_params),
      prioritized_suffix = "{{_ABTEST_SUFFIX_LIST_}}"
    ) \
    .perflog_attr_value(
      name = "fountain_splash_fr_diversify",
      traceback = True,
      check_point = "audit_result_record",
      item_attrs = [
        "explore_operation_c_review_level",
        "audit_b_second_tag",
        "audit_hot_high_tag_level",
        "content_safety_level_with_namespace__level_hot_online",
        "topk_audit_level",
        "audit_hot_high_subdivision_level",
      ],
      aggregator = "count") \
    .log_debug_info(
      common_attrs = [
        "featureUserIsFountainSplash",
        "featureUserIsFountainRequest",
        "uId",
        "deviceId",
        "featureSourcePId",
        "fountain_ensemble_power_weight_fullrank_lstr_score",
        "fountain_ensemble_power_weight_fullrank_pptr_score",
        "fountain_skip_pic_and_selfdup_id_deduplicate_in_pagesize_splash",
        "fountain_skip_sim_remove_dup_id_deduplicate_in_pagesize_splash",
        "fountain_ltr_v3_duration_weight",
        "fountain_ltr_v3_ctr_weight",
        "featureFountainProfileClickPidList",
        "featureFountainProfileClickAidList",
        "featureFountainProfileLikePidList",
        "featureFountainProfileLikeAidList",
        "featureFountainProfileCommentPidList",
        "featureFountainProfileCommentAidList",
        "featureFountainProfileFollowPidList",
        "featureFountainProfileFollowAidList",
        "featureFountainProfileShortViewPidList",
        "featureFountainProfileShortViewAidList",
        "featureFountainProfileEffViewPidList",
        "featureFountainProfileEffViewAidList",
        "featureFountainProfileLongViewPidList",
        "featureFountainProfileLongViewAidList",
        "sample_user_features",
        "sample_item_features",
        "isSourceFollowedAuthor",
        "filtered_content_ids_item_key",
        "fullrank_click_score_adaptive_factor",
        "fullrank_sim_like_score_adaptive_factor",
        "fullrank_sim_follow_score_adaptive_factor",
        "fullrank_sim_pcmtr_adaptive_factor",
        "fullrank_sim_pptr_adaptive_factor",
        "fullrank_sim_phtr_adaptive_factor",
        "fullrank_sim_pvtr_adaptive_factor",
        "fullrank_sim_psvr_adaptive_factor",
        "fullrank_sim_plvtr_adaptive_factor",
        "fullrank_sim_out_pctr_adaptive_factor",
        "impression_audit_white_tags",
        "user_comment_count",
        "user_like_count",
        "user_show_count",
        "fountain_comment_ltr_model_kconf_key",
        "high_hot_audit_white_tags",
        "skip_fullrank_ensemble_score_v8",
        "fountain_relation_interaction_retr_redis_key",
        "fountain_skip_ltr_predict_v3",
        "enable_find_v4_fountain_ltr_v3_predict",
        "fountain_skip_cal_enrich_comment_ltr_item_attr_from_redis",
        "fountain_skip_cal_enrich_comment_ltr_common_attr_from_redis",
        "fountain_skip_cal_comment_ltr",
        "fountain_comment_ltr_model_kconf_key",
        "fountain_skip_cal_enrich_comment_ltr_item_attr_from_redis_mobile",
        "fountain_skip_cal_enrich_comment_ltr_common_attr_from_redis_mobile",
        "fountain_skip_cal_comment_ltr_mobile",
        "fountain_comment_ltr_model_kconf_key_mobile",
        "fountain_ensemble_power_weight_fullrank_ltr_v4_next",
        "avgFinishRateList",
        "uid_show_day_7",
        "userBrowseSetHetuLevel3",
        "userBrowseSetHetuLevel1",
        "userBrowseSetHetuLevel2",
        "fountain_enable_wtp_v2_vtr_as_wtd",
        "fountain_fullrank_sim_pwtd_finish_rate_power",
        "fountain_ltr_v3_duration_weight",
        "fountain_ltr_v3_ctr_weight",
        "enable_fountain_pwatch_time_sigmoid_bias",
        "enable_fountain_pwatch_time_adjust",
        "fountain_vtr_max_value_1",
        "enable_personal_time_coeff",
        "featureUserAvgWatchTime",
        "fountain_personal_sigmoid_bias",
        "fountain_ensemble_score_v2_sim_pwtd_no_bias_weight",
        "fountain_ensemble_power_weight_fullrank_cl_score",
        "enable_fountain_pwatchtime_origin",
        "fountain_ensemble_power_weight_fullrank_pwtd_watchtime_score",
        "fountain_ltr_score_wtd_weight",
        "userExpSvtr",
        "userExpLvtr",
        "fountain_fullrank_bucket_dura_for_pfr",
        "fountain_fullrank_bucket_fr_for_pfr",
        "cdf_fr_list",
        "fountain_fullrank_finish_duration_factor_max_value_v2",
        "skip_fountain_finish_rate_adjust_v2",
        "fountain_fullrank_enable_cdf_fr_smooth",
        "fountain_fullrank_fr_smooth_para",
        "skip_fountain_finish_rate_adjust_v3",
        "fountain_fullrank_not_svr_pow_weight_for_pfr",
        "fullrank_emb_kess_name_for_hate_similary_score",
        "fountain_offline_collect_retrieval_max_keys",
        "fountain_offline_collect_retrieval_max_keys_splash",
        "fountain_fullrank_lt_emb_kess_name_for_fr",
        "fountain_fullrank_lt_emb_request_slot_id",
        "fountain_fullrank_use_xtr_raw_score_plvtr_para",
        "fountain_fullrank_use_xtr_raw_score_pvtr_para",
        "fountain_fullrank_use_xtr_raw_score_psvr_para",
        "fountain_fullrank_use_xtr_raw_score_pfintr_para",
        "common_request_type",
        "cascade_linear_score_weights",
        "fountain_mc_emb_kess_name_for_neg_feedback_sim_score",
      ],
      item_attrs = [
        "photo_id",
        "reason",
        "author__id",
        "upload_type",
        "duration_ms",
        "fullrank_ensemble_score",
        "cascade_pctr",
        "cascade_pltr",
        "cascade_pwtr",
        "cascade_pftr",
        "cascade_plvtr",
        "cascade_psvtr",
        "cascade_pcmtr",
        "cascade_ptr",
        "cascade_pcestr",
        "cascade_pepstr",
        "cascade_pwatch_time",
        "cascade_ensemble_score",
        "cascade_score",
        "dup_cluster_id",
        "sim_remove_dup_id",
        "pic_and_selfdup_id",
        "fullrank_sim_lstr",
        "fullrank_sim_pptr",
        "cascade_duration_cluster_id",
        "fullrank_detail_pcmtr",
        "fullrank_detail_pcmef",
        "fullrank_detail_pptr",
        "fullrank_detail_pepstr",
        "fullrank_detail_phtr",
        "fullrank_final_lstr",
        "fullrank_ltr_v4_fountain_next",
        "photo_like_cnt",
        "photo_show_cnt",
        "comment_ltr",
        "fullrank_ltr_v4_fountain_finish_rate",
        "fullrank_cl_score",
        "fountain_splash_slide",
        "featureACategoryLevelFour",
        "featureACategoryLevelOne",
        "featureACategoryLevelThree",
        "featureACategoryLevelTwo",
        "featurePHetuFaceId",
        "featurePHetuTagLevel4",
        "featurePHetuTagLevel5",
        "xgb_ltr",
        "hetu_tag_level_info__hetu_level_one",
        "hetu_tag_level_info_v2__hetu_level_one",
        "hetu_tag_level_info_v2__hetu_level_two",
        "hetu_tag_level_info_v2__hetu_level_three",
        "hetu_level_one_tag_index",
        "hetu_level_two_tag_index",
        "hetu_level_three_tag_index",
        "fullrank_sim_click_score_debias",
        "fullrank_sim_like_score_debias",
        "fullrank_sim_longview_score_no_bias_debias",
        "fullrank_sim_pwatchtime_no_bias_debias",
        "fullrank_ori_pswptr",
        "source_related_score",
        "hetu_level_one_v2_index",
        "fullrank_detail_new_pevtr_v2",
        "long_term_interest_ee_score",
        "cascade_long_term_interest_ee_score",
        "fullrank_sim_pwtd_playtime",
      ],
      item_num_limit = 10,
      for_debug_request_only = True,
    ) \
    .perflog_reason_count(
      check_point = "post_process_finish",
    ) \
    .copy_user_meta_info(
      save_flow_cpu_cost_to_attr = "post_process_splash_cpu_cost_ts",
    ) \

    return self
